### ISSUE TITLE
Adding an ISBN 

### ISSUE THREAD

**Issue by schansen** [pbs-assess/csasdowntex#101]
When your tech report is assigned an ISBN, how can you add it between the Cat. No. and the ISSN? 

My attempts to add it into the tech-report.sty file at lines 373 and 374 are overwritten when I knit. 

Thanks

**Comment by seananderson** [comment]
Is this the "trReportNum" below or something else?

```
Cat. No. Fs97-6/\trReportNum{} E \hfill ISSN 0706-6457\\
```

If it's that, add 

```
report_number: your-number-here
```

in index.Rmd

**Comment by schansen** [comment]
No, it's a separate number that I have been asked to include on the colophon page after the Cat. No.  
Example - PDF:
© Her Majesty the Queen in Right of Canada, 2019.
Cat. No. Fs97-6/3326E-PDF           ISBN 978-0-660-31975-9               ISSN 1488-5379

**Comment by seananderson** [comment]
OK, I added it with this commit: https://github.com/pbs-assess/csasdown/commit/bb8637dcf260b5e8ba9be7abce9127dffc255065 Hope that's what you need.

I also documented what I did in the wiki to hopefully help anyone else add any arguments needed in the future:
https://github.com/pbs-assess/csasdown/wiki/Passing-a-new-parameter-from-index.Rmd-to-a-.sty-file-in-csasdown

**Comment by schansen** [comment]
Thank-you! 

Would it also be possible to add the option of only having one line of these numbers? (e.g. the Cat. No. that ends in E-PDF, and ISSN 1488-5379)? This seems to be the library's preferred option. Currently I am getting the following, of which I only require the first two lines: 

> © Her Majesty the Queen in Right of Canada, 2019. 
Cat. No. Fs97-6/3326E          ISBN 978-0-660-31975-9               ISSN 0706-6457
Cat. No. Fs97-6/3326E-PDF           ISBN 978-0-660-31975-9               ISSN 1488-5379

**Comment by seananderson** [comment]
We can easily pull it out of the .sty file. When I checked some other recent technical reports, I only saw the E-PDF one like you mentioned. @grinnellm, was there a reason for having both of them?

**Comment by grinnellm** [comment]
I can't recall why I originally had two lines; I think one was for the PDF and one was for the electronic version? Do you remember @andrew-edwards -- I think you had a recent email about this? I think the two lines are no longer required and one line is OK, as we did in the TTT workshop proceedings.

**Comment by andrew-edwards** [comment]
TTT worked okay - just do what we did then. I think there used to be a 'printed version' number and an 'electronic version' number, which seems redundant now as they don't print them.

**Comment by seananderson** [comment]
I've removed the first line in the .sty files.
