### ISSUE TITLE
Make hyperlinks underlined in all style files

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#106]

**Comment by grinnellm** [comment]
Same for email addresses: should be blue, underlined, and normal font type (not typewriter), as on the [website](http://www.dfo-mpo.gc.ca/contact/regions/central-arctic-eng.html#Hay-River).

**Comment by seananderson** [comment]
This looks like a solution:
https://tex.stackexchange.com/a/23212
swapping out the `ttfamily` part for `sffamily` I think.

**Comment by grinnellm** [comment]
I tried that but it doesn't seem to work. Haven't commited it. I could make a branch so you can take a look?

**Comment by seananderson** [comment]
Sure

**Comment by grinnellm** [comment]
I made a branch `URLs` but it fails the tests.
I also just noticed that my last commit to master 76ad2c5 is causing Travis to fail. Might be here:
`tlmgr.pl: package repository http://muug.ca/mirror/ctan/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr.pl install: package already present: pgf
-- 1. Error: (unknown) (@tests.R#141)  -------------------------------------------------------------------------------
Failed to compile sr.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See sr.log for more info.
1: expect_warning({
       bookdown::render_book("index.Rmd", csasdown::sr_pdf(), envir = globalenv())
   }) at testthat/tests.R:141`
Sorry about this -- seems like I'm good at breaking it..

**Comment by seananderson** [comment]
Thanks. I'll look at that sometime soon. I just fixed the test: https://github.com/pbs-assess/csasdown/commit/3c5f19804509b6c9d4eb3697a4fa6741ad8df574

It just couldn't apply the number transformation to the default 'nnn'.

**Comment by seananderson** [comment]
I moved the problem part of the .sty file directly into the .tex so that we can replace it on the fly in R. See https://github.com/pbs-assess/csasdown/commit/0b2e1793d45785dfa3e4965a4eb15639c314a6c3

Are we sure that `csas-sccs@dfo-mpo.gc.ca` isn't fine for all regions? The web url is the national one.

If not, we should do other regions eventually... maybe in a loop or with lapply.

And once we decide on this I suppose we should implement these underlined links for research documents and tech reports. 

I guess we'll need to gsub all the urls into links for any random links in the document too.

Note that the current Travis problems I think are related to tikz, which some new TeX package that's been added requires. I'm trying a couple things with that. It's fine locally.

**Comment by grinnellm** [comment]
I'm not sure. The phone number is the local office, but maybe it's not necessary. Do you know why we can't just pass the variable `\rdEmail{}`?

**Comment by seananderson** [comment]
I don't know why it doesn't work with a newcommand expansion.

**Comment by grinnellm** [comment]
It's odd -- the email link works with other variables. For example, this works:
`E-mail: \link{mailto:CSA \rdRegion}{\rdEmail}\\`
except the font is tt, not sf. But it breaks if I replace `CSA \rdRegion` with `\rdEmail`:

> tlmgr search --file --global "/tikzlibrarytopaths.code.tex"
! TeX capacity exceeded, sorry [input stack size=5000].
\hyper@normalise ->\begingroup \catcode `\^^M
                                             \active \def ^^M{ }\catcode `\%...
l.1506 E-mail: \link{mailto:\rdEmail}{\rdEmail}
                                               \\ 
Error: Failed to compile sr.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See sr.log for more info.
Execution halted

**Comment by grinnellm** [comment]
Just asked CSAS and we do need region email addresses.

**Comment by grinnellm** [comment]
Also odd, the email address seems to retain the tt font. The link command in "sr.sty":

> \makeatletter
\newcommand*{\link}{\begingroup\@makeother\#\@mylink}
\newcommand*{\@mylink}[2]{\href{#1}{\sffamily\uline{#2}}\endgroup}
\makeatother

affects the internet address, but not the email address in "sr.tex":

> E-mail: \link{mailto:\rdRegion}{\rdEmail}\\
Internet address: \link{http://www.dfo-mpo.gc.ca/csas-sccs/}{www.dfo-mpo.gc.ca/csas-sccs/}\\

For example, if I replace `\sffamily` with, say `\rmfamily`, the internet address changes, but the email address stays tt font.

**Comment by seananderson** [comment]
Was the way it was coming out not OK?

![image](https://user-images.githubusercontent.com/19349/72644884-00506d00-3927-11ea-8286-6d69d0828dd1.png)

It should be easy to iterate over the other regions to get all the region emails correct in `fix_envs`. Don't need to worry about that right now.

**Comment by grinnellm** [comment]
The way it is there is OK, thanks Sean. Should I start a new issue for this?

**Comment by seananderson** [comment]
Is the issue other links in the document or the other region e-mails?

The other links in the document just need a gsub in fix_envs, but for now we should be smart and only do the substitution for Science Responses since the other preambles aren't set up for it.

Probably worth putting the email substitution in another issue so we can deal with it later.

**Comment by grinnellm** [comment]
I created `\link` commands to the Res Doc and Tech Rep style files (Eng and Fr), and I replaced all the `\href` commands with `\link`. In the "URL" branch. Should I try to merge it and close this issue?

**Comment by seananderson** [comment]
If you’ve tested it and it seems to work. I think you’ll need some gsub the hrefs that come out of Pandoc links too. I tried subbing in link on the resdoc a while ago but had some problems.

**Comment by grinnellm** [comment]
I ran `devtools::check()` and it didn't get any errors, but maybe I'll leave this as I'm not sure about the Pandoc part.
