### ISSUE TITLE
Flag in heading should be a black and white flag

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#107]
Figure in heading (for SR and maybe others?) should be a black-and-white flag.

**Comment by seananderson** [comment]
Black and white versions are in the same folder: https://github.com/pbs-assess/csasdown/tree/master/inst/csas-style/images

We just need to add back the `_bw`.

**Comment by grinnellm** [comment]
The style files use PNG images, and I didn't see black and white PNGs so I made some. Should I delete those and use the black and white GIFs? I'm not sure why some images have a PNG and a GIF..

**Comment by seananderson** [comment]
I would use these:
https://github.com/pbs-assess/csasdown/blob/018c00976e23e36205fa5c2f9dc8cbd02db14f33/inst/csas-style/images/title-header.png

https://github.com/pbs-assess/csasdown/blob/018c00976e23e36205fa5c2f9dc8cbd02db14f33/inst/csas-style/images/title-header-FR.png

which I originally pulled from the official resdoc .docx files. They may have been deleted. The extras are from a folder Dan received.

**Comment by grinnellm** [comment]
Thanks Sean, will do.
