### ISSUE TITLE
Report number needs to retain leading zeros

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#108]
For the SR, the `report_number: 004` gets shortened to "4" in the PDF; should be "004". I tried it with and without quotes, but they were both shortened.

**Comment by seananderson** [comment]
Some options:
https://tex.stackexchange.com/questions/30930/how-to-output-a-counter-with-leading-zeros

fmtcount and `\padzeroes` looks promising.

or a big if-else based on `\ifnum\value{mycounter}<10 0\fi\arabic{mycounter}`
