### ISSUE TITLE
Reduce space between tables for pages with just tables

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#109]
Should look like this:
![image](https://user-images.githubusercontent.com/25674027/72112520-aaf6d900-32f2-11ea-80bd-d6634390b754.png)
not this:
![image](https://user-images.githubusercontent.com/25674027/72112510-a3373480-32f2-11ea-8701-bc98b853be3b.png)

**Comment by seananderson** [comment]
Isn't that "just" a LaTeX floating issue?

**Comment by grinnellm** [comment]
I'm not sure, but I think we need to "squish" the vertical space between tables so that the bottom one is closer to the top of the page. I received an email from Laura Ferris (CSAS web and publications administrator) regarding this issue, #107, and email style in #106.

**Comment by seananderson** [comment]
Does it work when not letting it float to the bottom? https://stackoverflow.com/a/44888475

**Comment by grinnellm** [comment]
I've been working on this will no success yet.
