### ISSUE TITLE
Substitute regional email addresses in the "Available" section

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#110]
Currently the email is hard-coded for Pacific region (csap@dfo-mpo.gc.ca) in "sr.tex" here:
`E-mail: \link{mailto:csap@dfo-mpo.gc.ca}{csap@dfo-mpo.gc.ca}\\`.
See comments related to this in #106, specifically that we can iterate over the other regions to get all the region emails correct in `fix_envs`.

**Comment by seananderson** [comment]
It's probably a nicer user experience in the end anyways because it's one less thing to modify yourself in the index.Rmd file.

For now it will default to the national address if the document isn't for the pacific region.

**Comment by seananderson** [comment]
At least it wasn't hardcoded before this commit:
https://github.com/pbs-assess/csasdown/commit/4aac7c1ab51207adedc6a0fdaf3c74d51985f29f

Was this not working?
https://github.com/pbs-assess/csasdown/blob/4aac7c1ab51207adedc6a0fdaf3c74d51985f29f/R/utils.R#L197-L202

**Comment by grinnellm** [comment]
Not sure? I wasn't aware of that code in utils.R.

**Comment by seananderson** [comment]
Oh, there was a typo that I just fixed. That was working for me at one point.

rdRegiod -> rdRegion

**Comment by grinnellm** [comment]
That seems to work just fine:)

**Comment by grinnellm** [comment]
Would it be useful to make a table that has columns for region name, region name in French, and email? Then we could `grep` to extract the email for each region using the `region` variable. Alternatively, maybe we could use the code that you have above to insert the `email` YAML variable if it's specified in the index.Rmd? Though I agree with your comment that it might be easier for users to not have to modify an email, it's easy to do.

**Comment by seananderson** [comment]
I don’t think we have access to the yaml contents there. Yeah, an internal csv file would be helpful. Can just look through some example SRs to get them.

**Comment by grinnellm** [comment]
Shoot. I started working on a table to fill in regional emails (`email` branch), but [it seems like they depend on the province](https://www.dfo-mpo.gc.ca/contact/csas-sccs-eng.html).

**Comment by seananderson** [comment]
Ha. How about we leave the email YAML then and pass it into a nicely formatted LaTeX comment and then gsub it in via the fix_envs function.

**Comment by grinnellm** [comment]
Oops my bad. They're listed by province, but I think they're actually by region.

**Comment by seananderson** [comment]
The passing by comment might be the simplest anyways so we don't have to maintain the table when things change.

**Comment by grinnellm** [comment]
Ok, so leave it the way we have it now? I'll delete that branch.

**Comment by seananderson** [comment]
Oh, I see you're mostly done. Up to you. Feel free to just finish what you've done or to just leave it for now. Might as well leave the branch regardless.

**Comment by grinnellm** [comment]
Finished the function. I'm not sure how or where to implement it though. I can leave it for now or continue if you're able to provide some direction. No problem either way:)

**Comment by grinnellm** [comment]
I think I have it sorted, except for 2 outstanding `FIXME`s in "utils.R".

**Comment by seananderson** [comment]
It looks like you might have figure this out now. Yes, you'd need a regular expression.

I can finish this up if needed, but won't have time for a little while.

**Comment by grinnellm** [comment]
https://xkcd.com/208/
