### ISSUE TITLE
French appendices in the technical report won't work.

### ISSUE THREAD

**Issue by jordanoplante** [pbs-assess/csasdowntex#116]
Hello. I am not able to set appendices right in the french technical report. I read issue #48, but still, no success. 

My appendices are in a separate .Rmd file. The file looks like this:
`r if(knitr:::is_latex_output()) '% begin csasdown appendix'`
`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'`

## Annexe 1 {#app:annexe1}

blablabla

## Annexe 2 {#app:annexe2}

blablabla

`r if(knitr:::is_latex_output()) '% end csasdown appendix'`

**Someone knows what to do?**

**Comment by seananderson** [comment]
I took the built-in template, changed the language to French, and rendered the technical report. I think it looks correct, but maybe I'm wrong. What specifically is the problem?

Here's my test folder:
https://www.dropbox.com/sh/4pjzkiu5h3k7tf2/AABrzSqS8Iyg7mTYHO3EY8Uha?dl=1

**Comment by jordanoplante** [comment]
Thanks @seananderson. Everything is fine excepted that in the table of content:

1. It mentions _Appendices_ instead of _Annexes_
2. Appendices A and B are not indented

Maybe the solution for this would be to not show _Appendices_ in the table of content? It makes sense as no header for _Appendices_ is found in the pdf before _Appendix A_.

**Comment by jordanoplante** [comment]
Also, in your example, the _Appendices_ section is not numbered. Shouldn't it be Number 5 and the section _References_ number 6?

**Comment by seananderson** [comment]
I fixed Appendices -> Annexes: https://github.com/pbs-assess/csasdown/commit/f52fc272ac3d909c29f67578554e37d129d4d36b

The rest is fine as is, I think. The appendices are not numbered. Maybe I'm not understanding "Appendices A and B are not indented".

**Comment by jordanoplante** [comment]
Thanks @seananderson. As for the indentation, it's really a minor thing. If you open the rendered pdf found within the dropbox link you sent earlier, you will see within the bookmarks viewer pane of your pdf viewer that _Appendices A_ and _B_ are not nested within the _Appendices_ bookmark.

With other headings and subheadings (ex: heading _Methods_ created with `# Methods` and sub-heading _Sampling at-sea_ created with `## Sampling at-sea`), the bookmark _Sampling at-sea_ will be nested within the _Methods_ bookmark.

It doesn't work for appendices. If you try to change the heading levels of the 2 appendices in the dropbox by adding an extra # sign (ex: `# THE FIRST APPENDIX {#app:first-appendix}` will now be `## THE FIRST APPENDIX {#app:first-appendix}`, the rendered pdf will show Appendices A and B with different names:

-  `.1 THE FIRST APPENDIX`
-  `.2 THE SECOND APPENDIX, FOR FUN.`

Do you get my point?

**Comment by seananderson** [comment]
Ah, I see. I'm not really sure how Acrobat interprets the PDF structure for creating the bookmark indentation. I don't have time to dig into this right now, and I'm not too worried about it as is. Generally the formatting isn't as strict for the technical reports.

If someone else wants to dig into that, that's fine, but for now I'm going to close this.
