### ISSUE TITLE
Reference section in french tech report says "References" instead of "Références citées"

### ISSUE THREAD

**Issue by jordanoplante** [pbs-assess/csasdowntex#117]
I cannot find where to modify the code so it says "Références citées" instead of "Références" in the french tech report.

**Comment by seananderson** [comment]
You need to change it yourself in your .Rmd file:
https://github.com/pbs-assess/csasdown/blob/ffebb2f5719c9d8a7d5bc27e80a185369402d25a/inst/rmarkdown/templates/techreport/skeleton/06_bibliography.Rmd#L6-L10
