### ISSUE TITLE
Add list of known reports using csasdown to README

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#121]

**Comment by cgrandin** [comment]
I put a section header into the README for this, if you could put your publication citations in there that would be  a great help in showing how csasdown is being used. Also if you know of anyone else that has used it and published it would be good to add those as well. Thanks

**Comment by seananderson** [comment]
@schansen, what's the status of the Abalone Pre-COSEWIC? Can we list it among the reports that have used csasdown?

**Comment by schansen** [comment]
It's not quite done yet. The supporting tech report was done in csasdown though. 
http://waves-vagues.dfo-mpo.gc.ca/Library/40849296.pdf

**Comment by seananderson** [comment]
Awesome, thanks. I've added the tech report. Let us know when we can add it, even if it's just in review or approved but not posted yet.

**Comment by SOLV-Code** [comment]
Here's another one:
https://waves-vagues.dfo-mpo.gc.ca/Library/40890041.pdf
