### ISSUE TITLE
Fix csl to disambiguate citations by citation order

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#124]
Example copied from elsewhere:

> Article 1 Smith et al. 2010 Computer engineering
> Article 2 Smith et al. 2010 Linear Programming
> Article 3 Smith et al. 2010 Software developping

> and I have the following text:
> bla bla bla bla bla, (Smith et al. 2010a), bla bla bla bla bla (Smith et al. 2010a, 2010b, 2010c)

Currently our .csl file will sort them according to how they appear alphabetically in the bibliography. I believe it is CSAS style to sort them according to order of appearance. Noted over here https://github.com/pbs-assess/yelloweye-inside/issues/19

Apparently this is fairly easy to fix.

Taken from here https://forums.zotero.org/discussion/21779/disambiguate-year-suffix-problems-with-the-suffixes

"
For general instructions, see here:
http://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step
Specifically, find the bibliography section of the style - it starts with <bibliography>
right after that, it will define the sort order. That will be something like

```
<sort>
<key macro="author"/>
<key macro="year-date"/>
<key macro="title"/>
</sort>

Change that to:
<sort>
<key macro="author"/>
<key macro="year-date"/>
<key variable="citation-number"/>
<key macro="title"/>
</sort>
```

The key is to have the citation-number line after the year-date (or issued, or issued-date - depends on the style) line. The "title" line may or may not exist. If you have any trouble we need to know which style you're looking at.
"

**Comment by cgrandin** [comment]
I did all 6 **csl** files. I think it's what you meant. The order for a given year with the same author will appear as 2010a, 2010b, 2010c, etc in the text but may be out of alphabetical order by title for those particular ones in the bibliography. The author alphabetization in the bibliography is as it should be.

**Comment by seananderson** [comment]
Thanks for giving it a quick shot. Unfortunately, this doesn't seem to do what I was hoping to achieve.

First, it may be worth checking with CSAS/P to make sure this is actually what they want, since apparently as of APA style 5 and onwards, the current sorting is correct.

Screenshots of the problem:
![image](https://user-images.githubusercontent.com/19349/79780925-88ad2800-82f1-11ea-97bc-f1998520f7cb.png)

which is of course sorted correctly in the bibliography but not according to the order of appearance by first author's last name and year:

![image](https://user-images.githubusercontent.com/19349/79780952-95318080-82f1-11ea-8c72-077154da67f8.png)

Example res doc here:
https://www.dropbox.com/sh/8k5mfs9ipfb7j3o/AABX1LIL0YHGMJvvcAEyE9sxa?dl=1

This seems like a tricky thing to google, but I did stumble across this:
https://forums.zotero.org/discussion/70140/in-text-citation-error-when-an-author-has-two-publications-with-the-same-year

They hint at something to do with `givenname-disambiguation-rule="primary-name"` but I can't get that to work properly. That might be a dead end. But disambiguation rules are keywords.

**Comment by cgrandin** [comment]
I may not understand the issue.. So if we want the references re-ordered so that **a** appears before **b** in the document text, the only way to do that correctly is to re-order them in the bibliography which is what I did in my commit. 

I just checked and of course it worked when I tested it with my example references, but not with your example. I'll look into it.

**Comment by seananderson** [comment]
Not sure what your original test was, but it's possible that this has been fixed for cases where the author list is identical between the two references. In my example, it's just the first author and year that is identical. As I mentioned, it might be worth checking the CSAP rules carefully if this turns out to be tricky, because maybe we don't need to do this.

**Comment by cgrandin** [comment]
Yes, my test was just a copy of a ref. If you make a copy of the anderson2020gfmp reference in refs.bib and give it a different tag, then the ordering works as it should.

**Comment by seananderson** [comment]
Sounds like we don't need to worry about this after the email from Ann.
