### ISSUE TITLE
Word Version of Tech Report is Not a Tech Report

### ISSUE THREAD

**Issue by NormOlsen** [pbs-assess/csasdowntex#128]
Creating a PDF version of a tech report via csasdown::draft("techreport") produces a standard Canadian Technical Report of Fisheries and Aquatic Sciences. Creating a MS Word version of the same results not in a technical report, but rather a Canadian Science Advisory Secretariat Proceedings Series. Screenshots attached.

PDF version:
![image](https://user-images.githubusercontent.com/6886169/80717324-a9be0780-8aad-11ea-85e4-8f821f46e474.png)

Word version:
![image](https://user-images.githubusercontent.com/6886169/80717413-c22e2200-8aad-11ea-812d-3af53231949e.png)

**Comment by cgrandin** [comment]
This shows how often we actually compile to Word.. I never noticed this! I labelled this as a bug but it doesn't break the build so I'll come back to it later

**Comment by NormOlsen** [comment]
Thanks Chris, I'm switching to the PDF version now so definitely no hurry
on this one. Just wanted to let you know. Cheers.

**Comment by seananderson** [comment]
Just means I must have dropped the wrong .docx template into the package. It grabs the style from that. I'll fix. I've used the Res Doc Word version, but that's it.

**Comment by NormOlsen** [comment]
Thanks Sean, I *think* I've managed to convince our team to use the PDF
version anyway, but having the Word option available is very nice.

**Comment by seananderson** [comment]
I realized that I don't have a Tech Report .docx template. It's not part of the official zip folder of CSAS templates... probably because it's not technically CSAS. Can someone send me a template or even an existing doc I can pull the styles from?

**Comment by NormOlsen** [comment]
Hi Sean, I've attached two examples here.
[SofG2012_report_sept2013FINAL.docx](https://github.com/pbs-assess/csasdown/files/4561298/SofG2012_report_sept2013FINAL.docx)
[Surry&King ALPI TR (final).docx](https://github.com/pbs-assess/csasdown/files/4561300/Surry.King.ALPI.TR.final.docx)

**Comment by cgrandin** [comment]
`PRO-CR2016-eng.docx` and `PRO-CR2016-fra.docx` need to be replaced in `inst/csas-docx`, @seananderson do you have those?
If so, did you get them from a CSAS website or something? If so, what's the link..

**Comment by seananderson** [comment]
I do not! I believe technically the Tech Reports are not part of CSAS and so they don't come with the same template package. I assume they can be downloaded from this intranet site: http://intra.dfo-mpo.gc.ca/intracom/report/template/index_e.htm but I would have to sign on the VPN to check.

**Comment by cgrandin** [comment]
Thanks. I got the covers from there but I don't know where this header part comes from or is set up for tech reports:

![image](https://user-images.githubusercontent.com/4551051/94735550-c641c280-031f-11eb-9c8d-15cfee95e196.png)

**Comment by seananderson** [comment]
Should be fixed now. https://github.com/pbs-assess/csasdown/commit/5056b12956d4e2b89984c8d126ff07cf3fa6ca52
