### ISSUE TITLE
Heading 5 not formatted according to CSAS requirements

### ISSUE THREAD

**Issue by brendanmichaelconnors** [pbs-assess/csasdowntex#130]
I am unable to render heading 5 according to CSAS layout requirements (from CSAS office "arial 11 italics, pt 6 below and after the heading in terms of spacing, indented just past where heading 4 is indented").

It appears as though heading 5 (i.e., #### header 5) returns the same format as heading 4 (i.e., ### header 4).

Has anyone else run into this?

Perhaps adding something like this to the sr.sty file would do the trick?:

\renewcommand{\subsubsubsection}{\@startsection
{subssububsection}{5}{0.75cm}
{-1.5ex \@plus -0.25ex \@minus -.1ex}
{0.5ex \@plus.1ex}
{\normalfont\bf}}

**Comment by seananderson** [comment]
You may be the first person to go 5 headings deep. :)

Thanks for the suggested code.

**Comment by cgrandin** [comment]
Yes, it only goes 4 deep. I suppose we thought nobody would want more!
I can try to fix this

**Comment by cgrandin** [comment]
Here's why we stopped there: https://texfaq.org/FAQ-subsubsub

So the fix I just made doesn't work. There is a possible way but it is a hack and will probably take me a lot of time. I suppose I'm asking if you could re-organize your doc so that it doesn't go 5 levels deep?

**Comment by seananderson** [comment]
If it's simple then go for it. We can also just stop at four levels deep if that's going to make for some more complicated hard-to-maintain code.

**Comment by brendanmichaelconnors** [comment]
Thanks for looking into this @cgrandin. No problem re-organizing things to only go 4-levels deep.

**Comment by cgrandin** [comment]
I’ll put something in the wiki FAQ about the reasons behind this limitation.
