### ISSUE TITLE
Specify correct International Standard Serial Number (ISSN) for french SRs

### ISSUE THREAD

**Issue by brendanmichaelconnors** [pbs-assess/csasdowntex#131]
csasdown is rendering the same ISSN for both english and french SRs. The CSAS office has asked me to change the ISSN on the last page in a french version of an SR to "1919-3815". 

Can anyone advise on how I might go about doing this? 

Merci beaucoup!

**Comment by seananderson** [comment]
Does it need to print both English and French ISSNs in the same PDF? If they are two separate PDFs then just change the ISSN in each version. If they both appear in the same PDF then we might need to fix this.

**Comment by brendanmichaelconnors** [comment]
It just needs to print a single ISSN in each PDF. It is just not immediately clear to me where to manually change the ISSN...

**Comment by seananderson** [comment]
What should it be? I assume it's the same for all reports? We need to change it in the .tex here:
https://github.com/pbs-assess/csasdown/blob/af2044e736f1c67788f30aa69b55b65d7c6f0d57/inst/csas-tex/sr-french.tex#L116

**Comment by brendanmichaelconnors** [comment]
It should be 1919-3815 and yes I believe it is the same for all reports. I've made a pull request.

**Comment by seananderson** [comment]
Thanks for making the change. Could you add this report to the list of publications in the README.md file?

That list is getting long enough we should probably move it lower in the readme eventually.
