### ISSUE TITLE
Document accessibility - table tagging

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/csasdowntex#134]
This can probably go into the Wiki once we are all satisfied with it.

I went through the table tagging issues CSAS has with csasdown documents.

This image is what is should look like, and what we get when we use `\begin{longtable}`:
![image](https://user-images.githubusercontent.com/4551051/81903741-0e319a00-9577-11ea-97e0-012c34bd2e03.png)

There are \<TR\> tags, with sub-tags \<TH\>, one for each column header, followed by one \<TR\> tag for each row with sub-tags \<TD\>, one for each cell in that row. So it's basically all good.

This image is what it looks like if we use `\begin{table}`:
![image](https://user-images.githubusercontent.com/4551051/81903962-6f596d80-9577-11ea-9b0b-dc7a13ca9929.png)

All the parts of the table are tagged as paragraph \<P\>. Not good, as the CSAS office have to re-construct the tags one-by-one for all the tables.

So if we use longtables for everything it will be fine except for one major problem. You can have one section title and text above all the tables. If you add another section and/or any text below the tables it will destroy the tagging on all the tables. Luckily for us, adding a `\clearpage` resets this and we can have another section with longtables.

The default in `csasdown::csas_table()` is `longtable = TRUE` so there are no changes but we will have to stipulate that all tables in a document going to CSAS must be in their own "Tables" section. So, no tables inline with text.

I confirmed that this works with a real resdoc that I'm working on (arrowtooth), but noticed that if you have `echo=true` in the knitr chunk, so that you are showing the code that produces the table, it thinks that the code itself is the table and the table is made of paragraphs. Not that we do that for CSAS docs but something to be aware of.

@brendanmichaelconnors Ann gave me a copy of the Sablefish MSE resdoc in PDF and some of the tables are showing this issue. They are in a "Tables" section so my guess is that you called `longtable = FALSE` but let me know if that is not the case and we can look more closely.

**Comment by brendanmichaelconnors** [comment]
Thanks for having a look at the Sablefish SR doc @cgrandin. As far as I can tell all tables in the doc are with the default `longtable = TRUE`. Can you let me know which tables are showing the issue?

**Comment by cgrandin** [comment]
Table 3 "Price per pound..."
Table 4 "Weighted economic.." - But this is landscape and I didn't test for that yet

Table 9 "Ageing error... " This is probably because there is a figure following it. You can't have anything following a table or it messes up the tagging. One solution is to have two sections in the appendix, one for tables and one for figures with a \clearpage between them. You may also get away with just adding a \clearpage after the appendix table since there is a new page there anyway. I also noticed that your table and figure numbering is wrong for everything in appendix A (The references in the main body are for Figure A.1 for example but it is labelled Figure 8 in the appendix). I think it is because you didn't put this at the beginning of the Appendix:

`r if(knitr:::is_latex_output()) '% begin csasdown appendix'`
`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'`

and this at the end:

`r if(knitr:::is_latex_output()) '% end csasdown appendix'`

**Comment by cgrandin** [comment]
I just figured out that sometimes the longtables still fail to render tags correctly. When I make the format latex it seems to fix it.

```
csas_table(format = "latex")
```

@seananderson can you think of an issues arising from making `format = "latex"` the default? Right now it's "pandoc"

**Comment by seananderson** [comment]
> can you think of an issues arising from making format = "latex" the default? Right now it's "pandoc"

The only issue is that the table then won't work for Word output. We could not worry about that or maybe flip that argument value based on the rendering format.

Fantastic that it's as simple as using long table and having a clearpage after.

I suggest we set up csas_table so that it's always long table and not configurable.

**Comment by brendanmichaelconnors** [comment]
Thanks @cgrandin for the feedback. To ensure tags are rendered correctly I have (1) made the format "latex" in all tables and (2) ensured there are no figures that directly follow a table by using \clearpage between tables and figures in the appendix. I am not sure how to check a PDF for tags so am assuming this has had the desired effects and will ask Ann to confirm.

To maintain consistency with other recently published SRs (i.e., the herring one) I have kept the figure #s as a continuation of those in the main text and have not restarted and prefixed them with an "A" in the Appendix.
