### ISSUE TITLE
Allow 'Canadian Technical Report of Hydrography and Ocean Sciences'

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#135]
From an e-mail:

> [...] I am about to write a Canadian Technical Report of Hydrography and Ocean Sciences [...] My question is: how do I change the name of the report.  I tried doing this in the tech-report.sty but this file gets overwritten when you knit the project.

My response:

> We would either need to pass the type of report through from the index yaml header into the .sty file or create some options so you can stop the .sty file from getting overwritten so you can hand modify it yourself. The reason I set it up so that the .sty file gets overwritten is so that people can update the R package and get any new changes to the .sty files. The reason we even bother to put the .sty file in the user's directory (not just keeping it within the R package library directory) is that some people's DFO computers have folder permission problems running TeX on files in their R package library.

I wonder if just checking for some tag in the yaml that stops the .sty file from getting overwritten would be a good and generic solution to a lot of problems?

**Comment by cgrandin** [comment]
My guess is that just changing the title in index.Rmd doesn’t do it, this is more like a fourth type of document in csasdown which would have to be implemented

**Comment by seananderson** [comment]
But my understanding is that this is likely just changing "Technical Report" to "Technical Report of Hydrography and Ocean Sciences". If so, doesn't need a new template. Allowing someone to 'freeze' the .sty file would also let someone use it for a "Manuscript Report" (I think I have that name right). Different than the title in index.Rmd.

**Comment by cgrandin** [comment]
I need a break from the hake MSE code, I'll take a look at this

**Comment by seananderson** [comment]
Thanks. Could possibly pass an option from index.Rmd all the way down to `update_csasstyle()` that won't overwrite an existing .sty (so that it will copy the first time).
https://github.com/pbs-assess/csasdown/blob/7453f41a06c4b5072e77884a3164b82506609a0c/R/utils.R#L181-L185

**Comment by seananderson** [comment]
Or just pass the report type through and be done with it. This might be the only case, although this might alleviate other smaller requests like changing the ISSN down the road.

**Comment by cgrandin** [comment]
So this should work now. If there's a project already started, you will have to add a line to `index.Rmd`. In the YAML header part add the `copy_sty` line:

```
output:
 csasdown::techreport_pdf:
   french: false
   copy_sty: false
```
All new projects will have this line included, e.g. one created from one of these:
```
csasdown::draft("sr")
csasdown::draft("resdoc")
csasdown::draft("techreport")
```
