### ISSUE TITLE
Adjusting font size of captions in for Tech Reports

### ISSUE THREAD

**Issue by carrieholt** [pbs-assess/csasdowntex#137]
I'd like to make the font sizes for captions in Tech Reports the same as the font size in the rest of the report. How do I do this? Font size for captions are currently larger.

**Comment by seananderson** [comment]
Strange. Try it now after reinstalling csasdown.
<img width="310" alt="image" src="https://user-images.githubusercontent.com/19349/83436541-e35a9900-a3f2-11ea-97f6-ddb9d3203f0c.png">

**Comment by carrieholt** [comment]
Great! thanks.
