### ISSUE TITLE
Page numbering when table of contents spans more than one page

### ISSUE THREAD

**Issue by NormOlsen** [pbs-assess/csasdowntex#138]
When generating a pdf tech report with a table of contents that spans more than one page, the page numbers for the abstract and resume (which follow the contents) are off by [number of pages in table of contents] - 1

**Comment by cgrandin** [comment]
I tried inflating the TOC in the tech report example to 2 pages and the numbering is correct. That is the citation says the last page should be `vi` and it is (RESUME page). Is your abstract larger than one page?

**Comment by cgrandin** [comment]
I also made the TOC three pages and everything is correct.

**Comment by cgrandin** [comment]
I also made the abstract go to 2 pages, with the TOC at three pages and everything looks fine. Hmmm

![image](https://user-images.githubusercontent.com/4551051/83551367-1ff2c700-a4bd-11ea-8931-f55e43768146.png)

**Comment by NormOlsen** [comment]
No, my abstract is just one page. So there must be something about my version of tech-report.sty that's causing this. I'll carefully compare it to the default template and see if I can spot anything.

**Comment by cgrandin** [comment]
You shouldn't have to do that because the file is copied every time you compile the doc. Make sure you have the latest csasdown installed, and then as a check you can delete the csas-style folder manually from your project, then rebuild and it will re-appear.

**Comment by cgrandin** [comment]
If you send me a copy of the project I can take a look

**Comment by NormOlsen** [comment]
But I have a customized tech-report.sty (I converted it to a manuscript report style). What I'm doing now is going back to the default tech-report.sty and see if the problem is resolved.

**Comment by NormOlsen** [comment]
Still getting the same issue. Here's a zipped archive of my project. Thanks for having a look!
[TrawlCruiseReport.zip](https://github.com/pbs-assess/csasdown/files/4718814/TrawlCruiseReport.zip)

**Comment by cgrandin** [comment]
Do you have one with local data files? I cannot connect to the network to grab the data from this machine..

```
 Error: nanodbc/nanodbc.cpp:983: 01000: [Microsoft][ODBC SQL Server Driver][Shared Memory]SQL Server does not exist or access denied.  [Microsoft][ODBC SQL Server Driver][Shared Memory]ConnectionOpen (Connect()). 
```

**Comment by NormOlsen** [comment]
Oh right of course. No I don't. The code uses a bunch of SQL Server stored procedures. That would be a big job to convert it all into using local data files. I'll keep plugging away on it myself. Thanks for the offer.

**Comment by NormOlsen** [comment]
Chris, are you using tinytex?

**Comment by cgrandin** [comment]
Yes, tinytex - see https://github.com/pbs-assess/csasdown/wiki/LaTeX-installation-for-csasdown

**Comment by seananderson** [comment]
@NormOlsen Can you strip it down to a minimal reproducible example that shows the problem without pulling in any data? You could comment things out in bookdown.yml. Probably just needs the first few pages.

**Comment by NormOlsen** [comment]
I stripped out all my R chunks and the problem disappeared. So now I'm just going to start with everything back in and iteratively comment-out/compile until I can isolate the offending chunk.

**Comment by NormOlsen** [comment]
I believe I've solved it! I hope so, after many hours of hacking at it. The page numbering problem appears to happen whenever a table gets split across more than one page, but only if the "repeat_header" kableExtra option is set:
`kableExtra::kable_styling(latex_options = "repeat_header")`

** Edit: The problem also only appears if you have the csas_table "caption" option set. If you remove the caption the "repeat_header" option works without messing up the page numbers.

**Comment by cgrandin** [comment]
Great! Do you have a minimal working example (without database reliance) that I could take a look at? If so maybe this can be fixed or at least I could document the behaviour..

Is the offending table after the roman numeral pages? If so, that's really weird. It wouldn't be the first time I said that about something in LaTeX though!

**Comment by NormOlsen** [comment]
I'll get an non-db example ready for you and post it here. The tables involved were in the results section so well after the roman numeral pages. And yes, I thought that was super weird as well!

**Comment by NormOlsen** [comment]
Here you go @cgrandin The attached example is setup to reproduce the problem. There is a table at the end of the introduction that spans two pages. If you leave the "repeat_header" option in, the roman numeral pages reported in the ToC are wrong. If you comment out the "repead_header" option, the page numbering is correct.
[PageNumberTest.zip](https://github.com/pbs-assess/csasdown/files/4725246/PageNumberTest.zip)

**Comment by cgrandin** [comment]
Thanks! You need to use the `repeat_header` argument in `csas_table()` instead of piping using `kable_styling()`. So you need to change your table code from this:

```
csasdown::csas_table(df,
                     caption = "Caption text",
                     format = "latex",
                     landscape = FALSE,
                     font_size = 7) %>%
kableExtra::kable_styling(latex_options = "repeat_header")
```

to this:

```
csasdown::csas_table(df,
                     caption = "Caption text",
                     format = "latex",
                     landscape = FALSE,
                     font_size = 7,
                     repeat_header = TRUE)
```

I remember this issue now back when I added `repeat_header` to the function. You need to have the extra argument `repeat_header_method` for `kable_styling()` set to "replace" otherwise it uses "append" which tells Latex it is on the same page for some internal reason. This is coded as the default in `csas_table()` so you don't have to worry about it.

Anyway that should solve the issue :) If it does, feel free to close this issue!

I'm going to add this to the Wiki in case it comes up again.

**Comment by NormOlsen** [comment]
Awesome, thanks so much @cgrandin I'm closing this issue now.
