### ISSUE TITLE
csas_table parameter "repeat_header = TRUE" not working?

### ISSUE THREAD

**Issue by NormOlsen** [pbs-assess/csasdowntex#139]
Using the csas_table parameter "repeat_header = TRUE" does not appear to work. After a page break there is no header at the top of the continued table.

```r
df <- read.csv("data/table01.csv")
names(df) <- c("Species", "Scientific Name", as.character(2016:2025))
csasdown::csas_table(df,
                     caption = "Length-stratified species age sample schedule by year for all Fisheries and Oceans Canada Pacific Region synoptic bottom trawl surveys.",
                     format = "latex",
                     landscape = FALSE,
                     font_size = 7,
                     repeat_header = TRUE)
```

![image](https://user-images.githubusercontent.com/6886169/83803521-96c8c500-a661-11ea-9e08-ef076591a44e.png)

**Comment by cgrandin** [comment]
Actually don't need an MWE. I replicated the issue. I thought I tested this.

**Comment by NormOlsen** [comment]
Thanks for formatting my code example properly!

**Comment by cgrandin** [comment]
You don't need to include `repeat_header` at all, it is the default. I had forgotten to do the repeat header stuff for non-landscape tables. Should be fine now
