### ISSUE TITLE
tinytex or LaTeX problem suddenly started today

### ISSUE THREAD

**Issue by SOLV-Code** [pbs-assess/csasdowntex#141]
Hi,

I've been using csasdown for several tech reports, and was able to make everything so far work based on the detailed examples and wiki. But today all the tech reports suddenly stopped working. It seems to generate the md document fine, but then runs into problems with the pdf conversion.  At first I thought that something got messed up in the report I was modifying, but after removing the new table didn't fix it, and uninstalling/re-installing the tinytex package in Rstudio didn't fix it, I decided to try other reports that worked fine just yesterday, and they run into the same error.

```
output file: SBC_CK_Data_TechReport.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS SBC_CK_Data_TechReport.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output SBC_CK_Data_TechReport.tex --self-contained --table-of-contents --toc-depth 2 --template "C:\Users\jeffv\Documents\R\win-library\3.6\csasdown\csas-tex\tech-report.tex" --number-sections --highlight-style tango --pdf-engine pdflatex --lua-filter "C:/Users/jeffv/Documents/R/win-library/3.6/rmarkdown/rmd/lua/pagebreak.lua" --lua-filter "C:/Users/jeffv/Documents/R/win-library/3.6/rmarkdown/rmd/lua/latex-div.lua" --top-level-division=chapter --wrap=none --include-in-header "C:\Users\jeffv\AppData\Local\Temp\RtmpuiDDIV\rmarkdown-str26906f472a02.html" --variable tables=yes --standalone -Mhas-frontmatter=false --filter "C:/Program Files/RStudio/bin/pandoc/pandoc-citeproc.exe" 
tlmgr.pl: package repository http://ctan.mirror.globo.tech/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr.pl install: package already present: pdftexcmds
! LaTeX Error: File `pdftexcmds.sty' not found.

! Emergency stop.
<read *> 

Error: LaTeX failed to compile SBC_CK_Data_TechReport.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See SBC_CK_Data_TechReport.log for more info.
In addition: Warning messages:
1: package 'dplyr' was built under R version 3.6.3 
2: package 'ggplot2' was built under R version 3.6.3 
3: package 'tibble' was built under R version 3.6.3 
4: package 'purrr' was built under R version 3.6.3 
Execution halted
```

## Update 1
As per [this](https://github.com/pandoc/dockerfiles/issues/65) and [this](https://github.com/pandoc/dockerfiles/issues/65), the error might be with pandoc, but reinstalling pandoc did not fix the problem.

## Update 2

Maybe it is a tinytex problem, as per [this](https://tex.stackexchange.com/questions/518757/module-pdftexcmds-not-found-after-update).  I'll try switching to MikTex.

## Update 3

MikTex is temporarily offline (see [here](https://github.com/MiKTeX/miktex/issues/574))

## Update 4

Tex Live install had an error, but seems to be proceeding regardless. Taking a very long time though...
```
TLPDB::_install_data: downloading did not succeed (check_file_and_remove failed) for http://mirror.its.dal.ca/ctan/systems/texlive/tlnet/archive/texlive.infra.win32.tar.xz
TLUtils::install_packages: Failed to install texlive.infra.win32
                           texlive.infra.win32 will be retried later.
Installing [0003/4010, time/total: 00:56/123:17:00]: tlperl.win32 [6816k]
```

**Comment by cgrandin** [comment]
Sometimes on Windows my tinytex dies and I get errors like these. I wrote a wiki to address it. If you try this it may fix your issue: https://github.com/pbs-assess/csasdown/wiki/LaTeX-installation-for-csasdown

**Comment by SOLV-Code** [comment]
Hi Chris,

thank you for the quick reply!

TexLive is taking *forever* to install (it's at an 1:40 now, and still installing various libraries/pkgs etc), so I'll abort, remove tex live bits and MikTex as per your wiki, and just try again with tinytex.

It helps to know that this is something that just happens every so often, and just stick with tinytex re-install.
Will let you know.

Cheers,
Gottfried

**Comment by SOLV-Code** [comment]
Hi Chris,

Thank you! that worked.

I think my problem was that I used
```
remove.packages("tinytex")
install.packages("tinytex")
library(tinytex)
```
which didn't fix it (in hindsight: of course not!)

Rather, it needed
```
tinytex::install_tinytex()
```
as per your wiki.

Should I add a note regarding this cul-de-sac to the wiki?

Cheers,
Gottfried

**Comment by cgrandin** [comment]
I'm glad to hear it! I pulled my hair out several times with this annoying issue.
The tinytex install guide already mentions `tinytex::install_tinytex()` so I would say the wiki is good as it is.

**Comment by SOLV-Code** [comment]
OK, thanks again. I'll close this issue.

Heads up: I've been compiling a list of questions (small formatting stuff), and will create an issue for those sometime next week.

Cheers,
Gottfried
