### ISSUE TITLE
Formatting changes to SR requested by CSAS

### ISSUE THREAD

**Issue by briannamwright** [pbs-assess/csasdowntex#143]
Hi,
Recently sent a SR doc into CSAS that was built using csasdown and they sent back these requested formatting changes, which I believe need to be changed within the source code, so not something I can easily address myself. Any assistance is greatly appreciated!

- Add a colon after “This report is available from the:” and also add a colon in the French version, but there should be a space before the colon in the French version, i.e. “Le présent rapport est disponible auprès du :”
- In the English version, capitalize “Correct Citation for this Publication:”, and left align it, the French version should also be left aligned and have a space before the colon, but is not capitalized except the first word: “La présente publication doit être citée comme suit :”
- In the section entitled “Correct Citation for this Publication”, they would like the hanging indent to be aligned with the “O” in DFO and MPO, right now it’s too far to the right.
- They want more space between the last line of text and the footer on the first page in the French version
- They want more space above the footnotes (they did not say how much – maybe a half line?)

**Comment by cgrandin** [comment]
Hi Brianna,

I have fixed most of this but I don't understand what they mean by this:

```In the section entitled “Correct Citation for this Publication”, they would like the hanging indent to be aligned with the “O” in DFO and MPO, right now it’s too far to the right.```

It looks like what they want? I can also make it so that eh citations are flush with the left or indented.

![image](https://user-images.githubusercontent.com/4551051/87468439-7c71f780-c5ce-11ea-853f-f08868df8a17.png)

French:
![image](https://user-images.githubusercontent.com/4551051/87467452-d07bdc80-c5cc-11ea-829b-e8e080a9aee8.png)


Wow, it sounds like they are eyeballing the space between the footnotes and guessing at the specs.

**Comment by briannamwright** [comment]
Hi Chris,
Thank you so much for looking at this so quickly! I think for the Correct
Citation section, my understanding was that the first line of the citation
was to be left-aligned, and the second line was to be indented. So
basically it's supposed to look like the French version you sent but the
first line of "MPO. 20XX." etc. should be left-aligned with "La presente
publication..." above it. Does that make sense? Sorry it's hard to describe
and they're being really picky! Attached is my current PDF render in
English, which is left-aligned but has a larger hanging indent than they'd
like.

Thanks for your help!
- Brianna

**Comment by cgrandin** [comment]
Ok I think everything on your list is done except the spacing issues (last two bullets). I don't see an attached PDF of your docs, could you attach them again? Thanks

**Comment by seananderson** [comment]
I'm working on this right now. Should look like this I think.
![image](https://user-images.githubusercontent.com/19349/87570414-7be46a00-c67d-11ea-9797-6e61770b3b2e.png)

**Comment by briannamwright** [comment]
OK, thanks Chris - attached are the French and English versions of my PDF,
as they appeared when I sent them into CSAS.

Thanks for your help on this,
- Brianna

**Comment by seananderson** [comment]
I fixed the citation indentation:
![image](https://user-images.githubusercontent.com/19349/87571267-a08d1180-c67e-11ea-92f1-aec0e5584185.png)

@briannamwright, I think you'll need to email us the PDF or upload somewhere and post a link. I don't think GitHub issues will show an attached PDF.

**Comment by briannamwright** [comment]
Fantastic! Yes I think that's exactly how they want it. Thanks for doing
this - I will re-render and let you know if I run into any issues. Thanks
so much for your time!

- Brianna
