### ISSUE TITLE
Page Numbers for English and French abstracts

### ISSUE THREAD

**Issue by SOLV-Code** [pbs-assess/csasdowntex#148]
Thank you for the rapid fixes of the cover page issue (#146), but there is one more unresolved issue holding up publication of a tech report.  I've got 3 more in development with the same issue, but those submissions are a while away...

*The page numbers in the citation on the colophon page are wrong, as well as the page numbers for English and French abstracts.*

We have a very long table of contents.

This [just-published tech report](https://waves-vagues.dfo-mpo.gc.ca/Library/40889385.pdf) has the same page number for the front matter (v) as the knitted version of our report. In their case it is correct, because the TOC is only 1 page. Then the english and french abstracts are pages *iv* and *v*. In our case these should be *xiii* in the citation, and *xii* and *xiii* for the abstracts in the TOC. Maybe *iv* and *v* are hard-wired somwhere?

We tried fixing it in the pdf, but weren't able to match fonts...

**Comment by seananderson** [comment]
I assume this is an issue with a longer TOC. Hopefully it is fixable without too much work. I think this was a copied and pasted comment from elsewhere, but the cover page and inside cover is no longer an issue. See here https://github.com/pbs-assess/csasdown/issues/146#issuecomment-699401270

**Comment by SOLV-Code** [comment]
Yes, this was originally in the thread for #146

**Comment by seananderson** [comment]
Can you send me a (minimal) reproducible example that demonstrates this? I don't think I can reproduce it. The page numbers are not hard wired and this minimal version with a long TOC is working, unless I'm misunderstanding the problem:
https://www.dropbox.com/sh/6l2tzzq08feznx2/AAAn8YZ9qfTjXwQdEMKXQen3a?dl=1

(See `techreport.pdf` in the _book folder.)

**Comment by SOLV-Code** [comment]
I've put the 3 examples [here](https://www.dropbox.com/sh/os9qpnpxc4c6kg9/AACM2uOQhXuy4LCBd2SCJanpa?dl=0). I've also given you access to the repositories, just in case that's helpful.

I can see that this is not happening in your example. I'm comparing the pieces to look for something that got muddled in how I've set up the index.Rmd

**Comment by seananderson** [comment]
I can see it's an issue but I'm not sure why. If you can come up with a minimal reproducible example then I can debug it.

I created an issue template for the future, which might help: https://github.com/pbs-assess/csasdown/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

You could either build up an example to recreate it or strip back your report to something minimal that still has the problem.

**Comment by SOLV-Code** [comment]
good point. 

I'll build try to build a reproducible example as per the template, then start a new issue.

Thank you!
