### ISSUE TITLE
Create RStudio project file when creating a template

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#149]
Check how the usethis package does it. Worst case it's just a matter of creating a plain text file and naming it appropriately.

**Comment by cgrandin** [comment]
I did this some time ago:
https://github.com/pbs-assess/csasdown/blob/892b23b4000c872bb921a072128a64827cce5e33/R/draft.R#L45

I've tested the templates a lot since then and it works fine

**Comment by seananderson** [comment]
Ah, I see. I didn't notice that. But what I was thinking was that this file would get created when a new draft is created automatically, similarly to how usethis works when creating a new R package. I.e., this function would get called and we might need to have the user specify a folder. I'd say we follow however usethis does the interface for that.

**Comment by cgrandin** [comment]
Well it does, it is called in the draft() function. So when you call `csasdown::draft("resdoc")` for example in some directory, it copies everything you need to start and creates an RStudio project file there. Am I missing some other functionality?

**Comment by seananderson** [comment]
This was a problem with the unit tests, which I am now fixing.
