### ISSUE TITLE
gitignore and here files should start with . not _ in templates

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#150]
I noticed this in the tech report but it might affect others.

**Comment by cgrandin** [comment]
That could be a throwback to Windows users whom cannot create a file starting with a dot. They have to rename a file on the command line to get that functionality. But this is good.

**Comment by cgrandin** [comment]
This is why:
https://github.com/pbs-assess/csasdown/blob/892b23b4000c872bb921a072128a64827cce5e33/R/draft.R#L32

So we cannot change them

**Comment by seananderson** [comment]
This was a problem with the unit tests, which I am now fixing.
