### ISSUE TITLE
Case of automatically added title "Appendices"

### ISSUE THREAD

**Issue by Xandac** [pbs-assess/csasdowntex#153]
Hi CSASDOWN team,

When you knit the tech report project; if the document has appendices, the title “Appendices” appears on its own before the titles of the appendices one adds. Is there a way to make that word all caps “APPENDICES” because I want all of my headings to be all caps for first and second level headings to conform to the DFO report guide and also so they look consistent for my report.

Thanks,
Jeff

**Comment by cgrandin** [comment]
I'm not totally sure what the issue is. Could you provide an example doc or screenshots? If you have a git repository I could take a look at it.

**Comment by Xandac** [comment]
[Contents_From_TechReport.pdf](https://github.com/pbs-assess/csasdown/files/5318298/Contents_From_TechReport.pdf)

Attached is the table of contents from my report.  I have highlighted the word "Appendices" which is not all uppercase like the rest of the level titles. I would like it to be all uppercase; I just could not find the place in the csasdown files to make that change.

**Comment by Xandac** [comment]
I figured it out.  I had to edit the appendix.sty file under my TinyTeX installation (C:\Users\jacksonj\AppData\Roaming\TinyTeX\texmf-dist\tex\latex\appendix) by changing two lines:

\newcommand{\appendixtocname}{Appendices}
\newcommand{\appendixpagename}{Appendices}

to

\newcommand{\appendixtocname}{APPENDICES}
\newcommand{\appendixpagename}{APPENDICES}

[Revised_Contents_From_TechReport.pdf](https://github.com/pbs-assess/csasdown/files/5318997/Revised_Contents_From_TechReport.pdf)

**Comment by seananderson** [comment]
We should be able to gsub that in fix_envs https://github.com/pbs-assess/csasdown/blob/8e108463b4c51103228d3bb8f582a69b3ed7d5f3/R/utils.R#L448-L459

**Comment by seananderson** [comment]
Thanks for looking into it. I think [this](https://github.com/pbs-assess/csasdown/commit/1d11a1fb0480eb8489205c67e187f9cf68ffc229) should have fixed it.
