### ISSUE TITLE
Check pandoc version due to CSLReferences change (affects bibliography indentation)

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#157]
Newer pandoc versions (2.11.1.1 is what I have) create a CSLReferences environment that control biography hanging indentation. Older versions do not create that environment and so will not have correct indentation (at least in an SR) without manually adding something like this https://github.com/pbs-assess/csasdown/commit/481d8e2c5fcbb139d1cfda1e06c5a04f58e33e68

The version can be checked with

```r
rmarkdown::pandoc_version()
```

pandoc is bundled with RStudio unless installed separately and in the path.

**Comment by ricardd** [comment]
I am using pandoc 2.11.4 and the bibliography indentation is fine, but there are instances where the entries spill into the right margin:

<img width="391" alt="Untitled" src="https://user-images.githubusercontent.com/1110182/110488752-26a21080-80c5-11eb-81b7-9fdb6f456227.png">

@seananderson any suggestions?

Perhaps this is a side effect of the reference title having a URL associated with it, defined using \link{}{} in the title field of the bibtex entry (as per discussions in issue #160 )?

**Comment by ricardd** [comment]
Removing the \link{}{} fixes the margin spill:
<img width="394" alt="Untitled" src="https://user-images.githubusercontent.com/1110182/110497800-2ad22c00-80cd-11eb-908b-313ec4cac0f4.png">

This formatting requirement is proving deceptively difficult to address, and the path of least resistance seems to not have URLs in the bibliography.

**Comment by seananderson** [comment]
Purely a LaTeX thing. Try adding `\emergencystretch 3em` somewhere before the bibliography or if that doesn't work you could try `\sloppy`. I assume TeX tries harder not to hyphenate within the URL title.

https://tex.stackexchange.com/questions/9107/how-can-i-make-my-text-never-go-over-the-right-margin-by-always-hyphenating-or-b

**Comment by ricardd** [comment]
I added `\sloppy` to inst/csas-tex/sr-french.tex, rebuilt csadown and rendered the PDF again, and as the name implies it does look sloppy:

<img width="398" alt="Untitled" src="https://user-images.githubusercontent.com/1110182/110516047-71c91d00-80df-11eb-9b0b-309301855450.png">

I think that I will just remove the hyperlinks, as you did in your Pacific Cod SR 2021/002.

**Comment by seananderson** [comment]
Yeah, I wouldn't bother with linking all the report titles, but you could try this: https://tex.stackexchange.com/a/49791

**Comment by ricardd** [comment]
I kept `\sloppy` as above, added `\usepackage[hyphens]{url}` on line 20 of sr-french.sty, rebuilt csasdown and rendered the PDF again, and it is the same as above, there are no hyphens in the title, resulting in a pretty jagged reference.
