### ISSUE TITLE
PDF Metadata does not conform with Guide for the production of Fisheries and Oceans Canada Science Report Series

### ISSUE THREAD

**Issue by NatalieAsselin** [pbs-assess/csasdowntex#159]
This is in the guidelines for publications (https://waves-vagues.dfo-mpo.gc.ca/Library/333125.pdf)

Title and author have been entered as metadata in the Document Properties of the PDF.

Could this be added to the CSAS down package?

**Comment by seananderson** [comment]
For now, you should be able to do this after the fact in a PDF viewer/editor.

@ricardd mentioned this link https://www.karlrupp.net/2016/01/pdf-metadata-in-latex-documents/
which describes how this can be done with the hyperref package, so hopefully we can get this in the package.

**Comment by kellijohnson-NOAA** [comment]
Title and author are actually quite simple, and done in [sa4ss](https://github.com/nwfsc-assess/sa4ss/blob/6b109e44a325772617d00cb333ba55001b615ef9/inst/rmarkdown/templates/sa/resources/sadraft.tex#L109) (for another example).

**Comment by ricardd** [comment]
commit 9ebb9a1 adds PDF metadata to the rendered documents, closing this issue
