### ISSUE TITLE
Underline URLs in citations (SR)

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#160]
Got a bunch of new requests from CSAS re our SR this time. This one (and one more) I'm not sure how to fix. 

I tried using \href{url.address}{text} but that didn't work. I also tried wrapping this in \underline{}, and also putting \underine{} around the "text" part.

**Comment by grinnellm** [comment]
Basically, CSAS wants the title "A fishery decision-making..." part as a hyperlink, blue and underlined like in the main body of the document. This is some of what I've tried, so far without success: there's a blue hyperlink but it isn't underlined. I've also tried to use the `\link` command but that doesn't work: the title is omitted completely from the PDF. I tried putting the text part (i.e., "A fishery decision-making...") in an `\underline{}` but it doesn't underline it.

> @article{dfo2009,
>    author    = {DFO},
>    title     = {\href{https://www.dfo-mpo.gc.ca/reports-rapports/regs/sff-cpd/precaution-eng.htm}{A fishery decision-making framework incorporating the precautionary approach}},
>    year      = {2009},
>    volume    = {Last reportedly modified 23 March 2009, however figures have since changed}
> }

**Comment by seananderson** [comment]
`\link{}{}` should work in the main body, since we're using it here: https://github.com/pbs-assess/csasdown/commit/1f5010b8df6d0c45c8fcc6524ecfb414c5dc02fe

However, I'm not sure it will work within a .bib file when converted to a reference. I seem to remember having that issue too and just removing the hyperlink. It would be great to get something working, although as a stop gap or for testing, you could try putting `\link` directly into the final .tex file and rendering that.

**Comment by grinnellm** [comment]
Yes, `link{}{}` works fine in the main body but not in the .bib.

**Comment by grinnellm** [comment]
Is it odd that `\underline{}` doesn't work in the citations, when `\emph{}` works fine (for species names etc)?

**Comment by seananderson** [comment]
I’m thinking we might be able to fix this by regular expression within
fix_envs by manipulating the TeX, but that depends on how things come
through in the raw tex and if using the correct TeX actually works when
hand manipulated.

**Comment by grinnellm** [comment]
Just for info, I didn't have any success with the **soul** (command `\ul{}`) or **ulem** (`uline{}`) packages.

**Comment by ricardd** [comment]
@grinnellm just got the same request for my latest SR, and unfortunately the path of least resistance at this stage is to remove the hyperlinks from the citations, which is not really a satisfying long-term solution 

I tried this in the bibtex file, with no success:   title = {\href{https://blah.html}{\sffamily\uline{link text to be underlined}}}

so I guess that we are down to using a regular expression in fix_envs, as suggested by the contemporary prophet @seananderson

**Comment by grinnellm** [comment]
No, not ideal, especially if your reference is a webpage! It was for us.
Thanks for trying @ricardd, let me know if you have any success.
https://xkcd.com/208/

**Comment by ricardd** [comment]
I edited the file sr.tex, noticing how \underline was removed in the creation of the sr.tex file. In the bibtex file the title field appears as follows:

```
title = {\href{https://www.dfo-mpo.gc.ca/csas-sccs/Publications/SAR-AS/2016/2016_020-eng.html}{\underline{Guidelines for providing interim-year updates and science advice for multi-year assessments}}},
```

but in sr.tex, it appears as (not missing \underline):

```
\leavevmode\hypertarget{ref-dfo2016guidelines}{}%
DFO. 2016a. \href{https://www.dfo-mpo.gc.ca/csas-sccs/Publications/SAR-AS/2016/2016_020-eng.html}{{Guidelines for providing interim-year updates and science advice for multi-year assessments}}. DFO Can. Sci. Advis. Sec. Advis. Rep.
```

so I edited sr.tex to add \underline:

```
\leavevmode\hypertarget{ref-dfo2016guidelines}{}%
DFO. 2016a. \href{https://www.dfo-mpo.gc.ca/csas-sccs/Publications/SAR-AS/2016/2016_020-eng.html}{\underline{Guidelines for providing interim-year updates and science advice for multi-year assessments}}. DFO Can. Sci. Advis. Sec. Advis. Rep.
```

and ran tinytex::pdflatex("sr.tex") with the following result:

<img width="363" alt="Untitled" src="https://user-images.githubusercontent.com/1110182/109850408-dd674200-7c28-11eb-8162-37e674f31aa8.png">

@grinnellm any idea where to go from here? The underlining works but the title spills into the right margin.

**Comment by cgrandin** [comment]
Does this help @ricardd 
https://tex.stackexchange.com/questions/9550/why-does-underlined-text-not-get-wrapped-once-it-hits-the-end-of-a-line
But I see @grinnellm may have tried that above and failed

**Comment by ricardd** [comment]
what does seem to work is to use \sffamily\uline instead of \underline:

```
\leavevmode\hypertarget{ref-dfo2016guidelines}{}%
DFO. 2016a. \href{https://www.dfo-mpo.gc.ca/csas-sccs/Publications/SAR-AS/2016/2016_020-eng.html}{\sffamily\uline{Guidelines for providing interim-year updates and science advice for multi-year assessments}}. DFO Can. Sci. Advis. Sec. Advis. Rep.
```
yields this:
<img width="597" alt="Untitled" src="https://user-images.githubusercontent.com/1110182/109851662-51eeb080-7c2a-11eb-81cb-0a2720493d90.png">

**Comment by ricardd** [comment]
so back to @grinnellm's question above, why does \emph stay in the references but \underline or \sffamily\uline get removed in sr.tex?

**Comment by cgrandin** [comment]
One other thing.. From what I've read you need to be using the `url` tag in the bib file like this, not as an add-on in the title or somewhere:

```
@Article{Betancourt2018,
  author = {Betancourt, Michael A.},
  title = {A Conceptual Introduction to Hamiltonian Monte Carlo},
  journal = {Statistics Methodology, Cornell University},
  pages = {60pp.},
  year = {2018},
  url = {https://arxiv.org/abs/1701.02434}
}
```

**Comment by cgrandin** [comment]
> so back to @grinnellm's question above, why does \emph stay in the references but \underline or \sffamily\uline get removed in sr.tex?

Because latex was never meant to support underlining. At its core it supports italics but not underlining.

**Comment by ricardd** [comment]
@cgrandin when using url = {} in the bibtex, it does not appear in sr.tex :

```
\leavevmode\hypertarget{ref-dfo2016guidelines}{}%
DFO. 2016a. Guidelines for providing interim-year updates and science advice for multi-year assessments. DFO Can. Sci. Advis. Sec. Advis. Rep.
```

**Comment by grinnellm** [comment]
I think I had that problem with using the `url` field too, but I've had it work in knitr elsewhere. Is that an issue with the citation style file?

**Comment by ricardd** [comment]
indeed, I think that csas.csl dictates what fields are displayed and how

**Comment by ricardd** [comment]
while we are on the topic of the bibliography, what can I use for non-breaking white spaces since "~" doesn't seem to work?

```
pages = {iv + 127~p.}
```
yields this:
<img width="632" alt="Untitled" src="https://user-images.githubusercontent.com/1110182/109858430-312a5900-7c32-11eb-9f34-0aaf94f1e8e9.png">

**Comment by cgrandin** [comment]
I think it may be more fruitful to explore how to get the url tag to display in the bib instead of trying to embed the link in another tag. It sounds like (from my limited searching around) folks have had more success with linebreaks in links using the url tag for hyperlinks.

**Comment by ricardd** [comment]
so I am kind of stuck here, I can live with not having links in the bibliography at this stage, but that non-breaking space is really puzzling me, I wonder what causes the disappearance of all ~ in the bibliography in sr.tex, and yet "\&nbsp;" in the main Rmd files gets correctly translated to ~ in sr.tex

**Comment by grinnellm** [comment]
Did you try `\ `, where there's a space after the "\\"? Might not work, just a thought.

**Comment by seananderson** [comment]
@ricardd, If I build the built-in SR template (e.g., via the unit tests), and cite `[@edwards2013]`, which has:

```
@article{edwards2013,
  author       = {A. M. Edwards and R. Haigh and P. J. Starr},
  year         = {2014},
  title        = {Pacific {Ocean Perch} ({\emph{Sebastes alutus}}) stock
    assesment for the north and west coasts of {Haida Gwaii, British Columbia}},
  journal   = {DFO Can. Sci. Advis. Sec. Res. Doc.},
  volume    = {2013/092},
  pages     = {vi + 126~p}
}
```

in refs.bib, I get:

```
\leavevmode\hypertarget{ref-edwards2013}{}%
Edwards, A.M., Haigh, R., and Starr, P.J. 2014. [...] Doc. 2013/092. vi + 126~p.
```

in the .tex, which does seem to behave as a proper non-breaking space. If you can make a reproducible example, maybe put it in a new issue?

**Comment by ricardd** [comment]
@seananderson this is puzzling, I just did the same, added [@edwards2013] in the example SR, and in sr.tex it is this:

```
\leavevmode\hypertarget{ref-edwards2013}{}%
Edwards, A.M., Haigh, R., and Starr, P.J. 2014. [...] Doc. 2013/092. vi + 126 p.
```

**Comment by seananderson** [comment]
@ricardd What's your Pandoc version? 

```r
rmarkdown::pandoc_version()
#> [1] ‘2.11.2’
```

**Comment by ricardd** [comment]
I just updated everything now and it fixed the non-breaking space problem.

```
rmarkdown::pandoc_version()
[1] ‘2.11.4’
```
thanks @seananderson

**Comment by ricardd** [comment]
and magically, by upgrading RStudio and all R packages, using `\link{}{}` in the bibtex title field now works fine:
<img width="404" alt="Untitled" src="https://user-images.githubusercontent.com/1110182/109968294-e3acfb00-7cc8-11eb-9606-dfdce2100e3a.png">

**Comment by seananderson** [comment]
![image](https://user-images.githubusercontent.com/19349/109995830-806c9a00-7cc3-11eb-858e-81d2d14f3247.gif)
Hallelujah! I assume that was from a Pandoc update.

**Comment by ricardd** [comment]
but @cgrandin's point still stands, should the URL by in its own field in bibtex, or as a \link{}{} in the title?

**Comment by seananderson** [comment]
I don't think that's possible (using the URL field to link the title) without some serious post processing of the .tex or hacking of the .csl processing. E.g.
https://stackoverflow.com/questions/44457132/add-a-link-to-the-title-of-references
https://github.com/citation-style-language/documentation/issues/76

**Comment by ricardd** [comment]
so using `\link{}{}` will have to do

if @grinnellm can confirm that it works for him too we could close this issue

**Comment by grinnellm** [comment]
Updated RStudio/Pandoc and it works like a charm!
![image](https://user-images.githubusercontent.com/25674027/110010044-b1080000-7cd2-11eb-8394-fdb31ce61f09.png)
