### ISSUE TITLE
Keep individual references on the same page in "Sources of information" (SR)

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#161]
Second CSAS request that I'm not sure how to handle. 

That is, keep the lines together for each reference, so they don't continue on the next page.

**Comment by cgrandin** [comment]
I am wondering if you asked them why this list of changes since last year? You submitted an SR last year right, and they accepted it? Making these changes will ensure lack of standardization of the document from year to year, and standards are meant to ensure the opposite of that.

**Comment by grinnellm** [comment]
I haven't asked why, and what you say is logical, I completely agree. Unfortunately..

**Comment by seananderson** [comment]
The only thing I can think of is the widow/orphan penalty: https://tex.stackexchange.com/questions/4152/how-do-i-prevent-widow-orphan-lines

The other option would be to take the .tex at the very end and add a `\clearpage` where needed and rerender.

**Comment by cgrandin** [comment]
> I haven't asked why, and what you say is logical, I completely agree. Unfortunately..

I guess I'm hoping that if we keep asking them they may see our point eventually. Probably not though!

**Comment by grinnellm** [comment]
It might be that we are getting very close to what someone has in mind, and they feel like they have to say something, so these minor things get to the surface?

**Comment by cgrandin** [comment]
That's possible, hopefully that's what it is. We all spend so much time on these requests

**Comment by grinnellm** [comment]
Couldn't make this working setting the `widowpenalty` and `clubpenalty` to 10000, but seems to work fine if I use the "nowidow" package. Thanks Sean. Fixed in https://github.com/pbs-assess/csasdown/commit/54ac5de6cdd65c7c1852059d699f100e9b8ba3d3.
