### ISSUE TITLE
Feature Request: Generic Report

### ISSUE THREAD

**Issue by SOLV-Code** [pbs-assess/csasdowntex#162]
*I realize this probably out of scope for csasdown. In that case, maybe you can point me in the direction of a local fix? For example, could I just turn off the regeneration of AquatTechInsCover.pdf` and tech-report.sty somewhere?*

## Issue

I have done a few csasdown tech reports now, and have several in the works. So it really has become part of my default workflow.
Now I'm starting a report for COSEWIC  and would like to use the same setup. 

## Request

Ideally, there would be an option to set up the template by running ```csasdown::draft("genericreport")```. This would generate a report just like the DFO tech report, except for the DFO-specific inside cover and colophon pages.

### Main cover page

With the recent change to the custom cover page (using *tech-report-cover.pdf*) I can easily adapt the main cover.

###  Other Front Matter

The source file ```csas-style/pages/AquatTechInsCover.pdf``` gets regenerated every time you knit the doc, so can't simply replace with a custom pdf.

Similarly, the style file at ```csas-style/tech-report.sty``` gets regenerated every time, so can't just comment out line 358 and 
lines 364-398 (which insert the front matter)

Removing those pages afterwards using  some pdf editor seems to mess up page numbering and cross-reference (with the freeware I've tried).

**Comment by seananderson** [comment]
Have you tried `copy_sty: false`? As in:

```
output:
 csasdown::techreport_pdf:
   copy_sty: false
```

Do this after building the document at least once. That should freeze the .sty file so you can hand edit it as needed. You'll probably want to version control it in case that option ever gets accidentally toggled again.

As for the cover pages, it looks to me like they don't currently overwrite the files if they're already there:
https://github.com/pbs-assess/csasdown/blob/54ac5de6cdd65c7c1852059d699f100e9b8ba3d3/R/utils.R#L196-L197

If that isn't the case, maybe we can copy those based on the `copy_sty` state.

**Comment by SOLV-Code** [comment]
Thank you for the quick reply! 

I will do ```copy_sty: false``` and try the pdf.

**Comment by SOLV-Code** [comment]
works like a charm! Thank you again.
