### ISSUE TITLE
French .csl files are not picking up the correct locale

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#163]
**Describe the bug**
French bibliographies are using English words (e.g., 'and' instead of 'et').

**To Reproduce**
Build any of the 3 report types with `french: true` and look at the bibliography for entries with multiple authors.

**Expected behavior**
The references in French documents should have 'et' instead of 'and'.

**Observed behavior**
The references in French documents have English connector terms.

**Desktop (please complete the following information):**
Current csasdown package version. Mac and Windows. Whatever version of Pandoc is in the latest RStudio Preview for me.

**Additional context**
@ricardd and I both note that this used to be working(!), so this may be a result of an update to Pandoc.

It should work out based on the `default-locale="fr-CA"` at the top of each French .csl file. 
E.g. https://github.com/pbs-assess/csasdown/blob/master/inst/rmarkdown/templates/techreport/skeleton/csl/csas-french.csl#L2

Docs:
https://docs.citationstyles.org/en/stable/specification.html#terms  https://docs.citationstyles.org/en/stable/specification.html#locale

I wonder if it's written incorrectly in the .csl according to current formatting requirements or if a different `fr-` locale would work.

**Comment by cgrandin** [comment]
I confirm this bug with pandoc version 2.7.3

```r
rmarkdown::pandoc_version()
>'2.7.3'
```

**Comment by cgrandin** [comment]
This is because when `french: true` is changed in the YAML, `csl: csl/csas.csl` remains when it should be changed to
`csl: csl/csas-french.csl`
I'll see if it can be set programatically so the user doesn't have to remember to change two things

**Comment by cgrandin** [comment]
This fix only works for new projects. To fix old projects, you must modify your `index.Rmd` file with changes found in 407522dc0f3e0a9164cfe5f2f350b16c1b1c47e9

**Comment by ricardd** [comment]
thanks @cgrandin and @seananderson
