### ISSUE TITLE
More requested SR formatting changes

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#164]
Yet more CSAS-requested formatting tweaks to the SR template:

- [x] Increase space between Headings level 2 through 4 and the text (or heading) that follows. Space should be the same between headings and text as it is between paragraph text (equivalent to 6 pt. before and after in Word).  Your text (paragraphs) are spaced correctly – so you can use that as a guide
- [x] Little more space between table caption and beginning of tables (should be equivalent to 6 pt in Word –same distance as text between paragraphs)
- [x] Decrease white space a little in footer (“drop” footer a bit by lowering the border and page # - 1 page footer is perfect, just the 2nd page onward footer needs adjusting) 
- [x] Increase spacing between segments (address/contact onfo/iSSN in the “this document is available from” – 6 pt font between them as if they were separate paragraphs (see attached template –I think Matt already fixed this in the current style file)

**Comment by ricardd** [comment]
@seananderson I can't see any obvious commits that may have changed this, but the headers have now disappeared from all but the title page when I render a Science Response. 

I can confirm that this is also the case when knitting a fresh SR created using the "draft" function from a freshly built csasdown package.

It looks like the header is pushed outside of the page and the footer is too large.

**Comment by seananderson** [comment]
Should be all done assuming @grinnellm did the last one, which I think he did after looking at the commits.

Note that you must be on the TeX Live 2020 for all the spacing to work. It seems that the section spacing behaviour changed.
