### ISSUE TITLE
Header/footer have wrong spacing in SR with latest geometry TeX package

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#165]
From @ricardd:

I can't see any obvious commits that may have changed this, but the headers have now disappeared from all but the title page when I render a Science Response. 

I can confirm that this is also the case when knitting a fresh SR created using the "draft" function from a freshly built csasdown package.

It looks like the header is pushed outside of the page and the footer is too large.

_Originally posted by @ricardd in https://github.com/pbs-assess/csasdown/issues/164#issuecomment-759431085_

**Comment by cgrandin** [comment]
I thought it might be this one:

https://github.com/pbs-assess/csasdown/commit/1c191bc274951afe66f8aa2d666c40fd7da040e1

I just opened the sr.sty file and hit "Blame" and this one was a month ago. Possibly the "pc" should be "pt"

**Comment by seananderson** [comment]
I can confirm. I think the geometry TeX package must have been updated. I've seen this before when we had to switch from 1 inch margins to get it to look right. I assume this was a bug in the TeX package that's been fixed. I'll push a fix in a sec and require the latest tinytex. If the margins now look off to other people, they will have to update the tinytex TeX installation.

```r
install.packages("tinytex")
tinytex::reinstall_tinytex()
# or possibly just:
# tinytex::tlmgr_update()
```

**Comment by seananderson** [comment]
@cgrandin, no it's not that. I tried reverting back to some very old commits and comfirmed the same behaviour. I think it's a reversal of this issue:
https://github.com/pbs-assess/csasdown/issues/55
https://github.com/pbs-assess/csasdown/commit/9d63cb08338a4613145f762931303fa9c715b32d

**Comment by ricardd** [comment]
@seananderson my hero! Thanks for the fix.
