### ISSUE TITLE
Table formatting question (Not a bug)

### ISSUE THREAD

**Issue by SOLV-Code** [pbs-assess/csasdowntex#168]
I'm trying to do add some additional formatting to a `csas_table`, using examples from [this kableExtra vignette](https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf).

The example on the bottom of their p. 11 illustrates conditional formatting of cells, and I'm trying to add heatmap coloring to a table, so that looks like an exact fit.

However, the following

```
test.tab1 <-  senstest.disc.table.smsy[1:12,]

test.tab1.colors <- test.tab1 %>% 
                    mutate_all(function(x){gsub("L", "red", x)}) %>%
                    mutate_all(function(x){gsub("M", "yellow", x)}) %>%                        
                    mutate_all(function(x){gsub("S", "white", x)}) 

test.tab1 %>% select(-Stock) %>%
   rename(Stock = StkNmS,SR = NumSR, pSpn = PercSpnLabel, T =  BCT, TFd = BCTFd ) %>%
    mutate_all(function(x){gsub("NA", "-", x)}) %>% 
   mutate_all(function(x){gsub("&", "\\\\&", x)}) %>% 
   mutate_all(function(x){gsub("%", "\\\\%", x)}) %>%
   mutate_all(function(x){gsub("\\\\n","\n", x)}) %>%
   csas_table(format = "latex", escape = FALSE, font_size = 9, align = "r",
                  caption = "Overview of Sensitivity Tests for 12 largest Nass and Skeena Sockeye Stocks") %>% 
   kableExtra::row_spec(1:11, hline_after = TRUE) %>%
      kableExtra::column_spec(5, background = test.tab1.colors[,5] )
```
crashes with 

```
! Undefined control sequence.
l.2663 Fulton & 53 & 1993 & 38 & \cellcolor
                                           {38}{M} & S & L & L & M & N & S &...
```

The help file for  `column_spec()` states for the *background* argument to "please pay attention to the differences in color codes between HTML and LaTeX."  

Based on [this summary](http://latexcolor.com/) I've tried 2 versions of specifying the colors ("red",#FF033E"), but both give the same error. I haven't figured out where in the csasdown template the 3rd option would go: `\definecolor{americanrose}{rgb}{1.0, 0.01, 0.24}`

Any ideas?

## Side note

Other things from the vignette that I have tried worked basically right away.  For example,  grouping rows together with `pack_rows()` (p. 18 in the vignette) was no problem, so I don't think it's an issue of `csas_table` vs. direct calls to `kableExtra`.

**Comment by cgrandin** [comment]
It's probably because of the `format = "latex"` argument in `csas_table()`. Have you tried leaving that out?
The default is `format = "pandoc"`.

You may have to do `format = "html"` to get the colors to work, I'm not sure.

**Comment by SOLV-Code** [comment]
Thank you for the quick response.

the report knits when I change it to `format = "html"` or `format = "pandoc"`, but there are no colors in the table.
I will try to switch from the `csas_table()` call to the sequence from the vignette:

```
kbl(booktabs = T, linesep = "") %>%
kable_paper(full_width = F) %>%
```

and if that works, then I'll try to match the settings to the `csas_table()` defaults.

Will post an update here, one way or the other.

**Comment by cgrandin** [comment]
I think you actually have to knit to an HTML doc for this to work. I don’t believe table cell coloring is supported in other formats. Someone correct me if I’m wrong as this would be nice to have work.

**Comment by SOLV-Code** [comment]
The vignette is in pdf and has these tables, so I thought it should work. Their sample table on the bottom of pg 11 even has specific cells with a mouse-over hyperlink (mpg column). These things would be very nice to be able to play with.

**Comment by cgrandin** [comment]
The way I have accomplished this is to just make it a figure by using `ggplot2::geom_tile() + scale_fill_gradientn(colors = vector_of_colors)`

**Comment by seananderson** [comment]
If the question is just about where to put `\definecolor{americanrose}{rgb}{1.0, 0.01, 0.24}` then put it after `header-includes`: https://github.com/pbs-assess/csasdown/blob/52ecedada7c42407fa6ef138b7772b3148a8c57a/inst/rmarkdown/templates/techreport/skeleton/skeleton.Rmd#L40-L41

Assuming the appropriate LaTeX packages are already loaded. If not, load them too. See https://github.com/pbs-assess/csasdown/blob/master/inst/csas-style/tech-report.sty

**Comment by SOLV-Code** [comment]
@seananderson : I will try putting `\definecolor` there
@cgrandin : yes, plan B is to make a figure, but I haven't quite given up on the kabelExtra option yet...

**Comment by SOLV-Code** [comment]
Your comment re LaTeX Packages and pointing to \usepackage in the header-includes part of index.Rmd did the trick! Thank you.
The problem was not loading the required packages. Actually my problem was not reading the vignette from the beginning, where it lists the required packages :-(

Full example follows.

**Comment by SOLV-Code** [comment]
## Result

![Screen Shot 02-19-21 at 12 16 PM](https://user-images.githubusercontent.com/30556192/108557094-e06b4580-72ac-11eb-81cd-7db66429b9e0.PNG)

**Comment by SOLV-Code** [comment]
## index.Rmd

```
header-includes:
 - \usepackage{float}
 - \linenumbers
 # rest is from page 4 of https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf
 - \usepackage{booktabs} 
 - \usepackage{longtable}
 - \usepackage{array}
 - \usepackage{multirow}
 - \usepackage{wrapfig}
 - \usepackage{float}
 - \usepackage{colortbl}
 - \usepackage{pdflscape}
 - \usepackage{tabu}
 - \usepackage{threeparttable}
 - \usepackage{threeparttablex}
 - \usepackage[normalem]{ulem}
 - \usepackage{makecell}
 - \usepackage{xcolor}
 ```

**Comment by SOLV-Code** [comment]
## Table

```
test.tab1 <-  senstest.disc.table.smsy[1:12,]

test.tab1.colors <- test.tab1 %>% 
                    mutate_all(function(x){gsub("L", "red", x)}) %>%
                    mutate_all(function(x){gsub("M", "orange", x)}) %>%                        
                    mutate_all(function(x){gsub("S", "white", x)}) %>%                        
                    mutate_all(function(x){gsub("N", "white", x)}) 

test.tab1 %>% select(-Stock) %>%
   rename(Stock = StkNmS,SR = NumSR, pSpn = PercSpnLabel, T =  BCT, TFd = BCTFd ) %>%
    mutate_all(function(x){gsub("NA", "-", x)}) %>% 
   mutate_all(function(x){gsub("&", "\\\\&", x)}) %>% 
   mutate_all(function(x){gsub("%", "\\\\%", x)}) %>%
   mutate_all(function(x){gsub("\\\\n","\n", x)}) %>%
#   mutate_all(function(x){gsub("\\\\#","\#", x)}) %>%
   csas_table(format = "latex", 
              escape = FALSE, font_size = 9, align = "c",
                  caption = "Overview of Smsy Sensitivity Tests for 12 largest Nass and Skeena Sockeye Stocks") %>% 
   kableExtra::row_spec(1:11, hline_after = TRUE) %>%
    kableExtra::column_spec(5, background =  unlist(test.tab1.colors[,6]) ) %>% # need col +1 b/c of select(-Stock) above
    kableExtra::column_spec(6, background =  unlist(test.tab1.colors[,7]) ) %>%
       kableExtra::column_spec(7, background =  unlist(test.tab1.colors[,8]) ) %>%
       kableExtra::column_spec(8, background =  unlist(test.tab1.colors[,9]) ) %>%
       kableExtra::column_spec(9, background =  unlist(test.tab1.colors[,10]) ) %>%
       kableExtra::column_spec(10, background =  unlist(test.tab1.colors[,11]) ) %>%
       kableExtra::column_spec(11, background =  unlist(test.tab1.colors[,12]) ) %>%
       kableExtra::column_spec(12, background =  unlist(test.tab1.colors[,13]) ) %>%
       kableExtra::column_spec(13, background =  unlist(test.tab1.colors[,14]) ) %>%
       kableExtra::column_spec(14, background =  unlist(test.tab1.colors[,15]) ) %>%
       kableExtra::column_spec(15, background =  unlist(test.tab1.colors[,16]) ) %>%
       kableExtra::column_spec(16, background =  unlist(test.tab1.colors[,17]) )
```

**Comment by seananderson** [comment]
Glad that works. Here's our ggplot 'tigure' solution:

![image](https://user-images.githubusercontent.com/19349/108565919-5e821900-72ba-11eb-9ae4-af3cbe06497a.png)

https://github.com/pbs-assess/gfdlm/blob/0fa8db2177b9bcc6841e8babcdfcd5c223082b57/R/figures-tigure.R#L147-L158

**Comment by cgrandin** [comment]
Here's one we do for Hake which also incorporates transparency as a factor: (https://github.com/pacific-hake/hake-assessment/blob/41e286a85619590c0335804735709526dc12d6d8/R/figures-size-at-age.R#L75)

![image](https://user-images.githubusercontent.com/4551051/108566657-a0f82580-72bb-11eb-955f-1462c8a4d836.png)

**Comment by SOLV-Code** [comment]
These examples are impressive. I think you have a lot more formatting control with the "tigure" approach, and I will have to give the ggplot approach a try some time. For now the kableExtra approach does the trick, so I'll stick with it. 

Does the link to this issue stay the same, even after you close it? I know I'll be coming back here...

Thank you both for your help sorting this out.

**Comment by seananderson** [comment]
Link remains the same. I'll close this now.
