### ISSUE TITLE
Csasdown citation

### ISSUE THREAD

**Issue by SOLV-Code** [pbs-assess/csasdowntex#177]
I couldn't find a citation for the csasdown package in the readme, so I'm using the following bibtex entry, based on the names listed in the [csasdown licence](https://github.com/pbs-assess/csasdown/blob/master/LICENSE).

```
@Manual{csasdownpkg,
    title = {csasdown: An R package for creating CSAS reports in PDF or Word format with R Markdown and bookdown},
    author = {S. Anderson and C. Grandin and A. Edwards and
M. Grinnell and D. Ricard Ismay and  N. Solomon and B. Marwick},
    year = {2021},
    url = {https://github.com/pbs-assess/csasdown}
  }
```

Please let me know whether that works, or should be changed to something else.

**Comment by seananderson** [comment]
citation("csasdown") should get you close. There are some extra authors and the contributors (ctb) don't need to be included. I guess the license file is out of date. See the DESCRIPTION file, which is what citation() draws from.

**Comment by SOLV-Code** [comment]
good point. will do. Thanks.
