### ISSUE TITLE
csas_down(format = "latex") fails

### ISSUE THREAD

**Issue by ErikaDAnderson** [pbs-assess/csasdowntex#180]
Using csas_table function with format = "latex fails with csasdown 0.0.9.9000 and KableExtra 1.3.4. I am using R version 4.0.4 on Windows 10 x64. I made a [reproducible example](https://github.com/ErikaDAnderson/csasdownKableExtraErrorExample) using the template for csasdown tech report. The template report knits if all three of the csas_table(format = "latex") tables are commented out, but fails if one of the three latex tables is called. The error says: ![Error in 1:header_rows_end: NA/NaN argument...](https://github.com/ErikaDAnderson/csasdownKableExtraErrorExample/blob/master/data/Error.PNG). Thank you.

**Comment by seananderson** [comment]
Thanks for the example. It appears to be due to the `repeat_header = TRUE` option, which is the default. If you need the LaTeX output format over the default pandoc, then you could set `repeat_header = FALSE`. There must be a better solution, but that should hopefully do for now.

**Comment by ErikaDAnderson** [comment]
Hello @seananderson. Thank for the quick reply. I added repeat_header = FALSE to my example and the document knits as you suggested. However, my tables span multiple pages so headers need to be repeated. For example, see the long wide table on page 10 of the [example](https://github.com/ErikaDAnderson/csasdownKableExtraErrorExample). Does csas_table have another option to allow the header to repeat without breaking the knit? I have used csas_table before with tables repeating, so I had assumed (perhaps incorrectly), this was a package update issue. And if I remember correctly, the format = "latex" is necessary for landscape tables. Any suggestions would be welcome. I love this R package :simple_smile:

**Comment by seananderson** [comment]
Have you tried the newest landscape table instructions? @maburton made some updates so the the header and footer is oriented correctly and I think created a new environment for it `landscapepage`.  https://github.com/pbs-assess/csasdown/wiki/How-to-make-landscape-tables

**Comment by ErikaDAnderson** [comment]
I tried to follow the [wiki describing landscape table](https://github.com/pbs-assess/csasdown/wiki/How-to-make-landscape-tables) using my example repo and succeeded in making this mess using 
\begin{landscapepage} 
codechunk
\end{landscapepage} 
![MessyLandscape](https://user-images.githubusercontent.com/39602850/116327274-4b3c6f80-a77b-11eb-9a54-5a33c8a15339.PNG) 
which looks similar to a [previous issue](https://github.com/pbs-assess/csasdown/issues/31). After reading through that, I used a combination of splitting tables into one page chunks to allow the header names to repeat without using repeat_header = TRUE, and kableExtra options pipped after the csasdown::csas_table to make tables using this code or something similar:
csasdown::csas_table(
  ocean_wider2,
  format = "latex",
  font_size = 10,
  repeat_header = FALSE, # this is needed so it knits 
  col_names = c("Date", "Station",
                "Latitude", "Longitude", 
                "Start\nTime\n(PDT)", "Bottom\nDepth\n(m)","Gear\nDepth\n(m)",
                "Start\nTime\n(PDT)", "Bottom\nDepth\n(m)","Gear\nDepth\n(m)")) %>%
  kableExtra::add_header_above(c("", "", "", "", "CTD", "","", "BONGO", "", ""), align = "l") %>%
  kableExtra::landscape() 

I did this as a quick fix with all my landscape tables as we are close to completing the report. The remaining issue is the page numbers on the landscape and portrait positions on every landscape table
![DoublePageNumbers](https://user-images.githubusercontent.com/39602850/116329449-3adac380-a780-11eb-8090-6299efa2a53d.PNG)
Do you have any suggestions to overcome the page numbers in both spots? Perhaps I could tweak the tech-report.sty to remove one of the numbers? Any suggestions of where I should look for that? It looks like you switched from pdflscape to lscape before to fix this, and I noticed that my tech-report.sty has pdflscape.


Thank you for you time.

**Comment by cgrandin** [comment]
Hi Erika, if you send me the exact function call used in **codechunk** between the landscapetable tags above and the table data I will take a look. I have a feeling you "know too much" about what we had to go through before to get this working, as it should be just as laid out in the wiki.

**Comment by ErikaDAnderson** [comment]
I used the [example repo](https://github.com/ErikaDAnderson/csasdownKableExtraErrorExample) to test out the wiki instructions.

\begin{landscapepage}
```{r widelong, results = "asis"}
yrs <- 1:45
ages <- 1:15
widelong <- matrix(round(rnorm(length(yrs) * length(ages), 20), 4),
  nr = length(yrs),
  nc = length(ages),
  dimnames = list(year = yrs, age = ages))
widelong_df <- data.frame(cbind(yrs, widelong))

csasdown::csas_table(widelong_df,
  col.names = c("Year", as.character(ages)),
  caption = "A long and wide table",
  #format = "latex",
  font_size = 8
  # ,
  # repeat_header = FALSE
  )
```
\end{landscapepage}

**Comment by seananderson** [comment]
I just uncommented the `format = "latex"` in your example and this seems to work. In your code the table was coming out as Markdown but it was wrapped in a LaTeX environment. Now I forget why it wasn't working above with `format = "latex"`.

<img src="https://user-images.githubusercontent.com/19349/116438680-87b3ae00-a803-11eb-9775-547027ee835e.png" width="200">

**Comment by seananderson** [comment]
I have updated the wiki to note the need for `format = "latex"` in this case. 

https://github.com/pbs-assess/csasdown/wiki/How-to-make-landscape-tables

**Comment by cgrandin** [comment]
Thanks @seananderson, that one slipped past me. I checked and the examples all have `format = "latex"`.

I was thinking about making it the default in the function because then doing things like adding extra header rows like @ErikaDAnderson has done  would just work with the default. Can you think of a reason to not have it as the default?

**Comment by seananderson** [comment]
One major reason is it will break all .docx tables. I thought the Pandoc option helped with accessibility tagging, but maybe I'm remembering incorrectly.

**Comment by ErikaDAnderson** [comment]
I tried it on one landscape table in my data report. The report knits, has a single page number, and looks good. I originally commented out the format = "latex" since that line was breaking the knit, before I knew about landscapepage. Please feel free to close this issue from my perspective. Thanks again for the expertise.

**Comment by cgrandin** [comment]
Right, of course! docx compatibility. Ok, we leave it as-is and I'll close this.
