### ISSUE TITLE
Table Bug: csas_table, kableExtra, or PEBCAC?

### ISSUE THREAD

**Issue by SOLV-Code** [pbs-assess/csasdowntex#190]
**Describe the bug**

I'm generating multiple tables as subsets of a larger dataframe. The first table formats fine. Subsequent tables, with the same code, include row numbers as an extra column, which throws off the formatting. Looking at the dataframe subset, the inputs into all the csas_table() calls seem to be the same...

**To Reproduce**

 Reproducible tech report example on [Google Drive](https://drive.google.com/drive/folders/1d6GYgc6ftX6jqorKj1PKjzMasJ6kBoFz?usp=sharing)

The 2 tables are at the beginning of the *Results* section

**Expected behavior**

All tables should have the same columns and formatting

**Observed behavior**

Only first table is properly formatted.

**Screenshots**

First table

![Screen Shot 06-13-21 at 12 44 PM](https://user-images.githubusercontent.com/30556192/121820010-3e99ab00-cc45-11eb-9c90-f7b202f68550.PNG)
Other tables

![Screen Shot 06-13-21 at 12 45 PM](https://user-images.githubusercontent.com/30556192/121820016-41949b80-cc45-11eb-89ca-403b27036aa5.PNG)

**Desktop (please complete the following information):**
 - Operating system: Windowa
 - R version: "R version 4.1.0 (2021-05-18)"
 - csasdown version: ‘0.0.10.9000’

**Comment by SOLV-Code** [comment]
**Update**

Changing this 
```
andyW.idx <- grepl("Andreafsky West",loweryk.aerial.issues$Project)
loweryk.aerial.issues[andyW.idx ,]   %>%
   mutate_all(function(x){gsub("&", "\\\\&", x)}) %>% 
   mutate_all(function(x){gsub("%", "\\\\%", x)}) %>%
   csas_table(format = "latex", escape = FALSE, font_size = 11,
                  caption = "Andreafksy West Fork Aerial - Potential Data Issues",
              col_names = c("Project","Years Affected","Potential Issue")) %>%
   kableExtra::column_spec(1, width = "5em") %>%
   kableExtra::column_spec(2, width = "10em") %>%  
   kableExtra::column_spec(3, width = "25em") %>%
   kableExtra::row_spec(1:(sum(andyW.idx) -1), hline_after = TRUE) 
```
to 
```
andyW.idx <- grepl("Andreafsky West",loweryk.aerial.issues$Project)

test.df <- loweryk.aerial.issues[andyW.idx ,]  

test.df %>%
   mutate_all(function(x){gsub("&", "\\\\&", x)}) %>% 
   mutate_all(function(x){gsub("%", "\\\\%", x)}) %>%
   csas_table(format = "latex", escape = FALSE, font_size = 11,
                  caption = "Andreafksy West Fork Aerial - Potential Data Issues",
              col_names = c("Project","Years Affected","Potential Issue")) %>%
   kableExtra::column_spec(1, width = "5em") %>%
   kableExtra::column_spec(2, width = "10em") %>%  
   kableExtra::column_spec(3, width = "25em") %>%
   kableExtra::row_spec(1:(sum(andyW.idx) -1), hline_after = TRUE) 
```

doesn't fix it.

**Comment by cgrandin** [comment]
What’s the class(test.df) return for each of them?

If they are the same the code should work the same, try test.df <- as_tibble(test.df) as tibbles don’t have rownames

**Comment by SOLV-Code** [comment]
Thank you! PEBCAC it was :-)

```
loweryk.aerial.issues[andyW.idx ,]  %>% as_tibble() %>%
   mutate_all(function(x){gsub("&", "\\\\&", x)}) %>% 
```

does the trick.
