### ISSUE TITLE
More CSAS requested changes to SR template

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#192]
- [ ]     The text at the top of all pages (2 onwards) is too far from the header – not a deal breaker if it’s too onerous to fix. I’ve attached a published Word doc though that shows how it should mostly look.

- [x]   There should be a space between “français” and the colon (colophon page) – this is the last page of the document (report available from…)

- [x]   The comma following the second “MPO” in the French correct citation should be replaced with a period (not a comma) - this is the last page of the document (report available from…)

 

### French

- [ ]        The text on the following pages is too close to the page header:   3,4,6,7,8,11,12,13,14  - not a deal breaker if it’s too onerous to fix

- [ ]        Text on page 4 is too close to the page footer

- [x]        “BC” in the mailing address from the “Le présent rapport est disponible auprès du :” section needs to be translated to “C.-B.”

- [x]        There needs to be a space before colons (see “courriel:” and “Addresse internet:” on the colophon page) o   Exception: “Also available in English:” (no space needed)

- [x]         Fix spelling of “Addresse internet” o   Should be “Adresse Internet”

- [x]         The comma following the second “MPO” in the French correct citation should be replaced with a period

**Comment by seananderson** [comment]
Re: "BC" to "C.-B." in the mailing address, do they seriously not want the international mailing abbreviation?
https://www150.statcan.gc.ca/n1/pub/92-195-x/2011001/geo/prov/tbl/tbl8-eng.htm

**Comment by seananderson** [comment]
I've fixed everything other than the header spacing. For that:

I can't get this to work:

```
header_spacing: 25pt
```

```
\newcommand{\rdHeadSep}{$header_spacing$}
```

```
\setlength{\headsep}{\rdHeadSep{}}
```

So, for now, you could 

```
copy_sty: false
```

and hand edit the line in `csas-style/sr.sty` or `csas-style/sr-french.sty`:

```
\setlength{\headsep}{25pt}
```

to an appropriate value. 

The problem is that sometimes the short title is 2 lines and sometimes it is 1 line and that affects the spacing.

**Comment by grinnellm** [comment]
We need one of these for CSAS formatting:
"If you are using R and you think you’re in hell, this is a map for you."
http://www.burns-stat.com/pages/Tutor/R_inferno.pdf?dummyquery
