### ISSUE TITLE
column_spec not working with csas_table

### ISSUE THREAD

**Issue by tcoyle456** [pbs-assess/csasdowntex#196]
I am trying to use column_spec to adjust a table to fit on one page in a pdf document. However, csas_table ignores the command completely. There are no errors or messages, just no results. I can only get column_spec to produce results on an HTML document when I use kable instead of csas_table, but it still does not work in the PDF. My table continues to run off the page as the text will not wrap. Here is my code:

equip <- c("Sentinel V100 ADCP", "Hydrolab DS5X CTD")
loc <- c("Lemmens Inlet", "Lemmens Inlet")
lat <- c("49.2080", "49.2110")
long <- c("-125.8595", "-125.8571")
deploy <- c("Nov 2018", "Jun 2019")
param <- c("Current Velocity", "Depth, Temperature, pH, Chlorophyll,Turbidity, Dissolved Oxygen, Conductivity")

ocean_table <- as.data.frame(cbind(equip, loc, lat, long, deploy, param))

csasdown::csas_table(ocean_table, caption = "Location, coordinates, date of deployement and parameters measured for 
                     each piece of oceanographic equipment launched in 2018.") %>%
  column_spec(6, width = "3cm", background = "yellow")

I have tried many variations in the syntax, including:

csasdown::csas_table(ocean_table, caption = "Location, coordinates, date of deployement and parameters measured for 
                     each piece of oceanographic equipment launched in 2018.") %>%
  kableExtra::column_spec(6, width = "3cm", background = "yellow")

The code is ignored every time. 

Any help would be much appreciated!

**Comment by cgrandin** [comment]
Try using "3em" instead of "3cm"
Also, latex doesn't allow the yellow background color change, so that will work for HTML but not LaTeX (PDF)

**Comment by tcoyle456** [comment]
Unfortunately this still doesn't work :( The PDF output is still just the same table with long text spread all over the next row. I tried adjusting different columns and nothing changes regardless of what values I enter for width. 

The yellow background was actually just to see if the command was working - so not important. 

![Untitled](https://user-images.githubusercontent.com/93617980/139953642-e66f8a11-c678-419b-aa82-c010fb38d3d2.png)

**Comment by seananderson** [comment]
Have you tried specifying `format = 'latex'`? That's the warning I get when I run the table code in the console:

```
Warning message:
In kableExtra::column_spec(., 6, width = "3cm", background = "yellow") :
  Please specify format in kable. kableExtra can customize either HTML or LaTeX outputs. See https://haozhu233.github.io/kableExtra/ for details.
```

The default for csas_table and kable may be different (`format = "pandoc"` for csas_table and empty for knitr::kable).

```r
equip <- c("Sentinel V100 ADCP", "Hydrolab DS5X CTD")
loc <- c("Lemmens Inlet", "Lemmens Inlet")
lat <- c("49.2080", "49.2110")
long <- c("-125.8595", "-125.8571")
deploy <- c("Nov 2018", "Jun 2019")
param <- c("Current Velocity", "Depth, Temperature, pH, Chlorophyll,Turbidity, Dissolved Oxygen, Conductivity")

ocean_table <- as.data.frame(cbind(equip, loc, lat, long, deploy, param))

csasdown::csas_table(ocean_table, caption = "Location, coordinates, date of deployement and parameters measured for
each piece of oceanographic equipment launched in 2018.", format = "latex") %>%
kableExtra::column_spec(6, width = "3cm")
```

![image](https://user-images.githubusercontent.com/19349/139954561-50d2a18d-f6f7-4577-9bc7-c73b2d91029e.png)

**Comment by tcoyle456** [comment]
Yes that worked! Thank you!

I actually did try specifying the format within knitr::kable and kable(), which did not work, but I guess I didn't try adding it to csas_table. 

Thanks again! I would have wasted way too many hours trying to sort that out.
