### ISSUE TITLE
Bad spacing between header and body/text when header is two lines (SR)

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#197]
**Describe the bug**
CSAS requested that we shrink the vertical space between the header and the body/text of the SR. I changed
`\setlength{\headsep}{25pt}`
to
`\setlength{\headsep}{15pt}` here:
https://github.com/pbs-assess/csasdown/blob/a750391b1390b09719182a0a7742afe29bb9cda0/inst/csas-style/sr.sty#L64
This gives the right spacing when the `title_short` is one line (see below), but it's not enough when the `title_short` is two lines (also see below). (The second is a silly example, but our French short title is two lines.)

**To Reproduce**
[header.zip](https://github.com/pbs-assess/csasdown/files/7470769/header.zip)
Unzip the attached file. To see the issue, change `\setlength{\headsep}{25pt}` to `\setlength{\headsep}{15pt}` in "sr.sty" (csasdown) and then knit the PDF (`bookdown::render_book("index.Rmd")`).

**Expected behavior**
A fixed space between the header and the body, regardless of whether the header has one or two lines.

**Observed behavior**
Two-line headers cause the header to be too close to the body/text.

**Screenshots**
Proper spacing with a one-line header:
![image](https://user-images.githubusercontent.com/25674027/140191298-85304004-e5f3-46cc-b434-c7d052032a19.png)

Improper spacing with a two-line header:
![image](https://user-images.githubusercontent.com/25674027/140191771-016ed88f-b7be-411b-a9c3-b2cc30ca5c4f.png)

**Desktop:**
 - Operating system: Windows
 - R version: R version 4.1.1 (2021-08-10)
 - csasdown version: 0.0.10.9000

**Additional context**
I also tried adding another option `headsep=15pt` to the "geometry" package here
https://github.com/pbs-assess/csasdown/blob/a750391b1390b09719182a0a7742afe29bb9cda0/inst/csas-style/sr.sty#L61
but that has the same issue where two-line headers were too close. I tried this option two ways, with `\setlength{\headsep}{15pt}` present, and commented out.

**Comment by seananderson** [comment]
I've seen this with other reports. It's tough because we need a different height depending on how many lines the short title is. I haven't found a good way to deal with it automatically. A hack is to set `copy_sty = false` in the YAML and manually change the headsep value. At the very least, we should get that into the wiki.

I think I tried passing in the headsep value as a YAML argument, but couldn't get it to work, but that would be one option. Or perhaps an argument specifying a 1 or 2 line short title and then pick the right headsep value internally.

**Comment by grinnellm** [comment]
I guess LaTeX doesn't have an option to specify the space between the bottom of the header to the top of the text? I was hoping one of those two options above would do that, but they don't seem to. Or some way to have LaTeX measure the distance between the top of the page and the bottom of the header, then add a bit onto that? Something like `widthof` in the "calc" package, but for height?
https://github.com/pbs-assess/csasdown/blob/a750391b1390b09719182a0a7742afe29bb9cda0/inst/csas-style/sr.sty#L310

**Comment by seananderson** [comment]
Well there does appear to be `heightof` https://tex.stackexchange.com/questions/580137/latex-throws-error-on-heightof

I'm sure it's possible if you have the patience to figure it out.

**Comment by grinnellm** [comment]
I can give it a try. Do you think that's a good approach?

**Comment by seananderson** [comment]
If it works then that sounds good. You could probably just measure the height of the short header text itself and do something based on that... assuming it knows whether it's wrapped or not at that stage. Programming in TeX always feels like a foreign language to me, so I'm not sure.

**Comment by cgrandin** [comment]
The problem was the header height was not enough to accommodate two lines so it pushed the whole header down instead of starting higher. Should be good now.
