### ISSUE TITLE
Bibtex fine-tuning question: shortauthor  doesn't seem to work.

### ISSUE THREAD

**Issue by SOLV-Code** [pbs-assess/csasdowntex#198]
We have a a lot of grey literature reports in our citations , and tried to use *shortauthor* in the bib file, based on [this](https://tex.stackexchange.com/questions/452054/biblatex-how-to-use-organizations-acronym-in-in-text-citation-and-full-name), like the following:

```
@article{JTC2021Summary,
	title = {{Yukon River salmon 2020 season summary and 2021 season outlook}},
	journaltitle = {Alaska Department of Fish and Game, Division of Commercial Fisheries, Regional Information Report},
	volume = {3A21-01},
	shortauthor = {{JTC}},   # <-------------- ADDED THIS, BUT DIDN'T WORK
	author = {{Joint Technical Committee of the Yukon River U.S./Canada Panel}},
	date = {2021}
}
```
However, in-text citations are still showing up as *maximum 3% (Joint Technical Committee of the Yukon River U.S./Canada Panel 2021)*, rather than *maximum 3% (JTC 2021)*.

As a temporary fix, I'm changing the *author* to *JTC*, but I'm hoping there's a better solution. 

What I've found so far seems overly complicated and would require messing about with things that are probably handled somewhere insed *csasdown* , For example , see [here](https://stackoverflow.com/questions/48303890/using-short-author-citations-in-bookdown-rmarkdown), [here](https://stackoverflow.com/questions/48303890/using-short-author-citations-in-bookdown-rmarkdown), or [here](https://tex.stackexchange.com/questions/133700/problem-with-mkbibdateapalongextra-of-biblatex-apa).

If there's no quick fix, we'll just stick to using the acronym in the *author* field.

**Comment by cgrandin** [comment]
From what I can see you need to use `biblatex` as a `citation_package` to make use of `shortauthor`, but csasdown uses BibTex so it may not be possible.

**Comment by SOLV-Code** [comment]
OK, thank you. That saves a lot of time. I think we'll just go with acronyms for the common ones (DFO, JTC) and full names in both the citation and the references section for those less familiar to Cdn readers (Alaska Board of Fisheries)

It is really helpful to have this opportunity to check in with you regarding stuff like this. It has prevented me from going down unproductive rabbit-holes many times. Thank you again for your help this time, and all the times before!
