### ISSUE TITLE
Footnote formatting

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#199]
At least in Res Docs, the footnote formatting needs some tweaking.

Example:
![image (88)](https://user-images.githubusercontent.com/19349/142271337-704c133c-4d54-4d14-931b-e90458957a84.png)

Response:
> Font is good, but the footnote should be left aligned with the margin. Would be ideal to have a bit more space between the footnote line and text above but understand that’s sometimes hard to do.

**Comment by cgrandin** [comment]
![image](https://user-images.githubusercontent.com/4551051/142401281-d0c3fc8c-34b4-4adc-b580-2710d7175dc2.png)
