### ISSUE TITLE
Fix references to appendices

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#2]
- [ ] add `app:` in front
- [ ] currently creating something like Appendix A.6.1.1; should be Appendix A

**Comment by seananderson** [comment]
Most work but there's bug in the appendix line insertion:

Example:

```
\caption{Rearranged coefficients from the logistic regression maturity ogives. Parameters are in logit or log odds space. The intercept refers to the log odds of maturity for a theoretical fish of age zero.}\label{fig:age-mat-coefs}
\refstepcounter{chapter}
\end{figure}
```

**Comment by seananderson** [comment]
@robynforrest the solution is that you need to have a `\clearpage` at the end of the previous chapter/appendix or the beginning of the next. Add `\clearpage` at the top of the CPUE appendix and it works.

```
test \@ref(analysis-of-biological-data)
test \@ref(delay-difference-model)
test \@ref(commercial-cpue-standardization)
```

<img width="298" alt="image" src="https://user-images.githubusercontent.com/19349/45189238-d9d7d900-b1ec-11e8-8673-d40c88e3f5e0.png">

longterm perhaps we should automate that

**Comment by robynforrest** [comment]
Great thanks. Will try it in a few minutes

**Comment by robynforrest** [comment]
\clearpage works, thanks!
