### ISSUE TITLE
ResDoc References section different in French and English

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#200]
**Describe the bug**
In the csasdown example ResDoc, the way that the References section appear in the rendered PDF is different in French and in English.

**To Reproduce**
I am using the basic index.Rmd for the English version, and only changing the YAML header to `french: true` for the French version.

English:
1. Run `csasdown::draft("resdoc")
2. Knit the document.
3. The References section is numbered, despite the fact that it appears as `# REFERENCES {-}` on line 6 in file 04_references.Rmd 

French:
1. Run `csasdown::draft("resdoc")
2. Go to line 27 in file index.Rmd and change to `french: true`.
3. Go to line 6 in file 04_references.Rmd and change to `# RÉFÉRENCES CITÉES {-}`.
4. Knit the document.
5. Unexpected result in the PDF: the hyperlink to the section Références Citées in the navigation panel doesn't work, and the section is not numbered.

**Expected behavior**
Both the French and English versions should have a functioning hyperlink to the References section, and the References section should be numbered.

**Observed behavior**
The French and English versions are different.

**Screenshots**
![image](https://user-images.githubusercontent.com/1110182/143084857-9e0b3f55-e302-456e-abb5-c9af7ee30f3b.png)

**Desktop (please complete the following information):**
 - Operating system: Windows
 - R version: 4.1.2
 - csasdown version: 0.0.10.9000

**Comment by cgrandin** [comment]
This is still  broken. I came across it trying to do one of the tasks in #204. I'll try to fix it once and for all.
