### ISSUE TITLE
Implement 2022 CSAS formatting updates

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#204]
Changes:
•	Science Response Template 2022 French :
- [x] o	New French CSAS Name (header first page): Secrétariat canadien des avis scientifiques
- [x] o	French citation (in both French and English version): 
MPO. 2022. Title. Secr. can. des avis sci. du MPO. Rép. des Sci. 2022/nnn
- [x]  o	Last page, CSA title in mailing address is Centre des avis scientifiques (CAS) - add (CAS)
 
•	Science Response Template 2022 English:
- [x]  o	Last page, CSA title in mailing address is Centre for Science Advice (CSA) - add (CSA)
 
•	Res Doc Template 2022 French
- [x] o	1st page Header, new French CSAS name: now Secrétariat canadien des avis scientifiques (SCAS) 
- [x] o	2nd page: update the text “Also available in English:” to italics (already bolded or should be)
 
•	Res Doc Template 2022 English
- [x] o	2nd page: update the text “Aussi disponible en francais :” to italics (already bolded or should be)
- [x] o	2nd page: Add period to Cat No. (now Cat. No.)
 
•	Across both Res doc templates:
- [x] o	Update Heading Styles
- [x] •	Add period after the numbers
- [x] 	e.g. 1 INTRODUCTION become 1. INTRODUCTION, 2.1 becomes 2.1. , 2.1.1 becomes 2.1.1.
- [x] 	I think the appendix headings already reflect this but section headings would be structured the same way (A.1., A.1.2., A.1.2.3., etc.)
- [x] •	See annotated template for a visual, including spacing after the number (e.g., space between 1. and INTRODUCTION)
- [x] •	Spacing before/after headings has not changed
- [x] o	Update Address format, now:
Name of Affiliation 
Street/PO Address 
City, Province Postal Code
- [x] o	Update French citation to reflect new French CSAS name:  
Auteurs, I. 2022. Titre. Secr. can. des avis sci. du MPO. Doc. de rech. 2022/nnn
- [x] o	Update TOC to reflect updates in Heading styles (add period(s) after #, reduce space between number and heading) 
- [x] o	References are called References Cited and heading should be numbered (think this might already be fixed) e.g. 10. REFERENCES CITED / 10. RÉFÉRENCES CITÉES
- [x] o	Landscape pages do not need a line and page number on the side - this note came from Maritimes but I feel like this was fixed a while ago.
- [x] o	Update TeX style files to minimize words breaking across lines when rendering documents. E.g. 
Avoid this: 
 
 
Instead, wrap recommended to next line

**Comment by cgrandin** [comment]
I didn't do anything to change the "Update address format" task - they looked correct given the description
