### ISSUE TITLE
Move the .csl file into the `inst` package data folder

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#21]
This way it will stay up-to-date when people update the csasdown package and we won't end up with a whole bunch of these files hanging around in various people's projects.

**Comment by ricardd** [comment]
@seananderson , this issue can be closed, right?

**Comment by seananderson** [comment]
No this issue is referring to the need to keep the .csl files in the inst directory rather than having them in the user's project folder. Although now that I think about it maybe that's impossible because it's done directly by Pandoc. So I'll close this.
