### ISSUE TITLE
Problem with header and footer on landscape pages (csasdown SR)

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#213]
I am using the `landscapepage` environment for some wide tables. The header and header line, as well as the footer line are not right. The header is on two separate lines (see vertical alignment of left and right and left side text ("Pacific Region" and "Science Response:..."). The header line seems to be in the middle of the page, and the footer line is missing. Am I using the wrong environment? I'll post a MWE soon.
![image](https://user-images.githubusercontent.com/25674027/185466989-a8273af9-e525-4793-9ddb-7d0ebdf06fd1.png)

**Comment by grinnellm** [comment]
My attempt at a MWE.
[landscape.zip](https://github.com/pbs-assess/herringsr/files/9376915/landscape.zip)

**Comment by grinnellm** [comment]
(ref:allocation-sog-cap) This is the caption. This is the caption. 
This is the caption. This is the caption. This is the caption. 
This is the caption. This is the caption. This is the caption. 

\begin{landscapepage}

\setlength{\tabcolsep}{3.75pt}

```{r allocation-sog, results = 'asis', echo=FALSE}
alloc <- tibble::tribble(
    ~"MP and allocation", ~"Column 1", ~"Column 2", ~"Column 3", ~"Column 4", ~"Column 5", ~"FB", ~"Seine", ~"Gillnet",
  "NoFishFSC", "0.81", "0.45", "0.00", "0.14", "1.00", "-", "-", "-",
  "HS3060HR20alloc (no adjust)", "0.72", "0.26", "79.18", "10.26", "0.33", "0.21", "0.40", "0.39",
  "HS3060HR20alloc (0.1, 0.9)", "0.72", "0.26", "79.44", "10.35", "0.33", "0.21", "0.08", "0.71",
  "HS3060HR20alloc (0.9, 0.1)", "0.72", "0.26", "78.93", "10.20", "0.33", "0.21", "0.71", "0.08"
) 
top_head <- c(" " = 1, "Objectives" = 5, " " = 3)
names(top_head) <- c(" ", en2fr("Objectives", translate = french), " ")
middle_head <- c(
  " " = 1, "Conservation" = 1, "Biomass" = 1, "Yield" = 3,
  "Final allocation" = 3
)
names(middle_head) <- middle_head
n_cols <- ncol(alloc)
csasdown::csas_table(
  x = alloc, format = "latex", bold_header = FALSE,
  caption = ifelse(
    french, "(ref:allocation-sog-cap-fr)", "(ref:allocation-sog-cap)"
  ),
  align = c("l", rep("c", times = n_cols - 1))
)
```

\setlength{\tabcolsep}{6pt}

\end{landscapepage}

**Comment by grinnellm** [comment]
Is anyone else having this issue?

**Comment by cgrandin** [comment]
@grinnellm I can't look at this for a few weeks, busy with the Arrowtooth assessment, but you can by not copying the style file each time (set copy_sty to false in the YAML) then messing with the landscape settings in the style file (sr.sty) in your minimal example until the line goes away or moves how you want. That's all I would be doing if I were to do it!

**Comment by seananderson** [comment]
I just looked at this. I had another inquiry by email. With 

```
\begin{turn}
R plot here
\end{turn}
```

I get

![image](https://user-images.githubusercontent.com/19349/204906230-35a4f242-16bc-4913-98f7-46fbd229659a.png)

Which seems right except for the double headers and footers (note I've added test text in the header to show which is generating which).

And with 
```
\begin{landscapepage}
R plot here
\end{landscapepage}
```

I get

![image](https://user-images.githubusercontent.com/19349/204906150-1f2843b2-9aec-4ff2-87ba-86ee73d8fb51.png)

which is what @grinnellm showed above. It lacks the horizontal line at the top and the lower line floats up.

What was the purpose of the `turn` environment? Did this used to work? @maburton I think you worked on this in the past. I'm not really sure what's going on in that section of the SR style file.

Example zip folder here: 
[test98.zip](https://github.com/pbs-assess/csasdown/files/10127247/test98.zip)

**Comment by seananderson** [comment]
I figured out that removing this `AddEverypageHook` [code](https://github.com/pbs-assess/csasdown/blob/35410b6d871ab56d1aac22a60f7c7e4c99606a86/inst/csas-style/sr.sty#L317-L329) fixes the double headers/footers if you use the `turn` environment. Should we recommend using that instead of `landscapepage` like we currently do in the wiki?

**Comment by maburton** [comment]
The AddEverypageHook (to my memory) was what fixed the headers disappearing on multi-page tables problem. I'm going to have a look at the code

**Comment by seananderson** [comment]
Ah, good to know. I just pushed a version commenting out that hook, but that can be reversed as needed. Single page figures and tables seem to work in landscape with `turn`. Multi-page tables do have headers on each page with `turn` and the hook commented out but the font size seems off on the first page.
![image](https://user-images.githubusercontent.com/19349/204911416-02d9bf30-d058-484c-98e8-dececbb758ae.png)


[test98 2.zip](https://github.com/pbs-assess/csasdown/files/10127430/test98.2.zip)

**Comment by maburton** [comment]
So I had a look and it seems like the spacing of where it was putting the horizontal lines in the headers and footers was not what it should be and the figure/table was printing where latex was trying to put the lines and they were getting bumped to further down the page. I also adjusted the spacing of all of it so it matches the portrait pages. I just changed the addeverypagehook to `\AddEverypageHook{\ifdim\textwidth=\textheight
  \fancyhf{}\fancyfoot{}
   \begin{textblock*}{11pt}(0.575in,1in+\shorttitlelandWidth+\remainderlandWidth)
{\rotatebox{90}{\selectfont\fontsize{11}{13.2}\textbf{\rdRegion{}}}}\end{textblock*}
\begin{textblock}{0.05}(0.0518,0.0909)
{\rotatebox{90}{\selectfont\fontsize{11}{13.2}\textbf{Science Response: \rdTitleShort{}}}}\end{textblock}
\begin{textblock}{0.05}(0.89,0.5)
{\rotatebox{90}{\sffamily\selectfont\small\thepage}}\end{textblock}
  \begin{textblock}{0.05}(0.062,0.0909)
{\rotatebox{90}{\rule{9in}{0.25pt}}}\end{textblock}
  \begin{textblock}{0.05}(0.875,0.0909)
  {\rotatebox{90}{\rule{9in}{0.25pt}}}\end{textblock}
\fi}`

And left everything else as is. Then using your code you linked in the zip above, I can produce the tables with correct header/footer. 
![image](https://user-images.githubusercontent.com/50122470/204925897-c9532c63-23bb-49c7-8c0e-ab2e7c0b75e1.png)

It also works on landscape pages with figures
![image](https://user-images.githubusercontent.com/50122470/204925948-72366773-61d5-4939-92e9-4e8c874b7281.png)

You run this the same way as before with \landscapepage. Not sure why the spacing doesn't work anymore. I'll probably also look at the tech and resdoc stys and make sure that their spacing isn't also messed up. 

But also if you want to use turn that's fine by me. I do not know how to fix your second page text size issue though

**Comment by maburton** [comment]
@seananderson Also, it makes sense that commenting out addeverypagehook fixed the double header when using the turn environment, because turn creates a landscape page and then add headers and footers. Addeverypagehook looks for a landscape oriented page and adds headers and footers. The landscapepage environment creates a landscape page but does not add headers or footers (these get added later by addeverypagehook)

**Comment by seananderson** [comment]
Thanks @maburton!
