### ISSUE TITLE
Update all copyright statements :crown:

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#220]
`s/Her Majesty the Queen/His Majesty the King/`

> We have confirmed that the copyright statement must now be changed to the following:
For English reports: ©  His Majesty the King in Right of Canada, as represented by the Minister of the Department of Fisheries and Oceans, 2022
For French reports: ©  Sa Majesté le Roi du chef du Canada, représenté par le ministre du ministère des Pêches et des Océans, 2022

**Comment by seananderson** [comment]
Might still need to add "as represented by the Minister of the Department of Fisheries and Oceans". Not sure if that's everywhere or not.

**Comment by seananderson** [comment]
Wondering if this should actually be "as represented by the Minister of Fisheries and Oceans Canada", which seems far more prevalent on Google and represents our current department name. I'm reopening this until we get confirmation one way or the other.

**Comment by cgrandin** [comment]
Yes, that's right. We are no longer a "Department" despite still going by the acronym DFO. I suspect this is because they didn't want to go by FOC. But we are officially " Fisheries and Oceans Canada"

**Comment by seananderson** [comment]
Wikipedia clears this up.

“The legal name of the department is the Department of Fisheries and
Oceans. It is also referred to as "Fisheries and Oceans Canada" under
the Federal
Identity Program <https://en.m.wikipedia.org/wiki/Federal_Identity_Program>
.”

And the guidance on Crown copyright is now to use the legal name. It’s
barely been used in this form yet (so says Google), so we’re forging new
ground, but I got confirmation that it’s correct.

**Comment by cgrandin** [comment]
Aha...

I found the FIP site: 
https://www.tbs-sct.canada.ca/ap/fip-pcim/reg-eng.asp

I thought we were always supposed to use the "Applied title" for all communications, but if it says legal name then this says it's DFO

![image](https://user-images.githubusercontent.com/4551051/207824510-99ab28f5-59c4-4ca1-8c18-d9331f3665f3.png)

This is enlightening, I didn't know this all existed :)

**Comment by aulthouseb** [comment]
I see this issue is still open, and I just received feedback from the CSAS office that the copyright statement in the frontmatter should read "His Majesty the King in Right of Canada, as represented by the Minister of the <line break>
Department of Fisheries and Oceans, 2023". It currently just reads "His Majesty the King in Right of Canada, 2023"

**Comment by seananderson** [comment]
Done. Be sure to let us know when your publication comes out so we can add it to [the list](https://github.com/pbs-assess/csasdown/wiki/Publications-prepared-using-csasdown) (which is likely quickly getting out of date). A message on MS Teams, an email, or an issue here work.
