### ISSUE TITLE
rosettafish needed as dependent package?

### ISSUE THREAD

**Issue by MichaelFolkes** [pbs-assess/csasdowntex#221]
`rosettafish` is required in the techreport rmd.  Should it be a dependent? If commented out calls to `en2fr()` fail.

**Comment by seananderson** [comment]
It should be in the template examples but not used within the package functions, so it should be in `Imports`, which [it is](https://github.com/pbs-assess/csasdown/blob/85881411bda0e4f53f6f44115f2de96c39b78ea8/DESCRIPTION#L73). It also needs to then be loaded within the templates (`library(rosettafish)`), which I believe it is. Does that sound right?

**Comment by MichaelFolkes** [comment]
yep, sounds right.  I see it as a Suggest. 
my order of operation as suggested in the readme:

- `remotes::install_github("pbs-assess/csasdown")`
- (note: that  `csasdown` is not loaded in these steps)
- `csasdown::draft("techreport")`  (`rosettafish` not installed as it's a suggest)
- open `index.Rmd`
- attempt to compile. 
- `rosettafish` missing error.

In `index.rmd`  `rosettafish` is loaded before `csasdown`, is that the problem? Can't recall the nuances of suggested packages.

**Comment by seananderson** [comment]
Hmm, right. The default on the `dependencies` argument with
`remotes::install_github()` is `NA`, which is "Depends", "Imports" and
"LinkingTo". We could suggest modifying that to `TRUE`, which adds
'suggests'. I guess the point is you don't *need* rosettafish to use
csasdown, but I agree, not a great experience when the default draft
doesn't compile.

**Comment by MichaelFolkes** [comment]
I'll leave it to your decision if this is closed or not!

**Comment by cgrandin** [comment]
I'm closing this because the error message clearly states what is missing and there's been no other activity here for 1.5 years, and no other complaints.
