### ISSUE TITLE
Tech Report TeX error

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#222]
**Describe the bug**
Default Tech Report doesn't compile with fresh install of tinytex and TexLive.

**To Reproduce**
Run the first unit test in `test-render-techreport.R`

**Expected behavior**
PDF is created.

**Observed behavior**

The following TeX error:

```
! Missing = inserted for \ifnum.
<to be read again> 
                   v
l.14 \RequirePackage
                    [running]{lineno}  % Number lines (editing) 
```

**Desktop:**
 - Operating system: macOS, but I think @ricardd was getting this on Windows too
 - R version: R version 4.2.1 (2022-06-23)
 - csasdown version: current GitHub version

**Additional context**
I tried commenting out 
```tex
\RequirePackage[running]{lineno}
```
in the .sty file, but the error persists with other packages named.

I tried reverting to [this commit](https://github.com/pbs-assess/csasdown/tree/90ef4bf05a3aecf59547f7abde0dc513e416dbbb) and that didn't fix it either.

Coming back to this later, I no longer have this issue. The only difference, I think, is that I rendered a resdoc in between, thereby installing a bunch of other TeX packages.

**Comment by MichaelFolkes** [comment]
I can confirm the same error running Win10 and R version 4.1.1 (2021-08-10)
In my case it's a fresh install of `csasdown`, MikTex updater was run prior to attempted compile of the techreport's index.Rmd

**Comment by cgrandin** [comment]
For me, I deleted tinytex completely, then re-installed from scratch and the first thing I did after installing it was testthat::test_file("tests/testthat/test-render-techreport.R") 
 and it passed all the tests, no errors.
I then went through the normal procedure using csasdown::draft() and render() and it built the PDF fine.

Windows 10
R version 4.2.0 (2022-04-22 ucrt)
csasdown commit (84596)
tinytex version 0.42
Miktex is NOT installed on this machine

**Comment by MichaelFolkes** [comment]
I just uninstalled miktex (had to wait for IT to do it, arrggh).  Installed tinytex. 
Started rendering, after 30mins of tinytex installing packages, it rendered a-ok,
