### ISSUE TITLE
Can kableExtra::group_rows be used with csas_table?

### ISSUE THREAD

**Issue by krHolt** [pbs-assess/csasdowntex#228]
I am hoping for some advice on whether it is possible to use kableExtra::group_rows with csasdown::csas_table. 

I have been creating a multi-page table using kable with kableExtra::group_rows so that I can add horizontal lines and indented text to my table.  However, the CSAS office has asked me to make some formatting changes to get rid of re-occurring Table captions on each page.  The easiest way I have found to do this is to switch to csasdown::csas_table instead of kable, but then I loose the formatting I added with kableExtra::group_rows.  

Are there any examples using kableExtra::group_rows with csas_table?  Or, is there a better way for me to be adding this formatting to my csas_table?

Here is my current code using csas_table.  None of the horizontal lines or indents show up when rendered to a pdf. 

csasdown::csas_table(as.data.frame(stockTable), escape = FALSE,
                      booktabs = TRUE,
                      format = kable_format,
                      linesep = "\\addlinespace[5pt]",
                      caption = "Policy compliance of the Sablefish Management System with the Fish Stocks provisions and PA Policy (DFO 2009). Stock status estimates are taken from DFO 2023.",
                      align = c("l","r","l") ) %>%
  kable_styling(latex_options = c("hold_position", "scale_down"),
                  bootstrap_options = c("striped", "hover","scale_down")) %>%
  kableExtra::group_rows(start_row=2, end_row=7, latex_gap_space = "0.05em", hline_after = TRUE, indent = FALSE) %>% # Mgmt paradigm
  kableExtra::group_rows(start_row=8, end_row=12, latex_gap_space = "0.05em", hline_after = TRUE, indent = FALSE) %>% # Reference points
 kableExtra::group_rows(start_row=13, end_row=20, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) %>% # Assmt / Operating Model
  kableExtra::group_rows(start_row=21, end_row=21, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) %>% # Management Procedure
  kableExtra::group_rows(start_row=22, end_row=25, latex_gap_space = "0.1em", hline_after = FALSE, indent = TRUE) %>% # Data
  kableExtra::group_rows(start_row=26, end_row=27, latex_gap_space = "0.1em", hline_after = FALSE, indent = TRUE) %>% # Assmt
  kableExtra::group_rows(start_row=28, end_row=35, latex_gap_space = "0.1em", hline_after = FALSE, indent = TRUE)  %>% # HCR
  kableExtra::group_rows(start_row=36, end_row=48, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) %>% # Stock status
  kableExtra::group_rows(start_row=49, end_row=49, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE)  %>% # Rebuilding plan
  kableExtra::group_rows(start_row=50, end_row=54, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) %>% # Rebuilding criteria
  kableExtra::group_rows(start_row=55, end_row=61, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) %>% # Enviro
   kableExtra::group_rows(start_row=62, end_row=81, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) # Fishery objectives

**Comment by seananderson** [comment]
Is `format = "latex"` or the default `format = "pandoc"`? It may need to be `format = "latex"` here. (Not sure what value `kable_format` has above).

**Comment by krHolt** [comment]
The format is set to latex.  I have tried changing some of the bootstrap and latex options in kable_styling, but it doesn't help.  I have also updated my csasdown install (I think I was using an older version).

**Comment by seananderson** [comment]
I'm not sure what in csas_table() is breaking the group_rows. I've never see the group_rows function before. I tried working out an example. I'm not sure what exactly you're looking for in the end. Here's what I have:

```{r, eval=TRUE, results="asis"}
d <- data.frame(x = sample(1:100, 100, replace = TRUE), y = sample(1:100, 100, replace = TRUE))
d <- dplyr::as_tibble(d)
```

```{r, results='asis'}
library(magrittr)
# csasdown::csas_table(d, caption = "Caption", format = "latex") |>
knitr::kable(d, caption = "Caption", format = "latex", longtable = TRUE, booktabs = TRUE) |>
  kableExtra::kable_styling(latex_options = "repeat_header") |> 
  kableExtra::group_rows(start_row=2, end_row=7, latex_gap_space = "0.05em", hline_after = TRUE, indent = FALSE) %>% # Mgmt paradigm
  kableExtra::group_rows(start_row=8, end_row=12, latex_gap_space = "0.05em", hline_after = TRUE, indent = FALSE) %>% # Reference points
  kableExtra::group_rows(start_row=13, end_row=20, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) %>% # Assmt / Operating Model
  kableExtra::group_rows(start_row=21, end_row=21, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) %>% # Management Procedure
  kableExtra::group_rows(start_row=22, end_row=25, latex_gap_space = "0.1em", hline_after = FALSE, indent = TRUE) %>% # Data
  kableExtra::group_rows(start_row=26, end_row=27, latex_gap_space = "0.1em", hline_after = FALSE, indent = TRUE) %>% # Assmt
  kableExtra::group_rows(start_row=28, end_row=35, latex_gap_space = "0.1em", hline_after = FALSE, indent = TRUE) %>% # HCR
  kableExtra::group_rows(start_row=36, end_row=48, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) %>% # Stock status
  kableExtra::group_rows(start_row=49, end_row=49, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) %>% # Rebuilding plan
  kableExtra::group_rows(start_row=50, end_row=54, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) %>% # Rebuilding criteria
  kableExtra::group_rows(start_row=55, end_row=61, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) %>% # Enviro
  kableExtra::group_rows(start_row=62, end_row=81, latex_gap_space = "0.1em", hline_after = TRUE, indent = FALSE) # Fishery objectives
```

<img width="648" alt="image" src="https://user-images.githubusercontent.com/19349/235032324-e503c1e6-a8c9-4955-9da2-84840bf63a8b.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/19349/235032346-618dde4e-9c2e-4792-a526-570ba761d6f5.png">

The repeating headers (but not captions) part is responsible for much of the complexity in csas_table(). I forget what exactly CSAS wants, but presumably it's something like that, because Chris added it.

As a work around, could you have multiple smaller tables instead of gaps in one large table?

Another option, can you use the linesep argument?

E.g.

<img width="369" alt="image" src="https://user-images.githubusercontent.com/19349/235032652-d22e3aaf-f02c-4531-b906-72e7be1d8ba3.png">

<img width="419" alt="image" src="https://user-images.githubusercontent.com/19349/235032722-848d1c3b-d1a5-42c9-b2ed-675cd22e6042.png">

**Comment by cgrandin** [comment]
If you check out the tech report there are a couple of more complex table examples in there - https://github.com/pbs-assess/csasdown/blob/main/inst/rmarkdown/templates/techreport/skeleton/02_methods.Rmd

You should be able to use any `kableExtra` methods on the `csas_table()` output since it is just a `kable()`

**Comment by krHolt** [comment]
Thanks Sean & Chris for your help with this! 

I wasn't able to get kableExtra::group_rows working in the end, but I was able to add horizontal lines with kableExtra::row_spec(1, hline_after = TRUE)  (which, came from one of the examples Chris pointed me to in the tech report).  I wasn't able to add the indenting, but the table will be fine without this.

I'll close the issue now.  Thanks again!
