### ISSUE TITLE
draft() ignores directory argument

### ISSUE THREAD

**Issue by quang-huynh** [pbs-assess/csasdowntex#232]
**Describe the bug**
See title

**To Reproduce**
```
dir.create("test-folder")
setwd("test-folder")
file.create("do-not-delete.txt")
dir.create("make-report-here")

csasdown::draft(type = "resdoc", directory = "make-report-here")
```

**Expected behavior**
Create report files in `make-report-here`

**Observed behavior**
- Created report files in `getwd()`.
- More perniciously, I was prompted to delete all files in `make-report-here` (weird because it was empty) but `draft()` then deleted everything in my working directory! However I cannot reproduce this in the above example with `do-not-delete.txt`.
- I also suggest to add `type <- match.arg(type)` in the function.

**Comment by seananderson** [comment]
Thanks for the report of the bad bug. I've fixed it here https://github.com/pbs-assess/csasdown/commit/b3b3f8ed0c0dc62724f5ed4d5b9235c1fd5cd6a1
