### ISSUE TITLE
consider including Canadian Technical Report of Hydrography and Ocean Sciences

### ISSUE THREAD

**Issue by clayton33** [pbs-assess/csasdowntex#233]
I was wondering if it would be possible to include `Canadian Technical Report of Hydrography and Ocean Sciences` as document option. I believe the only difference between it and the `Canadian Technical Report of Fisheries and Aquatic Sciences ` is the cover page, inside cover page, and the citation.

I tried to 'trick' it to compile with the Ocean Sciences inside cover page by changing where it calls it in `tech-report.sty` file, with no success as it looks like that file is regenerated, or something, when the document is compiled.

**Comment by seananderson** [comment]
If you want to 'trick' it, you'll need to set `copy_sty: false`

>  copy_sty is a toggle to copy the style file from the csasdown package every time you compile
>  the document. If false, any changes you have made to the style file in your project
>  will remain between compilations. If true, your changes will be lost when you compile

You'll also need to create your own PDF cover pages and copy right pages and substitute those, I think.

**Comment by clayton33** [comment]
Oh that's perfect, I should have read through the `index.Rmd` file a bit more carefully. I'll try that. Thanks !

**Comment by clayton33** [comment]
The trick worked for me, so I'll consider this issue closed.
