### ISSUE TITLE
add install of rosettafish to .README 

### ISSUE THREAD

**Issue by DylanMG** [pbs-assess/csasdowntex#234]
Just getting started playing with csasdown. Step 5 in the setup of the .README won't work unless `rosettafish` is installed. 
Suggest adding this installation to step 2 of the setup guide. 
Small issue, but important for new users...

**Comment by seananderson** [comment]
Thanks. This change should fix that: https://github.com/pbs-assess/csasdown/commit/57fa8d63fa860963f2a38f8ae7e503453c5f179d
