### ISSUE TITLE
Errors on csasdown::render() with some French documents

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#238]
Unit test failure here:
https://github.com/pbs-assess/csasdown/blob/417f88c274099184c16470a5ec04a7759fec6598/tests/testthat/test-fix-envs.R#L91-L96

Error:

```
Error in `ans[ypos] <- rep(yes, length.out = len)[ypos]`:
! replacement has length zero
Backtrace:
 1. base::ifelse(fr(), meta$french_title, meta$title)
```

I assume this is related to having to revert to `bookdown::render_book("index.Rmd")` in some of the unit tests for French documents.

**Comment by cgrandin** [comment]
This is because the SR now has `title_other:` in the `index.Rmd` **YAML** instead of `french_title:` for some reason but the error checking code also expects it (weird). Is there a reason that it needs to be `title_other:` or can I change that back to `french_title:` like the rest of the doc types? It requires a bit more work to fix the error checking code as well.

**Comment by seananderson** [comment]
I guess that wasn't that long ago: https://github.com/pbs-assess/csasdown/commit/85cc4dda03d6513c11350f7f607cce1cacb6bf6a

The issue is the same index.Rmd is used for English and French docs. In the resdocs, the other language citation is written out: https://github.com/pbs-assess/csasdown/blob/5fca72471dcb59199d5022642e2fd08cd3a452a7/inst/rmarkdown/templates/resdoc/skeleton/skeleton.Rmd#L31

But the SR figures out that other language citation based on the other title arg. So, for a French document, that 'other' YAML arg should be the English title.

I don't know what's best to do here also thinking about backwards compatibility.

**Comment by seananderson** [comment]
Fixed [here](https://github.com/pbs-assess/csasdown/commit/5e9de068e9536495e40cd2103b2a0e2c9be05d2b) as described in the NEWS.md [here](https://github.com/pbs-assess/csasdown/blob/5e9de068e9536495e40cd2103b2a0e2c9be05d2b/NEWS.md?plain=1#L5-L7).
