### ISSUE TITLE
4th-level headers possible in res doc?

### ISSUE THREAD

**Issue by SOLV-Code** [pbs-assess/csasdowntex#239]
In a large res doc, we have a couple of places where 4th-level headers are necessary for clarity. We've implemented these as simple italic text like this ```*Header Text*```. However, in the final review, the CSAS office  requested changing these to fully formatted subheaders with indent, bold font and numbering, like **1.1.1.1 Header Text**.

When I tried to implement as ```#### Header Text``` it came out as a 3rd level header, the same as ```### Header Text``` 

- Is there any way for end-users to enable 4th-level headers?
- If not, could this option be added to the package?

**Comment by seananderson** [comment]
How is this? https://github.com/pbs-assess/csasdown/commit/740bd3525fa2162fe03fd824a6060c9cbc147203 
I'm not sure on the exact formatting I'm aiming for:
<img width="449" alt="image" src="https://github.com/pbs-assess/csasdown/assets/19349/42dba531-9f38-4b14-8752-2dbeaf52b056">

4th-level headings may or may not work in appendices yet.

**Comment by SOLV-Code** [comment]
Awesome, thank you! I will confirm with the CSAS office, but I think this is exactly what they were looking for.

**Comment by SOLV-Code** [comment]
Heard back from CSAS.  *"The four level headers look good except they should be left indented by 0.25 in"*. 

Also said they could fix that indent in the pdf at the end, if it is a pain to do in the csasdown template.

**Comment by seananderson** [comment]
Should be done now: https://github.com/pbs-assess/csasdown/commit/9dd85dd125a6491abb87a18d75604abe8f73c42c

**Comment by SOLV-Code** [comment]
Great, thank you!
