### ISSUE TITLE
Error knitting herring Science Response

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#241]
I get an error knitting the herring science response. I could be wrong but this might have to do with the recent commits regarding pandoc, and the fact that we are running older versions of R and RStudio?

If I knit the SR 

`bookdown::render_book("index.Rmd")`

it fails with

`Error in grep("^% START-PANDOC-3.1.8", csas_style) :`
`object 'csas_style' not found`

For now I can get around this by installing an older version of csasdown (Sept 27, 2023):

`devtools::install_github("pbs-assess/csasdown@92f7f6429fd0844f1f952a2e2b26b03f738e2dd9")`

and then it knits as expected.

We have to use older 32-bit R and RStudio versions to connect with 32-bit MS Access, so Pandoc is older too:

`rmarkdown::pandoc_version()`
`[1] ‘1.19.2.1’`
`R.version.string`
`[1] "R version 4.1.3 (2022-03-10)"`

And RStudio Version 1.1.463 – © 2009-2018 RStudio, Inc.

If it's not obvious what the problem is, I will make a small reproducible example and post it here soon.

**Comment by seananderson** [comment]
Huh, same as this: https://github.com/pbs-assess/csasdown/issues/240

I doubt that's from pandoc... it sounds like it can't find the 'csas_style' folder in the installed package data, although I have no idea what's changed around that. I'll look through the commit history.

**Comment by seananderson** [comment]
Ah, I think I see the bug.

**Comment by grinnellm** [comment]
I'm working on a small example to reproduce, would that help?

**Comment by seananderson** [comment]
Nope, I see the issue.

**Comment by seananderson** [comment]
Check if it's fixed now.

**Comment by grinnellm** [comment]
Amazing service, thanks Sean:)
That did it.. works just fine now.
