### ISSUE TITLE
Add an option on turn off `"Continued on next page..."` for long tables

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#245]
Easiest to just add an argument in `csas_table()`. Does anyone else remember if CSAS explicitly did or did not want this? @grinnellm ? @quang-huynh

**Comment by cgrandin** [comment]
Done in 6b831dbc7d586dfe742048292e813a68b126a377 cd4be9f187a5488c99bb09dbaa64d2fdd1cc9d8a
