### ISSUE TITLE
Appendix processing code breaks with the latest pandoc

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#253]
With sufficiently complex appendices, results in errors like:

```
Error in app_chunk[1:(appsection_inds[1] - 2)] : 
  only 0's may be mixed with negative subscripts
```

Broken with pandoc 3.1.12.1.

I'm struggling to follow all the logic, but it appears that this function no longer works as intended with the TeX now produced by pandoc: https://github.com/pbs-assess/csasdown/blob/main/R/add-appendix-subsection-refs.R
These -2 and -3 now need to be -1 and -2 https://github.com/pbs-assess/csasdown/blob/e6bfa157731ec200340133b6016ba7d2ca4d7e8b/R/add-appendix-subsection-refs.R#L25-L27

But there are more issues below.

I think these -1 and -2 may need to be 0 and -1. https://github.com/pbs-assess/csasdown/blob/e6bfa157731ec200340133b6016ba7d2ca4d7e8b/R/add-appendix-subsection-refs.R#L48-L50

Because the line indexing is off it's cutting up the vector in the wrong places creating all sorts of havoc (although the default template ends up OK because the appendix sections are so simple). Parts of one chunk end up in the next, headers get injected in the middle of tables, and so on.

**Comment by jdunic** [comment]
The appendices seem correct as of pandoc `3.1.6.2` and no longer work as of pandoc `3.1.8` (`3.1.7` unsupported).

**Comment by cgrandin** [comment]
This works with all the crazy appendix subsectioning that I put into the tech report template for testing
