### ISSUE TITLE
References end up in wrong location with recent pandoc

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#255]
Tested on resdocs. Run the basic unit test:
https://github.com/pbs-assess/csasdown/blob/e909aa5cfdd60445bdbd39af0b10383f927c512d/tests/testthat/test-render-resdoc.R#L18-L24

Output:
<img width="802" alt="image" src="https://github.com/pbs-assess/csasdown/assets/19349/57a8ab4e-0bb7-4e97-98d7-8b1168d9090f">

Expectation:
Bibliography is positioned after the references header before the appendices.

Confirmed to happen with pandoc `3.1.12.3`. Does not happen with `3.1.1` (baked into RStudio).

Any fix will have to detect the pandoc version, I assume.

**Comment by jdunic** [comment]
The bibliography position is correct as of pandoc `3.1.6.2` and no longer works as of pandoc `3.1.8` (`3.1.7` unsupported).

**Comment by seananderson** [comment]
Thanks for the detective work, @jdunic! Fixed.

```
hypertarget{refs}{}
```

in pandoc < 3.1.7/8 becomes 

```
\phantomsection\label{refs}
```

in pandoc >= 3.1.7/8
