### ISSUE TITLE
Help with special characters table? 

### ISSUE THREAD

**Issue by DylanMG** [pbs-assess/csasdowntex#256]
I have a fairly simple table with some tex formatting I am trying to render in a ResDoc. 

It renders fine when I run it in my figures-tables.Rmd but it won't knit when running index.Rmd. I get the `Error: LaTeX failed to compile` and have followed all steps on the Yi Hui page, and checked resdoc.log. 

resdoc.log was saying I had an unsupported unicode "^" character, which isn't even in my table. Tried using combos of `escape` and `format` arguments as suggested in the [escaping special characters section](https://bookdown.org/yihui/rmarkdown-cookbook/kable.html#escape-special-characters) in the Rmd cookbook. 

Table looks like this: 
[Table_Priors.csv](https://github.com/pbs-assess/csasdown/files/14670664/Table_Priors.csv)

and am tying to render simple code like this:
```
priors <- read.csv(here("analysis/data/raw/Table_priors.csv"))

csasdown::csas_table(priors,
                     escape = TRUE, format = "latex", #have tried every combo of T/F, pandoc/latex...
                     caption = "(ref:tab-prior-posterior)")
```

What could I be missing?

**Comment by seananderson** [comment]
What was your solution? It can be hard to read in .csv's like in that R with sufficient `\` escaping since I think you'd still need `\\` in the Rmd to end up with `\` in the .tex and the reading of a .csv strips off some level of `\` escapes.

**Comment by DylanMG** [comment]
I was trying to delete the issue because I found my main issue was actually some reference not working with tex. Then I dug back into this table and found I had some bad syntax where "$\sigma_S_{MAX}$" should have been "$\sigma_{S_{MAX}}$".

After fixing that the table works fine with a basic: 
```
csasdown::csas_table(priors,
                     escape = TRUE, 
                     caption = "(ref:tab-prior-posterior)")
``` 
Still learning to debug, Really need to take advantage of looking carefully at resdoc.log when things break!
