### ISSUE TITLE
Delete .upb file after rendering to clean up

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#258]
**Describe the bug**

A `.upb` file gets left behind when rendering. It would be nice to clean this up for the user.

**To Reproduce**

Build a resdoc or tech report. E.g. from the unit tests.

**Expected behavior**

No extra files get left behind.

**Observed behavior**

A file, such as `techreport.upb` gets left behind.

**Screenshots**

<img width="446" alt="image" src="https://github.com/pbs-assess/csasdown/assets/19349/82fdac4a-b321-4109-aaa8-15434471ffc9">

**Comment by cgrandin** [comment]
All the deletions occur at the end of the render() function
