### ISSUE TITLE
Bad margins for hyperlinks in references of ResDoc

### ISSUE THREAD

**Issue by DylanMG** [pbs-assess/csasdowntex#261]
When I go to knit my ResDoc references with hyperlinks run into the margins.

See here:
![bad-margin](https://github.com/pbs-assess/csasdown/assets/37416118/6565b249-41fd-4b4d-862e-5bfe233fb017)

and here for a really bad one!
![bad-margin2](https://github.com/pbs-assess/csasdown/assets/37416118/d6e9a1bd-3c2a-4f95-9ff8-2fdbbbc15577)

Not seeing other issues that address this when searching "margins". Link to my index.Rmd can be found [here](https://github.com/Pacific-salmon-assess/FR-PK-ResDoc/blob/main/index.Rmd).

**Comment by seananderson** [comment]
I've seen this before, but I thought we'd resolved this. The demo resdoc doesn't have those margin issues on .bib URLs when I try it (example below). Internally, we replace the `href` links with `\link{url-here}{link-text-here}`. So, either you're on an older csasdown or something about your document is breaking that substitution.

i.e., this should work:

```
@article{swainbenoit2015,
 author = {Swain, D.P. and Benoît, H.P.},
 title = {Extreme increases in natural mortality prevent recovery of collapsed fish populations in a {N}orthwest {A}tlantic ecosystem},
 journal = {Mar. Ecol. Prog. Ser.},
 year = {2015},
 volume = {519},
 url = {https://www.int-res.com/abstracts/meps/v519/p165-182/},
 pages = {165-182}
}
```

Internally, this is what happens (so, it would be frustrating, but this is one solution)

```
@article{francis2011,
	author = {R. I. C. C. Francis},
	title = {\link{https://cdnsciencepub.com/doi/abs/10.1139/f2011-025}{Data weighting in statistical fisheries stock assessment models}},
  journal   = {Can. J. Fish. Aquat. Sci.},
	year = {2011},
	Volume = {68},
	Number = {6},
	Pages = {1124-1138},
}
```

<img width="881" alt="image" src="https://github.com/pbs-assess/csasdown/assets/19349/d94e5d63-55cb-4805-8e43-b4f8c5de9e2d">

Can you try building this example and see if it still happens for you?

[demo.zip](https://github.com/user-attachments/files/15959800/demo.zip)

**Comment by DylanMG** [comment]
When importing from Zotero, parts of the title that were in title case were imported like `title = {How to write a {{Bad Title}}}`, which would make R ignore the spacing of the text in the `{{ }}`. I just used a little hack `title = {How to write a {B}ad {T}itle}` and it seems to work. I guess it's an issue with how Zotero imports stuff to R, and then how csasdown renders it?

**Comment by seananderson** [comment]
Interesting, I didn't realize that. The usual best practice in a .bib file would be 

```
title = {How to write a {Good} {Title}}
```

 I.e., protect the whole word but don't connect them. That should work too, I would think. I didn't realize the stuff in the `{}` wouldn't wrap here. I'm sure there's some other solution but it's probably over my head.

**Comment by seananderson** [comment]
If you want my honest answer, I just quickly trash the DOIs and URL lines in my .bib file for CSAS reports (except for the few cases where a link is critical) because I can't be bothered with this type of thing. :)

**Comment by quang-huynh** [comment]
`\emph{}` wrappers seem to interfere with word wrapping, for example, when the species name is in the title.

At worst, add a manual linebreak `\\` in the bibtex reference
