### ISSUE TITLE
fsar branch _PACKAGE unrecognized, 

### ISSUE THREAD

**Issue by Sages11** [pbs-assess/csasdowntex#262]
When building the fsar branch of csasdown this warning is given:
Warning: csasdown.Rd: docType '_PACKAGE' is unrecognized

![image](https://github.com/user-attachments/assets/407f2a9a-69f7-423a-ae2f-5759e3d993a0)

I believe this might be having downstream effects on the fsar branch.

**Comment by seananderson** [comment]
Thanks - fixed in the main and fsar branches.
