### ISSUE TITLE
Line nums appear even when `copy_sty` and `line_nums` are set to `false` in YAML

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/csasdowntex#269]
In the SR at least, line numbers appear even when `line_nums` is `false`. It is also still required that if `copy_sty` is set to `false`, `line_nums` must be as well. I forget why this was, but the error message is:

```
Error: ✖ You have set copy to FALSE and line_nums to TRUE in the index.Rmd YAML header.
The permanent style file cannot be modified as needed to include line numbering.
Either set copy to TRUE or line_nums to FALSE to build.
``` 

Best fix would remove the need for both items to be `false`.

**Comment by SOLV-Code** [comment]
I think the exact same issue is happening with Tech Reports. Have you implemented the same fix there?  If yes, it must be something else, and I'll initiate a separate issue with a proper reproducible example. But I figured I'll check first, in case it's just a matter of transferring the fix to the other templates.  (I just removed and reinstalled csasdown and it's now showing version 0.2.1)

I'm using it to generate a set of workshop handouts where the layout, especially the tables, mirror the contents of a tech report that's taking shape, but used '''copy_sty false''' to edit the style file and remove the front matter (cover page, abstract, etc).  Turning off the line_num doesn't remove them.
