### ISSUE TITLE
Make a French version of the .csl file

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#28]
e.g. from @ricardd "and" can appear as "et" both in the inline references and in the bibliography.

**Comment by ricardd** [comment]
@seananderson , I can't see how to change this in the csl file, the only option for the separator between the second-to-last and the last name are "text" and "symbol". How can "and" be changed to "et"?

http://docs.citationstyles.org/en/stable/specification.html#name

**Comment by ricardd** [comment]
After further digging, I guess that the locale would take care of this?

https://github.com/citation-style-language/locales/wiki

I am adding csas-FR.csl files to csasdown/inst/rmarkdown/templates/*/skeleton/csl/ with the hope that once the French YAML option is activated it will take care of this.

**Comment by ricardd** [comment]
Pretty sure that this will work, I tried editing the CJFAS .csl file online, and changing the locale to "fr-CA" under "Global Formatting Options" does the trick of changing "and" to "et" to both inline references and to the bibliography.

http://editor.citationstyles.org/visualEditor/

**Comment by ricardd** [comment]
closing this issue, see pull request #34
