### ISSUE TITLE
Add option to disable section numbers in PDF res docs

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#30]
Should pass from YAML as logical to .tex and use one of the various TeX tricks to suppress the numbers.

**Comment by ricardd** [comment]
Related to this issue, I have built a document without section numbers by adding {-} the each section names (e.g. # INTRODUCTION {-}).

This works fine in that the document is rendered correctly without section numbers.

But while the document navigation panel displays correctly, the hyperlinks to the different sections in the output PDF do not work correctly, they all link to the title page. Is this an unrelated issue?

**Comment by seananderson** [comment]
The links do seem to break with `{-}`.

Ultimately we need to pass a YAML option to the .tex, which gets passed to the .sty, which uses an if-else statement to add something like this:

```
\makeatletter
\def\@seccntformat#1{%
  \expandafter\ifx\csname c@#1\endcsname\c@section\else
  \expandafter\ifx\csname c@#1\endcsname\c@subsection\else
  \expandafter\ifx\csname c@#1\endcsname\c@subsubsection\else
  \csname the#1\endcsname\quad
  \fi\fi\fi}
\makeatother
```

e.g. https://tex.stackexchange.com/questions/244668/remove-numbering-from-section-and-subsection

That seems to work in a test .tex CSAS document.

**Comment by ricardd** [comment]
@seananderson , how would that work? Is this something that would appear in index.Rmd?

**Comment by seananderson** [comment]
That above code needs to appear in the preamble, possibly directly in the .sty file. A YAML argument in index.Rmd would have to get passed through and then based on an if-else statement (in tex) included or not included.

**Comment by ricardd** [comment]
So the if-else would added to csasdown\inst\csas-tex\res-doc.tex?

**Comment by seananderson** [comment]
It would wrap that tex code listed above wherever that ends up. It would work in the sty file. It might work in the .tex file in the preamble too. I’m not sure.

**Comment by ricardd** [comment]
Not sure why, but the hyperlinks to the appendices do work.

**Comment by seananderson** [comment]
The appendices are coded differently but that might be a clue to what the solution is.

**Comment by jordanoplante** [comment]
Hi guys! I'm not so sure as to where this topic is at right now, but when I looked at the `resdoc_pdf()` help page, it says we can use other arguments from `bookdown::pdf_book()`. In this last function, would `number_sections`, which is a T/F argument indicating whether or not we want numbered section headings, be exactly what we are looking for here?

Unfortunately, I tried it but the numbered sections are still shown after knitting the document...

**Comment by seananderson** [comment]
It won't work unless we add explicit code for it using something like what is described above. I'll re-open this issue. You can also try freezing the .sty file after building once `copy_sty: false` https://github.com/pbs-assess/csasdown/blob/635c18c95493c031a347cfe94458f6e0bfdd07a7/inst/rmarkdown/templates/resdoc/skeleton/skeleton.Rmd#L24-L28 and adding your own TeX to the .sty file that turns off the numbering using an option from here:
https://tex.stackexchange.com/questions/244668/remove-numbering-from-section-and-subsection

**Comment by jordanoplante** [comment]
Thanks for the feedback @seananderson. I'll try this out.

**Comment by cgrandin** [comment]
In the fix I'm about to push, you need to add the `include_section_nums` line to your **index.Rmd** for old projects. In new projects (ones made with `csasdown::draft("resdoc")`) it will be included:

![image](https://user-images.githubusercontent.com/4551051/140605243-e7671056-aac2-4c2a-beec-df96801dcd56.png)
