### ISSUE TITLE
How to deal with wide tables that require landscape orientation?

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#31]
The CSAS style file for LaTeX provides functionality for landscape orientation through "landscapepage" defined in res-doc.sty

However, using the csasdown function csas_table enclosed within \begin{landscapepage} and \end{landscapepage} yields an improperly formatted table:

![image](https://user-images.githubusercontent.com/1110182/52758500-e0aa1980-2fde-11e9-9bd9-d9778e6df610.png)

What is clashing here?

**Comment by seananderson** [comment]
Have you tried not using `csas_table`? You can also put just plain old LaTeX in the .Rmd document. It won't render in the Word document but it will in the PDF. If you wanted to get fancy you could use an if else statement to render one way with TeX and the other way with .docx.

**Comment by ricardd** [comment]
@seananderson , using plain old LaTeX does work to a certain extent. Since my table is wide and long, I am using longtable. For some reason, the table caption is repeated on the second page, and the page number on the second page appears on the left of the landscape page instead of the bottom.

![image](https://user-images.githubusercontent.com/1110182/52860913-41347600-3107-11e9-9e00-40b52ec6c0c6.png)

The table is created using a CSV file that is used to create a .tex file using xtable, and then included using "\input". In the .Rmd file it looks like this:

```

```{r tablandingsWatage}
FisheryWAA <- read.csv("data/FisheryWAA.csv")
xt.fn <- "data/FisheryWAA.tex"
library(xtable)
xt <- xtable(FisheryWAA, label="tablandingsWatage", caption="Average weight at age (kg) of 3 to 16+ of removals for the southern Gulf of St. Lawrence cod stock, 1971-2018. \"Total\" represents the abundance-weighted average weight of 3+ fish.")
names(xt) <- c("Year","3","4","5","6","7","8","9","10","11","12","13","14","15","16+","Total")
print.xtable(xt, type="latex", file = xt.fn, floating=FALSE, tabular.environment="longtable", include.rownames=FALSE, caption.placement="top", add.to.row=list(pos=list(c(0)), command=c(paste("\\hline \n",
                             "\\endhead \n",
                             "\\hline \n",
                             "{\\footnotesize Continued on next page} \n",
                             "\\endfoot \n",
                             "\\endlastfoot \n",sep=""))), hline.after=c(-1))
        ```

\begin{landscapepage}
\input{data/FisheryWAA.tex}
\end{landscapepage}

```

And as you said, it doesn't render it in the Word document.

**Comment by seananderson** [comment]
The caption repeating on subsequent pages is a longtable option. I think that's the default.

The page number appearing in the wrong orientation on subsequent pages is a TeX issue too. Solvable with something like this apparently: https://tex.stackexchange.com/questions/313334/landscape-longtable-pagenumber-rotation-works-only-for-1-page

The one solution would be to use this xtable option for tex output and use kable/csas_table for the .docx output. You could do this by wrapping them in `if(knitr:::is_latex_output())`.

**Comment by ricardd** [comment]
I tried manually adding \begin{landscapepage} and \end{landscapepage} (environment defined in csas-style) to the LaTeX file produced by knitr , and it works fine, but now the table header is not right:

<img width="567" alt="Capture" src="https://user-images.githubusercontent.com/1110182/55412456-c238b700-5567-11e9-9fdf-1c569ad56d56.PNG">

Perhaps @andrew-edwards would have some insight into properly rendering a wide and long table in landscape orientation?

**Comment by cgrandin** [comment]
Andy is away for a month. I wrote the \landscapepage macro a few years ago, but the problem with the header in your table is due to the xtable code options you're using, not the landscapepage code. You'll have to run a minimum example to debug that I think

**Comment by cgrandin** [comment]
Also, see the \fancypagestyle{csaplscape} code which is what actually sets up the block that the landscape page is in. There's a bit more explanation of what's going on.

**Comment by cgrandin** [comment]
Email from @ricardd: Hi guys,
If you are available tomorrow, could I give someone a call to try and resolve the landscape issue for csasdown:

**Comment by cgrandin** [comment]
My reply: I think the time would be best spent if you produce a minimum working example of the issue, i.e. give me a tex document that renders wrong and I can fix the landscapepage macro (or add a new one for wide/long tables). I’m going to add these messages to the discussion on GitHub so we have a record of it. Better to use issues.

**Comment by ricardd** [comment]
@cgrandin , as requested, here is my minimal example. Step 1, the "problem"

I follow the README procedure and create a new Research Document using 

```
csasdown::draft("resdoc")
```

I then try to produce a long and wide data frame (e.g. a catch-at-age matrix for 45 years and 15 age classes), and add it as a table in the resdoc. So I am adding this code chunk to the very bottom of 01-chap1.Rmd

    ```{r longwide, results="asis"}
    yrs <- 1:45
    ages <- 1:15
    wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4), nr=length(yrs), nc=length(ages), 
    dimnames=list(year=yrs, age=ages))
    w.l.df <- data.frame(cbind(yrs, wide.and.long))
    
    csasdown::csas_table(
      w.l.df,
      col.names = c("Year", as.character(ages)),
      caption = "A long and wide table"
      )
    ```


I then knit the document to a PDF without changing anything else. The resulting table appears on pages 5-6 and is too large for the document so it spills into the right margin:

![Capture](https://user-images.githubusercontent.com/1110182/56746099-eb58fb80-6751-11e9-835b-180ba881b565.PNG)

**Comment by ricardd** [comment]
Minimal example. Step 2, trying to set a landscape section around the table, first attempt 

At the bottom of 01-chap1.Rmd, I surround the code block with \begin{landscapepage} and \end{landscapepage}:


    \begin{landscapepage}
    ```{r longwide, results="asis"}
    yrs <- 1:45
    ages <- 1:15
    wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4), nr=length(yrs), nc=length(ages), 
    dimnames=list(year=yrs, age=ages))
    w.l.df <- data.frame(cbind(yrs, wide.and.long))
    
    csasdown::csas_table(
      w.l.df,
      col.names = c("Year", as.character(ages)),
      caption = "A long and wide table"
      )
    ```
    \end{landscapepage}


In the rendered PDF, the table now appears on pages 7-8, with 2 problems: 1) the table is not correctly formatted (table header and table rows do not look good) and 2) the page numbers on pages 7 and 8 appear at different places:

![Capture](https://user-images.githubusercontent.com/1110182/56746939-81415600-6753-11e9-8f9a-92787efd788e.PNG)

**Comment by ricardd** [comment]
Minimal example. Step 3, trying to set a landscape section around the table, second attempt

Instead of using csastable, use the xtable package to create a separate .tex file that contains the table and then use LaTeX's \input to include the table in the document. So the bottom of 01-chap1.Rmd is changed to this:

    ```{r longwide, results="asis"}
    library(xtable)
    yrs <- 1:45
    ages <- 1:15
    wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4), nr=length(yrs), nc=length(ages), 
    dimnames=list(year=yrs, age=ages))
    w.l.df <- data.frame(cbind(yrs, wide.and.long))
    xt <- xtable(w.l.df, label="tablongwide", caption="A long and wide table", digits=c(0, 0, rep(2,15)))
    names(xt) <- c("Year",as.character(ages))
    print.xtable(xt, type="latex", file="data/long-wide.tex", tabular.environment = "longtable", 
    include.rownames=FALSE, caption.placement="top")
    ```
    
    \begin{landscapepage}
    \input{data/long-wide.tex}
    \end{landscapepage}


The table appears, formatted correctly, on pages 7-8 and the page numbers appear at different places:

![Capture](https://user-images.githubusercontent.com/1110182/56749566-5d344380-6758-11e9-9b5b-5fc9640db30a.PNG)

In addition, this will no render the table if the document's output is in Word.

**Comment by ricardd** [comment]
The ideal solution for the long and wide table would be that : 

1. the table is correctly formatted
2. the page numbers appear on the lower long edges of the landscape pages (i.e. always on the "bottom" of the page)
3. the table would appear in a Word document output

When a solution is found, it would be nice if it was added to the example document produced by csasdown's draft function. We could also add a landscape section with a wide figure.

**Comment by cgrandin** [comment]
This solves most of it. But not the hard part which is making sure pages after the first page have the correct geometry. I'm working on that now. It involves changing the definition of csaplscape in the style file. In the past, I have manipulated the table to avoid wide longtables by changing the font size and spacing as shown below.
<pre>
\begin{landscapepage}
```{r longwide, results="asis"}
yrs <- 1:45
ages <- 1:15
wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4), nr=length(yrs), nc=length(ages), 
dimnames=list(year=yrs, age=ages))
w.l.df <- data.frame(cbind(yrs, wide.and.long))
names(w.l.df) <- c("Year",as.character(ages))

get.align <- function(num,
                      first.left = TRUE, ## Keep the first column left-justified
                                         ## If FALSE, it will be justified according to the 'just' argument
                      just = "r"         ## just is the justification to use for the columns, "r", "l", or "c"
                      ){
  ## Returns a character vector used in the align argument of the xtable command.
  ## e.g. posterior output tables, reference point tables. Most tables really.
  ## num is the number of columns in the table
  if(first.left){
    align <- c("l", "l")
  }else{
    align <- c(just, just)
  }
  for(i in 1:(num-1)){
    align <- c(align, just)
  }
  return(align)
}

latex.size.str <- function(fnt.size, spc.size){
  ## Returns a string which has the given font size and space size applied
  paste0("\\fontsize{", fnt.size, "}{", spc.size, "}\\selectfont")
}

size.string <- latex.size.str(12, 11)
print(xtable::xtable(w.l.df,
                     caption = "A long and wide table",
                     label = "refLabel",
                     align = get.align(ncol(w.l.df))),
                     caption.placement = "top",
          include.rownames = FALSE,
          sanitize.text.function = function(x){x},
          size = size.string,
          table.placement = "H",
          tabular.environment = "longtable",
          hline.after = c(0),
          NA.string = "--",
          booktabs = TRUE)
```
\end{landscapepage}
<\pre>

**Comment by seananderson** [comment]
Would this be good enough?

All I did was add 

```
%>% kableExtra::landscape() %>% 
      kableExtra::kable_styling(font_size = 8)
```

And I specified the format as LaTeX. I can't get any of the formats to come out correctly in Word. You might have to use a `if(knitr:::is_latex_output())` and create a different format table for Word that isn't landscape. I don't know if there is a way around that.

And I switched from the pdflscape package to the lscape package, which doesn't rotate the page:
https://github.com/pbs-assess/csasdown/commit/52bfdc69b5e8bc7eb1cb6181f52213857bee3347

I.e. you will need to install the latest csasdown first.

    ```{r longwide, results="asis"}
    yrs <- 1:45
    ages <- 1:15
    wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4),         nr=length(yrs), nc=length(ages), 
    dimnames=list(year=yrs, age=ages))
    w.l.df <- data.frame(cbind(yrs, wide.and.long))
    
    csasdown::csas_table(
      w.l.df,
      col.names = c("Year", as.character(ages)),
      caption = "A long and wide table",
      format = "latex"
      ) %>% 
      kableExtra::landscape() %>% 
      kableExtra::kable_styling(font_size = 8)
    ```

![image](https://user-images.githubusercontent.com/19349/56754624-5995c200-6742-11e9-9c48-f12a49e82742.png)

**Comment by ricardd** [comment]
@seananderson this could just do the trick, let me try and get back to you.

If that is our solution, I guess that we should add kableExtra to Suggests in DESCRIPTION

**Comment by ricardd** [comment]
@seananderson I think that does the trick!

One slight addition so that the table header is repeated on subsequent pages:

    ```{r longwide, results="asis"}
    yrs <- 1:45
    ages <- 1:15
    wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4), nr=length(yrs), nc=length(ages), 
    dimnames=list(year=yrs, age=ages))
    w.l.df <- data.frame(cbind(yrs, wide.and.long))
    
    csasdown::csas_table(
      w.l.df,
      col.names = c("Year", as.character(ages)),
      caption = "A long and wide table",
      format = "latex"
      ) %>% 
      kableExtra::landscape() %>% 
      kableExtra::kable_styling(font_size = 8, latex_options = "repeat_header")
    ```

I also get a "LaTeX Warning: Label `tab:longwide' multiply defined."

**Comment by ricardd** [comment]
I just changed all my tables and am happy with the output, if CSAS is too then we are in good shape.

Just as in my previous comment, all tables using the above solution appear as having multiply defined labels. Do you know why that is?

**Comment by seananderson** [comment]
If you look at the .tex you'll see that it copies the caption when you added "repeat_header" and the caption includes the label. I looked at the help for `kable_styling` I think something like this works:

    ```{r longwide, results="asis"}
    yrs <- 1:45
    ages <- 1:15
    wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4), nr=length(yrs),     nc=length(ages), 
    dimnames=list(year=yrs, age=ages))
    w.l.df <- data.frame(cbind(yrs, wide.and.long))
    
    csasdown::csas_table(
      w.l.df,
      col.names = c("Year", as.character(ages)),
      caption = "A long and wide table",
      format = "latex"
      ) %>% 
      kableExtra::landscape() %>% 
      kableExtra::kable_styling(font_size = 8, latex_options = "repeat_header", 
         repeat_header_text = "Continued.", repeat_header_method = "replace")
    ```

**Comment by ricardd** [comment]
Happy with this lovely solution. 

Knowing how to pipe additional kableExtra functions is awesome, I modified a number of tables that now look much better than previously.

Thanks again @seananderson and all

**Comment by ricardd** [comment]
@seananderson I was informed not to repeat the Table number on subsequent pages for long tables. But I can't figure out how to repeat the header row only and not the "Table x. Continued" part. I tried this:

   ```{r longwide, results="asis"}
   yrs <- 1:45
   ages <- 1:15
   wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4), nr=length(yrs),     nc=length(ages), 
   dimnames=list(year=yrs, age=ages))
   w.l.df <- data.frame(cbind(yrs, wide.and.long))
   
   csasdown::csas_table(
     w.l.df,
     col.names = c("Year", as.character(ages)),
     caption = "A long and wide table",
     format = "latex"
     ) %>% 
     kableExtra::landscape() %>% 
     kableExtra::kable_styling(font_size = 8, latex_options = "repeat_header", 
        repeat_header_text = "", repeat_header_method = "replace")
   ```
but it still puts "Table x" on the second page of the long table. I would like to have the header row, and the header row only.

**Comment by seananderson** [comment]
Is this what you are looking for?

    ```{r longwide, results="asis"}
    yrs <- 1:45
    ages <- 1:15
    wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4), nr=length(yrs),         nc=length(ages), 
    dimnames=list(year=yrs, age=ages))
    w.l.df <- data.frame(cbind(yrs, wide.and.long))
    
    csasdown::csas_table(
      w.l.df,
      col.names = c("Year", as.character(ages)),
      caption = "A long and wide table",
      format = "latex"
      ) %>% 
      kableExtra::landscape() %>% 
      kableExtra::kable_styling(font_size = 8, latex_options = "repeat_header", 
         repeat_header_text = "", repeat_header_method = "replace") %>% 
      sub("\\caption\\[\\]\\{\\}", "\\caption*{}", .)
    ```

![image](https://user-images.githubusercontent.com/19349/57035188-41241c80-6c06-11e9-836b-baf718825291.png)

Figured that out from the longtable documentation: http://www.ctex.org/documents/packages/table/longtable.pdf

If this turns out to check all the CSAS boxes, then we can wrap:

```
      kableExtra::kable_styling(latex_options = "repeat_header", 
         repeat_header_text = "", repeat_header_method = "replace") %>% 
      sub("\\caption\\[\\]\\{\\}", "\\caption*{}", .)
```

into a little function in csasdown.

**Comment by ricardd** [comment]
@seananderson , yes this works fine, thanks.

**Comment by cgrandin** [comment]
I noticed this this morning:
![image](https://user-images.githubusercontent.com/4551051/57235761-73ec5d00-6fd8-11e9-9f71-d07f0bdf4ca1.png)

**Comment by seananderson** [comment]
Is that with the research document or science response?

It still works for me in the research document even with the updated TeX distribution with the following at the end of `01-chap1.Rmd`:

    ```{r longwide, results="asis"}
    yrs <- 1:45
    ages <- 1:15
    wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4), nr=length(yrs),             nc=length(ages), 
    dimnames=list(year=yrs, age=ages))
    w.l.df <- data.frame(cbind(yrs, wide.and.long))
    
    csasdown::csas_table(
      w.l.df,
      col.names = c("Year", as.character(ages)),
      caption = "A long and wide table",
      format = "latex"
      ) %>% 
      kableExtra::landscape() %>% 
      kableExtra::kable_styling(font_size = 8, latex_options = "repeat_header", 
         repeat_header_text = "", repeat_header_method = "replace") %>% 
      sub("\\caption\\[\\]\\{\\}", "\\caption*{}", .)
    ```

**Comment by cgrandin** [comment]
Yes that code works Sean. I still had xtable and \landscapepage in my document example from the other day

**Comment by sabledata** [comment]
Just finishing a csas report pdf (it is awesome) and I just cannot figure out a long sidways appendix where the appendix title, decsription and table are all sideways on the same page. Here's my minimal example using the code from above and package \usepackage{pdflscape}.  Also image attached.
![Capture](https://user-images.githubusercontent.com/55628556/76031609-e249c680-5eec-11ea-9975-c92efd244605.PNG)

\clearpage
# THE SECOND APPENDIX, FOR FUN {#app:second-appendix}
\begin{landscape}
More content to describe the second appendix.
\end{landscape}

```{r longwide, results="asis"}
yrs <- 1:45
ages <- 1:15
wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4), nr=length(yrs),         nc=length(ages), 
dimnames=list(year=yrs, age=ages))
w.l.df <- data.frame(cbind(yrs, wide.and.long))

csasdown::csas_table(
  w.l.df,
  col.names = c("Year", as.character(ages)),
  format = "latex"
  ) %>% 
  kableExtra::landscape() %>% 
  kableExtra::kable_styling(font_size = 8, latex_options = "repeat_header", 
     repeat_header_text = "", repeat_header_method = "replace") %>% 
  sub("\\caption\\[\\]\\{\\}", "\\caption*{}", .)
```

**Comment by seananderson** [comment]
Is there anyway you can squeeze it into a regular portrait table? There are other problems with landscape pages that we have yet to resolve that CSAS has been giving us problems with and @cgrandin and I have spent a lot of time already trying to fix them.

You can make the columns wrap using `kableExtra::column_spec()`.

For example:

```r
csasdown::csas_table(your_table_data, caption= "Your caption") %>%
 kableExtra::column_spec(1, width = "1.75cm") %>%
  kableExtra::column_spec(2, width = "1.75cm") %>%
  kableExtra::column_spec(3, width = "1.75cm") %>%
  kableExtra::column_spec(4, width = "9.5cm")
```

![image (3)](https://user-images.githubusercontent.com/19349/76105906-b5e48780-5f8a-11ea-999b-28f5ca8ca2c3.png)

**Comment by andrew-edwards** [comment]
And I don't think you'd want the Appendix title sideways anyway. Suggest having a sentence of text on first portrait page and then put the sideways table on the next page. Only a table should be sideways, and as Sean said, it's best to avoid if possible.

**Comment by sabledata** [comment]
Thanks for the quick replies and info @seananderson and @andrew-edwards. I thought I may have overlooked some function.  Fishing set specifications (dates, times, duration, lats, longs, depths.....) are always a challenge to list as portrait in an appendix, hence they usually end up in many reports in landscape format with sideways titles :-P
