### ISSUE TITLE
footnote not rendering

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#33]
In a section of a ResDoc, I added a footnote (\footnote{Some text.}), but it does not appear in the rendered in the PDF output.

Why is this?

**Comment by seananderson** [comment]
The example footnote in the template seems to work. Does this work for you:
https://github.com/pbs-assess/csasdown/blob/33cb8ec9d2192ac2bdf807bfafc1e529c26fd8fe/inst/rmarkdown/templates/resdoc/skeleton/03-chap3.Rmd#L74

**Comment by ricardd** [comment]
Yes, sorry, I had used a LaTeX command instead of the markdown one.
