### ISSUE TITLE
inline citations separated by comma instead of semi-colon

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#35]
I find this strange since the CJFAS style shows citations separated by ";" and not by ",", but my rendered PDF uses ",":

![image](https://user-images.githubusercontent.com/1110182/53341405-db53a580-38e1-11e9-953f-67af71e3a4b0.png)

**Comment by seananderson** [comment]
Put `\bibpunct{(}{)}{;}{a}{}{,}` in the .sty file. Looks like only the tech report has that right now. Apparently people have gotten away with that here for a while then.

**Comment by ricardd** [comment]
Only thing is that the .sty file get overwritten when knit is invoked, so we have to add it to the package itself.

And why does it use a comma when CJFAS papers have semi-colons?

**Comment by seananderson** [comment]
Oh right, we are using .csl here for the citations. Not sure. Would have to dig through the .csl and do some googling.

**Comment by ricardd** [comment]
So, to confirm, adding \bibpunct{(}{)}{;}{a}{}{,} to the .sty file doesn't do the trick.

**Comment by ricardd** [comment]
I really can't figure out why commas appear instead of semi-colons. 

Using CJFAS style and adding two references yields the right formatting here:

http://editor.citationstyles.org/visualEditor/

![image](https://user-images.githubusercontent.com/1110182/53357494-680f5b00-3904-11e9-8c43-9d8a043222e7.png)

**Comment by seananderson** [comment]
See my latest commit referenced above in this issue. I think that fixes it. However, until this is embedded in the package data you will have to update your local .csl to match.

**Comment by ricardd** [comment]
I just compared the CJFAS .csl file from here:
https://github.com/citation-style-language/styles/blob/master/canadian-journal-of-fisheries-and-aquatic-sciences.csl

to the one in csasdown, and line 199 defined a comma separator instead of a semi-colon, so I fixed that, see pull request #37.
