### ISSUE TITLE
can the References appear before the Appendices?

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#36]
CSAS asks for the References to appear between the Figures and the Appendices. Is this possible in csasdown? I tried moving References.Rmd in _bookdown.yml but it doesn't work.

I recall that this is the way bookdown does it, but just wondering if we could find a way around it.

**Comment by seananderson** [comment]
Not hard to move the LaTeX bibliography around in the .tex or .sty files but then you'd have to set up multiple bibliographies for the appendices in TeX. If you're willing to take that on then feel free. My understanding is that CSAS is also fine with a single bibliography at the end for everything. We've published some that way.

**Comment by seananderson** [comment]
On second thought I don't think this is possible while still using .csl. For it to happen we would have to switch over to BibTeX and natbib, which I'm sure is possible but would take some time to figure out. Since we seem to be able to get away with having a single bibliography at the end I don't think I'll spend time figuring this out unless CSAS forces us to.

**Comment by ricardd** [comment]
Well, CSAS is now asking me to put the References before the Tables and Figures.

@seananderson maybe if we are implementing this, it would also be good to have a separate list of References for the Appendices? I did this last year for my witch flounder ResDoc, I had References for the main document, and then one for each Appendix.

http://www.dfo-mpo.gc.ca/csas-sccs/Publications/ResDocs-DocRech/2018/2018_023-eng.html

**Comment by seananderson** [comment]
Are you sure this person can't be convinced otherwise? I thought CSAS had told us at one point that it was fine to have them at the end. @cgrandin do you remember?

As far as I know there is no way to have multiple reference sections with Pandoc and .csl-based references (formally called `pandoc-citeproc`). We could do something with BibTeX and natbib and sectionbib or chapterbib, but that would take some engineering with bookdown and it would not be compatible with Word output.

We could probably get the references before the tables and figures as long as it's OK for the appendix references to also appear in this one location with a trick something like this https://community.rstudio.com/t/change-location-of-bibliography-in-bookdown-latex/16928

**Comment by ricardd** [comment]
@seananderson, thanks for another excellent solution, just moving the entire bibliography to before the figures is fine for now. I will test this tomorrow morning.

**Comment by seananderson** [comment]
I'm fixing this right now. After talking about it with @cgrandin we think the easiest solution is with a bit of grepping and a regular expression https://xkcd.com/208/

**Comment by ricardd** [comment]
I had to reimburse the dal library for a book that I later found in RAM's office and that is now mine, Mastering Regular Expressions, indeed provides super powers

**Comment by seananderson** [comment]
See the last two commits that reference this issue. Hopefully that does it.

The syntax is to add:

```
\bibliography
```

wherever you want the bibliography to appear. If you don't include that then the bibliography will end up at the end.

I suppose as an alternative we could automatically put them before the appendices but this allows some flexibility with respect to whether you are grouping your figures and tables at the end. In that case it sounds like the bibliography should come before the group of figures and tables.

**Comment by ricardd** [comment]
I updated the package and added \bibliography just after the acknowledgements, but not getting the expected results:

![Capture](https://user-images.githubusercontent.com/1110182/57072021-a2092e80-6cb2-11e9-8e7c-bc9e30bed4d9.PNG)

**Comment by seananderson** [comment]
Does the built in demo/unit test work for you? You still need to have a references header at the end of the markdown as in the template files.

**Comment by ricardd** [comment]
The demo that I just ran (from csasdown::draft("resdoc")) has the references at the end.

When I add \bibliography to the top of 03-chap3.Rmd, the same as above happens.

What am I missing here? How did you get it to work in the demo?

**Comment by seananderson** [comment]
Other than not actually having the package installed (load_all won’t work) I don’t know. The demo res doc works for me. You’d have to browser() or otherwise debug into fix_envs before the references_insertion_line grep and check the grepping. In order to browse you’ll need to render from the console not from the RStudio button. 

I think I’ll simplify it so that the markdown references header is used for the search (instead of having it at the end and then moving it), but the concept will be be same.

**Comment by ricardd** [comment]
when you say that the demo works for you, what did you change to the base draft to move the bibliography before the tables?

**Comment by seananderson** [comment]
Nothing, the change is already embedded in the demo:
https://github.com/pbs-assess/csasdown/blob/master/inst/rmarkdown/templates/resdoc/skeleton/03-chap3.Rmd#L95

A quick way to run the demo is to open up the unit test file and run it down to the first rendering of the PDF.

**Comment by ricardd** [comment]
I just tried to Check the package in RStudio and I do get an error on the unit test.

```
"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS sr.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output sr.tex --table-of-contents --toc-depth 2 --template "C:\Users\RicardD\AppData\Local\Temp\1\RtmpWmqFb5\RLIBS_2ff9064832c34\csasdown\csas-tex\sr.tex" --number-sections --highlight-style tango --latex-engine pdflatex --top-level-division=chapter --wrap=none --variable tables=yes --standalone --filter pandoc-citeproc 
-- 1. Error: (unknown) (@tests.R#123)  ------------
Failed to compile sr.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See sr.log for more info.
1: expect_warning({
       bookdown::render_book("index.Rmd", csasdown::sr_pdf(), 
           envir = globalenv())
   }) at testthat/tests.R:123
2: quasi_capture(enquo(object), label, capture_warnings)
3: .capture(act$val <- eval_bare(get_expr(.quo), get_env(.quo)), 
       ...)
4: withCallingHandlers(code, warning = function(condition) {
       out$push(condition)
       invokeRestart("muffleWarning")
   })
5: eval_bare(get_expr(.quo), get_env(.quo))
6: bookdown::render_book("index.Rmd", csasdown::sr_pdf(), 
       envir = globalenv()) at testthat/tests.R:124
7: render_cur_session(files, main, config, output_format, 
       clean, envir, ...)
8: rmarkdown::render(main, output_format, ..., clean = clean, 
       envir = envir, encoding = "UTF-8")
9: output_format$post_processor(yaml_front_matter, utf8_input, 
       output_file, clean, !quiet)
10: tinytex::latexmk(f, config$pandoc$latex_engine, if ("--biblatex" %in% 
       config$pandoc$args) "biber" else "bibtex")
11: latexmk_emu(file, engine, bib_engine, engine_args, max_times, 
       install_packages, clean)
12: run_engine()
13: system2_quiet(engine, c("-halt-on-error", "-interaction=batchmode", 
       engine_args, shQuote(file)), error = on_error(), 
       fail_rerun = getOption("tinytex.verbose", FALSE))
14: on_error()
15: show_latex_error(file, logfile)
16: stop(e, " See ", logfile, " for more info.", call. = FALSE)

== testthat results  ==============================
OK: 8 SKIPPED: 0 WARNINGS: 0 FAILED: 1
1. Error: (unknown) (@tests.R#123) 

Error: testthat unit tests failed
Execution halted

1 error x | 0 warnings v | 1 note x
Error: R CMD check found ERRORs
Execution halted

Exited with status 1.
```

but this is seemingly related to the Science Response test

**Comment by seananderson** [comment]
You're getting an error on the science response. That probably has something to do with your local TeX installation. Chris is currently working on the science response and might have added a TeX package. The unit tests are running on my machine and on Travis. Are you using tinytex? If not, you may need to manually install a TeX package. Otherwise you will need to run this outside of the unit test environment so that you can look at the TeX error.

**Comment by seananderson** [comment]
I just simplified things. Now wherever you have the `# REFERENCES {-}` line, the `fix_envs` function will place the references after that. The mechanism is still the same though, so I'm not sure this will fix whatever the problem was above. I've updated the included template demo. You no longer need all the TeX code after that header.

**Comment by ricardd** [comment]
Still using MikTeX, for the science response error, here is what pdflatex spits out:

```
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.144 \MakeAvailable
                    
? 
```

**Comment by seananderson** [comment]
That's one of the new commands in the Science Response .sty file that Chris has been working on. I'm not sure what to say other than it's a different issue that we should deal with later in another issue. I don't think there are any new TeX packages in the SR after looking at the commit history. It seems to build and unit test for me, @cgrandin, and Travis. Just don't run the entire unit test for now. To test the research document you only need to run the top bit.

**Comment by ricardd** [comment]
What is the -1 at the end of line 234 in utils.R for? 

I think that it wreaks havoc for me since the new code chunk in resdoc.tex for the references has an extra unrelated line (\end{longtable}):

```
\chapter*{REFERENCES}\label{references}
\addcontentsline{toc}{chapter}{REFERENCES}
% This manually sets the header for this unnumbered chapter.
\markboth{References}{References}
\noindent
\vspace{-2em}
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\end{longtable}
\hypertarget{refs}{}
```

**Comment by seananderson** [comment]
I just removed it. It was in there from before when you needed to go up a line and it didn't make a difference for me in that last commit when I simplified it because the template has a blank line above that. Didn't realize it wouldn't always be blank.

**Comment by ricardd** [comment]
I removed the -1 and rebuilt the package, and can now knit the document without errors.

One thing however, in the PDF navigation pane hierarchy, the References now appears as the section where Tables and Figures are located. Perhaps we should define References as a numbered section too?

**Comment by seananderson** [comment]
My understanding is that the references are not allowed to be numbered. If that's not the case then yes I'd be happy for them to be a numbered section.

Can you post a screenshot or describe this more? I'm not sure I follow this " the References now appears as the section where Tables and Figures are located"

**Comment by seananderson** [comment]
Mine appear OK from the demo

![image](https://user-images.githubusercontent.com/19349/57093742-8bb79e80-6cc3-11e9-9993-a3c97cd12678.png)

**Comment by ricardd** [comment]
![Capture](https://user-images.githubusercontent.com/1110182/57093857-5623ad00-6ce5-11e9-8716-29b5400b97ed.PNG)

**Comment by seananderson** [comment]
Something is going wrong with the .tex. Can you look at that and see if there's anything relevant and/or try to create the problem with the minimal working example?  Maybe one section is ending before another begins? I did just push a small fix where an extra line space was needed in the demo but I don't think that would make a difference here.

**Comment by seananderson** [comment]
You could try making it a numbered section as part of troubleshooting. If you do that, you will need to change the regular expression since it currently searches for the starred version of chapter: `grep("^\\\\chapter\\*\\{REFERENCES\\}", x) + 1`

**Comment by ricardd** [comment]
I changed to a numbered section (# REFERENCES) and changed the regexp to 'grep("^\\\\chapter\\{REFERENCES\\}", x) + 1'

The References section appears at the right place:

![Capture](https://user-images.githubusercontent.com/1110182/57095562-9dac3800-6ce9-11e9-992f-f1aafe41432d.PNG)

But the actual references are not there:

![Capture](https://user-images.githubusercontent.com/1110182/57095639-c16f7e00-6ce9-11e9-825f-b25046451ea6.PNG)

they are at the end of the document

![Capture](https://user-images.githubusercontent.com/1110182/57095694-db10c580-6ce9-11e9-9831-cd2ba5abab04.PNG)

**Comment by ricardd** [comment]
In the resdoc.tex file, References appears as a chapter, whereas the other sections are defined as section.

**Comment by ricardd** [comment]
Changing the References from a chapter to a section in the resdoc.tex file does the trick:

```
\section*{REFERENCES}\label{references}
\addcontentsline{toc}{section}{REFERENCES}
```

![Capture](https://user-images.githubusercontent.com/1110182/57096968-d994cc80-6cec-11e9-80b2-76c022d5e022.PNG)

**Comment by ricardd** [comment]
So how does the References become a chapter and all others are sections, even if both are defined as H1 (#) in the .Rmd files?

**Comment by seananderson** [comment]
That’s because the word chapter gets switched to section. 

Which also makes me wonder if that’s what caused the issue in the previous unnumbered case for your PDF index. 

Try now with the {-} notation.

**Comment by seananderson** [comment]
Look above in fix envs. Bookdown gives us chapters. We switch them to sections. The * version means the regex doesn’t match above. Try the latest version.

**Comment by ricardd** [comment]
@seananderson your last commit does the trick. As always, thank you.

One minor thing, the hyperlink to the References in the navigation pane doesn't work.

**Comment by seananderson** [comment]
Good. The link has never worked. Something with the hyper target link syntax for unnumbered sections. We’ve been ignoring it but if you have ideas go for it.

**Comment by ricardd** [comment]
OK, happy with this, closing the issue.

**Comment by seananderson** [comment]
Fixed the link to the references! Just needed a "phantom section". https://github.com/pbs-assess/csasdown/commit/be6b88acbe896a1c1ad72da88e2ebb50d4737896

**Comment by ricardd** [comment]
awesome!

**Comment by ricardd** [comment]
Maybe I closed this too early, we also have to implement the same when the section is called RÉFÉRENCES in the French document. 

I guess that the code could be modified to use the YAML "french" parameter to do this?

**Comment by seananderson** [comment]
Yes and there’s already a French logical argument to the fix envs function being passed. Just deal with the logical if else part inside the function and it should work.

**Comment by ricardd** [comment]
I did the required changes, rebuilt on my end and rendered my French PDF, which looks fine. 

But Travis CI shows 2 errors, so I just asked for a review from you @seananderson
