### ISSUE TITLE
accented characters not rendering correctly in csas_table

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#39]
I am reading in a UTF8-encoded csv file and using it with csas_table to produce a table. The accented characters in the table header, passed as "col.names" to csas_table render correctly, but in the  table itself there is a problem with the accented characters:

![Capture](https://user-images.githubusercontent.com/1110182/55096258-50a8c680-5098-11e9-9077-31a31fa0c23b.PNG)

How can this be?

**Comment by ricardd** [comment]
This is a Windows problem that has to do with the default character encoding being Microsoft 1252 when RStudio is running. It has nothing to do with csasdown.

On my GoC laptop, I noticed that the same R file ran in RStudio would give correct accented characters in figures but would not render them correctly when the same file was sourced. My solution to this was to add an explicit encoding="UTF-8" argument to source().

I will nonetheless keep this issue open until I resolve it and will post the solution here. I tried to set the default encoding in R to UTF-8 but the OS doesn't let me:

```
> Sys.getlocale()
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
> Sys.setlocale("LC_ALL", 'en_US.UTF-8')
[1] ""
Warning message:
In Sys.setlocale("LC_ALL", "en_US.UTF-8") :
  OS reports request to set locale to "en_US.UTF-8" cannot be honored
```

In RStudio, I also changed Tools-Global Options-Code-Saving-Default text encoding to UTF-8, but Sys.getlocale() still says that the encoding is 1252.

**Comment by seananderson** [comment]
Best resource I know on character encoding in R: http://stat545.com/block028_character-data.html#character-encoding

Also: https://community.rstudio.com/t/character-encoding-within-the-tidyverse/4531/3

If you figure out a solution then maybe add it to the wiki.

**Comment by ricardd** [comment]
@seananderson , I will indeed contribute to the wiki.

Best summary of this that I read today: "Encodings are one of 21st century's worse headaches."

https://stackoverflow.com/questions/29379771/utf-8-encoding-problems-with-r

**Comment by ricardd** [comment]
in the above example, the tables were generated from a CSV file that was read in and used by csas_table

despite the fact that I had set the default encoding to UTF-8 in RStudio, the rendered table had erroneous accented characters, so I fixed the issue by explicitly specifying the encoding on the read.csv invocation. In other words, I changed this:

```
appland2018 <- read.csv("data/appland2018.csv")
```
into this:
```
appland2018 <- read.csv("data/appland2018.csv", encoding="UTF-8")
```

**Comment by seananderson** [comment]
Another reason to use `readr::read_csv()`, which has UTF-8 as the default, I believe.

**Comment by ricardd** [comment]
yes, tidyverse prophet
