### ISSUE TITLE
cross-referencing in figure and table captions

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#40]
Not a csasdown issue per se, but how can one use a cross-reference in a figure or table caption? 

I have a number of captions that refer to other figures or tables, but I can't figure out how to get the cross-referencing to work. I am unclear where the process fails, is knitr or bookdown responsible?

What I thought would work:
```
{r figRVnumersatage, fig.cap="Indices of relative abundance (numbers per tow at age) for Atlantic Cod from the southern Gulf of St. Lawrence September trawl survey, 1971-2018. Circle area is proportional to catch rate at age. Results for ages 0 and 1 were excluded because they may include Greenland Cod (See Table \\@ref(tab:tabRVcaa) caption)."}
knitr::include_graphics("figure/RV-cod-relative-abundance-at-age-to-2018-EN.png")
```

but doesn't:

![Capture](https://user-images.githubusercontent.com/1110182/55103569-7db0a580-50a7-11e9-8a42-8f057cc9883a.PNG)

My inelegant hard-wired solution is to write the table number directly:
```
{r figRVnumersatage, fig.cap="Indices of relative abundance (numbers per tow at age) for Atlantic Cod from the southern Gulf of St. Lawrence September trawl survey, 1971-2018. Circle area is proportional to catch rate at age. Results for ages 0 and 1 were excluded because they may include Greenland Cod (See Table 5 caption)."}
knitr::include_graphics("figure/RV-cod-relative-abundance-at-age-to-2018-EN.png")
```
```

**Comment by seananderson** [comment]
It's a knitr thing: https://github.com/pbs-assess/csasdown/wiki

**Comment by ricardd** [comment]
Thank you @seananderson for the pointer, this works beautifully now.
