### ISSUE TITLE
Fix the spacing in lists

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#45]
See a recent research document. I think it needs to have more space between the elements.

**Comment by cgrandin** [comment]
I don't think this can be done easily

**Comment by seananderson** [comment]
See this commit: https://github.com/pbs-assess/csasdown/commit/713edd152443a37de90fc0c4e0907ae46975a25f

Need to remove the `\tightlist` that Pandoc adds. Not sure that works for sub bullets, but I'm OK with that for now.

**Comment by cgrandin** [comment]
Works as of 16fe06a7599497b1f9901c861b6dfe85ee1cc1b2
