### ISSUE TITLE
How to get "APPENDIX A" to show as "ANNEXE A" in French ResDoc?

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#48]
I modified the beginning of Appendices.Rmd to this:

```
<!-- The following code should appear at the beginning of the first appendix.
After that, all subsequent sections will be turned into appendices. -->

`r if(knitr:::is_latex_output()) '\\Appendices'`

`r if(!knitr:::is_latex_output()) '# (ANNEXE) Annexe {-}'`
```

but the rendered PDF still shows the section as "APPENDIX A". I am looking at res-doc-french.sty and unsure where this is controlled.

**Comment by seananderson** [comment]
What you modified affects the .docx output. You’ll need to fix things in utils.R on the line: `\\\\starredchapter\\{APPENDIX~\\\\thechapter. ", x[i])`.

**Comment by ricardd** [comment]
Could utils.R be setup so as to know what to use based on french: true? Or is this currently just working for ResDocs?

**Comment by seananderson** [comment]
It can be done. The French option just needs to be passed from resdoc_pdf through to fix_envs and the appropriate if-else added to that line. I can do this later.

**Comment by ricardd** [comment]
@seananderson this is probably not too high on your list, so maybe I should give it a shot?

**Comment by seananderson** [comment]
Try now. I'll need this to work soon for the synopsis report anyways.

**Comment by ricardd** [comment]
works like a charm! thanks @seananderson
