### ISSUE TITLE
SR - page 2 is not numbered

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/csasdowntex#56]
This came as a result of fixing issue #55 with commit 9d63cb08338a4613145f762931303fa9c715b32d

Page 2 is not numbered for some reason. I've tried adding an extra `\afterpage{\cfoot{\thepage}}` in several places both in and out of the `\MakeFirstPage` and `firstPage` style section but no dice. Adding a `\clearpage` will solve it but introduce a whole empty page so that is not a viable solution as the document is meant to flow.

**Comment by obradovichs** [comment]
Page 3 is also not numbered for the tech report (i.e should be page i)

**Comment by cgrandin** [comment]
Fixed for SR only in 43e5da1260ad4c724f721f34caf7ceeed996d73b. Tech reports still need fixing. The tech report style files have a different structure than the other two doc types making it a different fix for them.

**Comment by cgrandin** [comment]
Tech reports are fine. I just built both English and French and all pages are numbered except for the first one.
