### ISSUE TITLE
Imported image (*png) not rendering in correct location in csasdown res doc

### ISSUE THREAD

**Issue by obradovichs** [pbs-assess/csasdowntex#60]
When an image file is called in the RMarkdown file ( e.g.  ![](knitr-figs-pdf/figname.png)  ), the formatting in the rendered document is problematic (there are excessive upper and left margins). The image is also produced several paragraphs after the actual figure call. These problems do not occur when figures/images are generated within the RMarkdown script, for example: 

```{r sexualdimorphismplot, echo=FALSE,warning=FALSE, fig.height=3, fig.width=6, fig.cap="Length-weight relationship of dioecious Northern Abalone in British Columbia, based on data from Quayle (1971)."}
ggplot(QS) + geom_point(aes(TD, Total.Weight,colour=Sex),alpha=0.7) + theme_classic() + scale_colour_manual(values=c("#006600", "#FFCC99"), labels=c("Female","Male")) + scale_x_continuous(name="Shell Length (mm)") + scale_y_continuous(name="Total Weight (g)")
```

How can we ensure that images inserted into the RMarkdown file render in the correct location and with the correct formatting?

**Comment by seananderson** [comment]
Can you post a screenshot?

**Comment by obradovichs** [comment]
[examplefigure.pdf](https://github.com/pbs-assess/csasdown/files/3175319/examplefigure.pdf)
The blue box was added to the screen shot afterwards.

**Comment by cgrandin** [comment]
Better yet @obradovichs, if you make your project a GitHub repository and push all your changes, we will be able to run the code directly and reproduce. It's hard to tell from this..

**Comment by seananderson** [comment]
Seeing the complete code would be most helpful.

Assuming you are generating that plot in the .Rmd in a code chunk, then your main options to tweak the formatting are

```
fig.asp = 0.618,
fig.width = 9,
out.width = "6in"
```

(those are the defaults in csasdown)

If you actually mean importing an already existing .png then the answer might be different.

**Comment by seananderson** [comment]
`out.width` is what controls the output within the PDF.

The exact positioning is determined by LaTeX to float the figure where it seems best based on the other text and figure elements and typographical rules. There are ways to gain some control over that but in general you are probably best off letting it do its thing. `fig.pos` is the main option.

https://yihui.name/knitr/options/

**Comment by obradovichs** [comment]
It is importing an existing png because not all co-authors use R and Git. The project is a private repository. I could add you as collaborators? Or is there another option?

**Comment by seananderson** [comment]
See an example here: https://github.com/pbs-assess/gfsynopsis/blob/d4d4fbd70fd9878f1bd08aa605baf5106603d950/report/report-rmd/01-intro.Rmd#L184

Yes, you could add us as “collaborators” and then we could see the code. That would be the best way. Hopefully the example above helps. We should include something like that in the example template.

**Comment by schansen** [comment]
Thanks for the advice! Adding `{width=100%}` immediately after the image call worked in our RMarkdown file. E.g. 
` ![](knitr-figs-pdf/WCHGtest.png){width=100%}`

And the following (from the example posted above) gave even more control :): 

> {r insert-fig-test, echo=FALSE, out.width="100%", fig.pos="tb"} 
> knitr::include_graphics(here::here("knitr-figs-pdf/WCHGtest.png"))
