### ISSUE TITLE
Landscape Orientation in Tech Report

### ISSUE THREAD

**Issue by ErikaDAnderson** [pbs-assess/csasdowntex#61]
I am trying to add a landscape page function to handle a wide table in the tech-report.sty file in csas-down. After reading through issue #31 ,  I copied the landscapepage function from the res-doc.sty file:

%% Make a landscape page properly, with the page numbers and bars rotated to
%%  be along the long side for ease of reading in a PDF viewer.
\newenvironment{landscapepage}[1]{
  \newgeometry{hmargin=1in,vmargin=1in}
  \thispagestyle{csaplscape}
  \begin{landscape}
    \centering
    #1
}{
  \end{landscape}
  \restoregeometry
  \clearpage
}

\makeatother
%% ------------------------------------------------------------------------------

%% ------------------------------------------------------------------------------
%% For landscape pages in CSAS documents
% \usepackage{pdflscape}
\usepackage{lscape}
\usepackage[absolute]{textpos}
\setlength{\TPHorizModule}
  {8.5in}
\setlength{\TPVertModule}
  {11.0in}
\fancypagestyle{csaplscape}{
  %% The argument is the left footer text
  %% clear all header and footer fields
  \fancyhf{}
  \fancyfoot{}
  %% Make the footers appear in landscape mode
  %% The 25pt in the first line adjusts the height (in landscape mode)
  %%  and the 90 rotates the footer name. The \footskip+0.0 makes it align
  %%  with the footer bar, like the pages in portrait mode do.
  %% Left footer:
  %% \fancyfoot[L]{\makebox[\textwidth+25pt][r]{
  %%    \smash{\raisebox{\dimexpr\footskip+0.0\textheight}{\rotatebox{90}{\fishname}}}}}
  %% Right footer - uncomment and change DRAFT to whatever the value for the right
  %%  footer is and the 1.3 to fit it. This is a hack, no time to figure it out.
  %% \fancyfoot[R]{\makebox[\textwidth+25pt][r]{
  %%    \smash{\raisebox{\dimexpr\footskip+1.3\textheight}{\rotatebox{90}{DRAFT}}}}}
  \begin{textblock}
    {1}(0.1,0.0909)
    {\rotatebox{90}
      {\rule{9in}{0.25pt}}
    }
  \end{textblock}
  \begin{textblock}
    {1}(0.9,0.0909)
    {\rotatebox{90}
      {\rule{9in}{0.25pt}}
    }
  \end{textblock}
  \begin{textblock}
    {0.05}(0.925,0.5)
    {\rotatebox{90}
      {\thepage}
    }
  \end{textblock}
  %% Get rid of lines along sides of landscape page
  \renewcommand{\headrulewidth}
    {0pt}
  \renewcommand{\footrulewidth}
    {0pt}
}
%% ------------------------------------------------------------------------------
Then I added 
\begin{landscapepage}
\end{landscapepage}
around my code chunk with a table.

When I knit, the changes that I saved in the tech-report.sty file disappear and I get the following error: 
! LaTeX Error: Environment landscapepage undefined.
What am I missing?
Thanks!

**Comment by seananderson** [comment]
Does the example at the end of that issue work for you?

No other changes should be needed. Nothing with lscape or anything else.

If we do need to update the .sty file then we do it in the package since it gets overwritten each time.

You may not need the part about the font size. The important bit is just the ` kableExtra::landscape()`

```
    ```{r longwide, results="asis"}
    yrs <- 1:45
    ages <- 1:15
    wide.and.long <- matrix(round(rnorm(length(yrs)*length(ages), 20),4), nr=length(yrs),             nc=length(ages), 
    dimnames=list(year=yrs, age=ages))
    w.l.df <- data.frame(cbind(yrs, wide.and.long))
    
    csasdown::csas_table(
      w.l.df,
      col.names = c("Year", as.character(ages)),
      caption = "A long and wide table",
      format = "latex"
      ) %>% 
      kableExtra::landscape() %>% 
      kableExtra::kable_styling(font_size = 8, latex_options = "repeat_header", 
         repeat_header_text = "", repeat_header_method = "replace") %>% 
      sub("\\caption\\[\\]\\{\\}", "\\caption*{}", .)
    ```
```

**Comment by ErikaDAnderson** [comment]
1. I tried piping the kableExtra::landscape onto my existing wide table:

```{r bridge, results='asis'}

# write table
csasdown::csas_table(
  bridgedf,
  caption = paste0("Bridge log information for trawl tows from the ",surveyYear, " Integrated Ecosystem Pelagic Survey aboard the MV ", vessel, ", ", surveyStart, " to ", surveyEnd, ". Beaufort Scale code for sea state definitions are provided in Appendix B."),
  format = "latex") %>%
  kableExtra::kable_styling(font_size = 8, latex_options = "repeat_header",
     repeat_header_text = "Continued.", repeat_header_method = "replace") %>%
  kableExtra::landscape()

```
The rendering fails with the kableExtra::landscape  line with the following error:
! LaTeX Error: Environment landscape undefined.

My table is long and wide and the R documentation for landscape() says it will only work for a **single** landscape page.: "This function will put the table on an single landscape page. It's useful for wide tables that can't be printed on a portrait page." 

2. I copied the above R code exactly and ran it within my tech report. The file knitted, but the table was not in landscape, and it was still in latex in the pdf file:

![image](https://user-images.githubusercontent.com/39602850/59045927-cfa74180-8835-11e9-825f-54cd6e658fb7.png)

Apparently, I have two related issues: landscape orientation and breaking a table across pages. Any suggestions would be appreciated, I have several long and wide tables that need to be incorporated in the appendix.
Thanks for your time!

**Comment by seananderson** [comment]
Probably needs the landscape LaTeX package to be added to the template. I’ll fix the style file and get an example in there. You can have the landscape tables on multiple pages.

**Comment by cgrandin** [comment]
This works as of b7e01c4957. There is a problem with the table possibly being to wide and overlapping the header and footer lines, but we can fix that if necessary. Try this and let us know if it is ok! Here is some example code to include in your Rmd file:
 
```{r widelong, results = "asis"}
yrs <- 1:45
ages <- 1:15
widelong <- matrix(round(rnorm(length(yrs) * length(ages), 20), 4),
                        nr = length(yrs),
                        nc = length(ages),
                   dimnames = list(year = yrs, age = ages))
widelong_df <- data.frame(cbind(yrs, widelong))
# In landscape tables, you can change the font size if the table
# is too large and overlaps the header and footer lines.
csasdown::csas_table(widelong_df,
                     col.names = c("Year", as.character(ages)),
                     caption = "A long and wide table",
                     format = "latex",
                     landscape = TRUE,
                     font_size = 8)
```

**Comment by ErikaDAnderson** [comment]
Your example code works with the update in my tech report, although you are correct that the header will cause issues:
![image](https://user-images.githubusercontent.com/39602850/59062692-4efb3c00-885b-11e9-9336-a14b47450654.png)

I tried the new function on my bridge log table. The first page was missing headings, but subsequent tables had the column names:
![image](https://user-images.githubusercontent.com/39602850/59062801-8e298d00-885b-11e9-9759-3d150731563c.png)

![image](https://user-images.githubusercontent.com/39602850/59062848-a4cfe400-885b-11e9-8204-2ba113236b68.png)

So I tried  adding column names using the col.names option in csas-table. But the headings are still missing from the first page of the table.
![image](https://user-images.githubusercontent.com/39602850/59063310-a8b03600-885c-11e9-9cf5-661df7514eeb.png)
Thanks!

**Comment by cgrandin** [comment]
Can you make a repository that I can clone? Then I can look at your code directly and test. Thanks

**Comment by cgrandin** [comment]
I think you're going to need to shorten those column names as well, they are making the table way too wide!

**Comment by ErikaDAnderson** [comment]
Yes - my column names need shortening.

My code is on a private repository with a database that you can't access, so I made a dummy repository to reproduce the issue
https://github.com/ErikaDAnderson/TechReportHelp

As usual, in reproducing the issue, I found the cause:
```r 
  kableExtra::kable_styling(latex_options = "repeat_header",
     repeat_header_text = "Continued.", repeat_header_method = "replace")
```

This removes the first page of column names. The intention was to repeat the header name with the word "continued" added. I will remove that code and be happy with it.
 
Will you be fixing the header and footer formatting with a long and wide table or should I close this issue?
Thanks.

**Comment by cgrandin** [comment]
I'll actually change the csas_table function so that you can supply a repeat header text. So I'll leave this open until I do that.

**Comment by ErikaDAnderson** [comment]
Great, I appreciate the software support.

**Comment by seananderson** [comment]
I thought we figured out that the official format is do not have a repeating header, which is why we added this:

```
kableExtra::kable_styling(latex_options = "repeat_header", 
         repeat_header_text = "", repeat_header_method = "replace") %>% 
      sub("\\caption\\[\\]\\{\\}", "\\caption*{}", .)
```

**Comment by cgrandin** [comment]
Done in 024fd8d9fabb98c95b4971febd614004243f8516.
I couldn't push to your helper repo so here is an example of the table you were trying to create
```
csasdown::csas_table(
  widelong_df,
  caption = "A Table with 'Continued..' as a header for second page of table",
  format = "latex",
  landscape = TRUE,
  font_size = 8,
  repeat_header_text = "Continued ..")
```

**Comment by cgrandin** [comment]
@seananderson You are correct, but technical reports are not as strict as the other CSAS docs. The default after these changes remain as it was, to repeat the header.

**Comment by ErikaDAnderson** [comment]
I updated my csasdown and copied @cgrandin example code into my helper repo. The following error was produced:

```{r CG2}
csasdown::csas_table(
  widelong_df,
  caption = "A Table with 'Continued..' as a header for second page of table",
  format = "latex",
  landscape = TRUE,
  font_size = 8,
  repeat_header_text = "Continued ..")
```
Error in kable_latex(x = c("1", "2", "3", "4", "5", "6", "7", "8", "9", : unused argument (repeat_header_text = "Continued ..")

I sent @cgrandin an invitation to my helper repo if you would like to follow up.

**Comment by cgrandin** [comment]
One last addition which I have wanted to do for awhile. 031288d2cc8a0addda2414092d58f9c32fc55151 makes it so you can put newlines into column names. Note new argument col_names_align. Any \n's in the column names will be replaced with the correct latex via kableExtra::linebreak()
```
csasdown::csas_table(widelong_df,
                     col_names = c("Year", paste0("Age\n", ages)),
                     col_names_align = "c",
                     caption = "A long and wide table",
                     format = "latex",
                     landscape = TRUE,
                     font_size = 8,
                     escape = FALSE)
```

**Comment by ErikaDAnderson** [comment]
I love the addition and will use it! 

Any chance that you could add the ability to use kableExtra::col_spec in csasdown::csas-table so I can limit the width of column to force text wrapping? Currently, the R code runs but the latex rendering fails when I try this.

```{r netSpecsLFS, results='asis'}

# create table of net specifications
netLFS <- read_csv("Part, Size, Material
                    Doors, 4 m2, Thyboron Type 15
                    Door Legs, 12.2 m (6.67 fm), 1 inch Spectra rope
                    Bridles, 45.72 m (25 fm), 3/4 inch TS2P Spectra Rope
                    Head Line, 102.83 m (56.2 fm), 5/8 inch coated Spectra Rope
                    Foot Rope, 102.83 (56.2 fm), 9/16 inch coasted Spectra rope with 13 mm chain
                    Mesh incl. Codend, 3.8 cm (1.5 inch), Knotted nylon
                    Codend Liner, 64 mm (0.5 inch), 210/20 knotless liner")

knitr::kable(
  netLFS,   
  booktabs = TRUE,
  format = "latex", 
  caption = paste("Net specifications for the LFS 7742 mid-water Trawl Net used during the", surveyYear, "Integrated Pelagic Ecosystem Survey aboard the M.V.", vessel, surveyStart, "to", surveyEnd, ".", sep = " ")) %>%
  pack_rows("Rigging", 1,3) %>%
  pack_rows("Net Frame", 4,4) %>%
  pack_rows("Foot Rope", 5,5) %>%
  pack_rows("Web", 6,7) %>%
column_spec(column = 3, width_max = "5cm")
```

**Comment by cgrandin** [comment]
@ErikaDAnderson just making sure you pulled the changes and re-installed the package?

**Comment by ErikaDAnderson** [comment]
@cgrandin Repeat headers in csas-table tech report works for me now. I had tried to pull the changes but it failed with:
"due to cannot remove prior installation of package ‘processx’"

I deleted processx and tried again. Now it works as promised.
Thanks again.

**Comment by cgrandin** [comment]
Just change your column_spec call to:
```
column_spec(column = 3, width = "5cm")
```

**Comment by ErikaDAnderson** [comment]
It worked - you are the master of kable.

**Comment by cgrandin** [comment]
I pushed to the helper repo the examples we just went through so with those and this discussion you should be good to go

**Comment by cgrandin** [comment]
Also just fixed one thing in csasdown, so pull again and re-install
