### ISSUE TITLE
formatting footnotes in tables

### ISSUE THREAD

**Issue by schansen** [pbs-assess/csasdowntex#62]
I am trying to include footnotes in cells in a csasdown table. Code & formatting that work when I knit from a simple rmarkdown file do not work when I knit from the index.Rmd file in a csasdown project. 

```
    ---
    output: pdf_document
    header-includes:
        - \usepackage{caption} 
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = FALSE, collapse = TRUE)
    
    require(csasdown)
    require(xlsx)
    require(plyr)
    require(dplyr)
    require(kableExtra)
    require(knitr)
    ```
    
    
    ```{r survey_table_data, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
    AStab[is.na(AStab)] <- ""
    
    AStab$References <- gsub("&","\\\\&",AStab$References)
    
    #Footnote a
    AStab[1,3] <- paste0(AStab[1,3], footnote_marker_alphabet(1,"latex"))
    
    #Footnote b
    AStab[20,4] <- paste0(AStab[20,4], footnote_marker_alphabet(2,"latex"))
    AStab[27,5] <- paste0(AStab[27,5], footnote_marker_alphabet(2,"latex"))
    
    #Footnote c
    AStab[31,8] <- paste0(AStab[31,8], footnote_marker_alphabet(3,"latex"))
    ```
    
    ```{r survey_table, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
    csasdown::csas_table(AStab, format="latex", escape=FALSE, booktabs=TRUE, caption="Northern Abalone Index Sites Surveys conducted in different regions in BC over time. Values     indicate the number of sites surveyed within a given region. 'NS' indicates that no NAISS was conducted in a given year. Footnotes indicate the number of sites after site     exclusion for data analysis.") %>%
      kableExtra::landscape() %>% 
      kableExtra::kable_styling(font_size = 8,latex_options = "repeat_header", 
         repeat_header_text = "", repeat_header_method = "replace") %>% 
      sub("\\caption\\[\\]\\{\\}", "\\caption*{}", .) %>%
      add_header_above(c(" "=2,"Region"=6)) %>%
      footnote(alphabet = c(" 51"," 46"," 39"), threeparttable = TRUE)
    #threeparttable = TRUE allows the footnotes to break across lines at the table width
    ```
    
    ```{r quad_table_data, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
    Qtab[is.na(Qtab)] <- ""
    
    #Footnote a
    Qtab[34,5] <- paste0(Qtab[34,5], footnote_marker_alphabet(1,"latex"))
    Qtab[37,6] <- paste0(Qtab[37,6], footnote_marker_alphabet(1,"latex"))
    
    #Footnote b
    Qtab[7,4] <- paste0(Qtab[7,4], footnote_marker_alphabet(2,"latex"))
    Qtab[13,4] <- paste0(Qtab[13,4], footnote_marker_alphabet(2,"latex"))
    Qtab[25,4] <- paste0(Qtab[25,4], footnote_marker_alphabet(2,"latex"))
    Qtab[3,5] <- paste0(Qtab[3,5], footnote_marker_alphabet(2,"latex"))
    Qtab[24,5] <- paste0(Qtab[24,5], footnote_marker_alphabet(2,"latex"))
    Qtab[27,6] <- paste0(Qtab[27,6], footnote_marker_alphabet(2,"latex"))
    Qtab[32,6] <- paste0(Qtab[32,6], footnote_marker_alphabet(2,"latex"))
    Qtab[32,7] <- paste0(Qtab[32,7], footnote_marker_alphabet(2,"latex"))
    Qtab[31,9] <- paste0(Qtab[31,9], footnote_marker_alphabet(2,"latex"))
    
    #Footnote c
    Qtab[16,5] <- paste0(Qtab[16,5], footnote_marker_alphabet(3,"latex"))
    
    #Footnote d
    Qtab[20,5] <- paste0(Qtab[20,5], footnote_marker_alphabet(4,"latex"))
    
    #Footnote e
    Qtab[17,4] <- paste0(Qtab[17,4], footnote_marker_alphabet(5,"latex"))
    
    #Footnote f
    Qtab[36,8] <- paste0(Qtab[36,8], footnote_marker_alphabet(6,"latex"))
    Qtab[36,9] <- paste0(Qtab[36,9], footnote_marker_alphabet(6,"latex"))
    ```
    
    ```{r quad_table, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
    csasdown::csas_table(Qtab, format="latex", escape=FALSE, booktabs=TRUE, caption="Summary of methodological changes in the number of quadrats surveyed. Survey indicates whether  a    Northern Abalone Index Site Survey was conducted in a given year (Y) or not (N). Zeros identify the number of surveys in which no abalone were encountered in the first 8  quadrats.    Numbers listed under each regional heading indicate the targetted total number of quadrats to be surveyed when the first eight encountered no abalone (according to  the survey    plan).") %>%
      kableExtra::kable_styling(font_size = 8,latex_options = "repeat_header", 
         repeat_header_text = "", repeat_header_method = "replace") %>% 
      sub("\\caption\\[\\]\\{\\}", "\\caption*{}", .) %>%
      add_header_above(c(" "=3,"Region"=6)) %>%
      footnote(alphabet = c("8 quadrats also identified in the data", "16 quadrats also identified in the data", "24 quadrats also identified in the data", "32 quadrats also     identified in the data","Quadrat counts in the data were all >= 32","Survey plan consisted of priority levels assigned to sites (if no abalone were found in the first 8     quadrats, surveying was stopped in low priority sites but continued in high priority sites)"), threeparttable = TRUE)
    
    ```
```
Produces the following: 
![image](https://user-images.githubusercontent.com/45637443/59455418-01d21980-8dc9-11e9-91fb-19a4fb45b5ea.png)
![image](https://user-images.githubusercontent.com/45637443/59455441-0bf41800-8dc9-11e9-9d94-79a2eefe4969.png)

But when I knit it from an index.Rmd file, it produces errors such as: 
! LaTeX Error: Environment TableNotes undefined.
! LaTeX Error: Environment threeparttable undefined.

! Misplaced \noalign.
\toprule ->\noalign 
                    {\ifnum 0=`}\fi \@aboverulesep =\abovetopsep \global \@b...
l.212 ...data analysis.\}\textbackslash{} \toprule
                                                   \multicolumn{2}{c}{ } \& ...

I have tried removing `threeparttable = TRUE`, but it prevents the footnotes from breaking across multiple lines so that they run off the edge of the page (it also ends up changing the column widths). 

Any advice?

**Comment by seananderson** [comment]
@cgrandin, I'm wondering if the `header-includes:` part is not getting passed into the .tex preamble. I assume we might have to do something special for that to happen and we haven't done anything special. We might be able to pass it through or we might just want to add the package.

**Comment by cgrandin** [comment]
@schansen, do you have an example which I can knit standalone to debug ? (above code is missing Astab object )

Thanks

**Comment by schansen** [comment]
@cgrandin, I've attached an excel file with AStab and Qtab in different sheets. The content of Qtab has changed slightly, but I'm still having the same issues. Thanks

[TableFootnoteTest.xlsx](https://github.com/pbs-assess/csasdown/files/3330978/TableFootnoteTest.xlsx)

**Comment by cgrandin** [comment]
Can you include the code you're using to import them into R objects ? Thanks

**Comment by schansen** [comment]
AStab <- read.xlsx("TableFootnoteTest.xlsx", sheetIndex=1, stringsAsFactors=FALSE)

Qtab <- read.xlsx("TableFootnoteTest.xlsx", sheetIndex=2, stringsAsFactors=FALSE)

**Comment by cgrandin** [comment]
Ok, this works now. You will need to use this `header-includes` statement:

```
header-includes:
  - \usepackage{threeparttablex}
```
And note that csas_table now has landscape and other things, so the code is simplified:
```r
  csasdown::csas_table(AStab,
                       format = "latex",
                       landscape = TRUE,
                       caption = caption="Summary of methodological changes in the number of quadrats surveyed. Survey indicates whether  a    Northern Abalone Index Site Survey was conducted in a given year (Y) or not (N). Zeros identify the number of surveys in which no abalone were encountered in the first 8  quadrats.    Numbers listed under each regional heading indicate the targetted total number of quadrats to be surveyed when the first eight encountered no abalone (according to  the survey plan).") %>% 
  footnote(alphabet = c("8 quadrats also identified in the data", "16 quadrats also identified in the data", "24 quadrats also identified in the data", "32 quadrats also identified in the data","Quadrat counts in the data were all >= 32","Survey plan consisted of priority levels assigned to sites (if no abalone were found in the first 8 quadrats, surveying was stopped in low priority sites but continued in high priority sites)"), threeparttable = TRUE)
```
For future note (everybody) - if you want to include more than one package you will have to have them on the same line like this:

```
header-includes:
  - \usepackage{threeparttablex} \usepackage{caption}
```

This will NOT work, only the first one is added:

```
header-includes:
  - \usepackage{threeparttablex}
  - \usepackage{caption}

```

**Comment by schansen** [comment]
@cgrandin I've pulled the changes to csasdown and added 
`- \usepackage{threeparttablex} \usepackage{caption}` to the YAML header in the index.Rmd file, but I am still getting the following error message: `! LaTeX Error: Environment TableNotes undefined.`
Have I missed a step? Do I need to reinstall csasdown or generate a new csasdown project and move my code into it? 
Thanks

**Comment by seananderson** [comment]
You will have to install the newest csasdown, but you shouldn't have to generate a new project.

**Comment by schansen** [comment]
I have now installed the latest csasdown. When I try to knit I get the following messages: 
` output file: techreport.knit.md `
` tlmgr search --file --global "/tikzlibrarytopaths.code.tex"`
` tlmgr search --file --global "/tikzlibraryshapes.code.tex"`
` tlmgr search --file --global "/tikzlibrarypositioning.code.tex"`
` tlmgr search --file --global "/tikzlibrarybackgrounds.code.tex"`
` Trying to automatically install missing LaTeX packages...
tlmgr install pgf
tlmgr.pl: package repository http://ctan.mirror.colo-serv.net/systems/texlive/tlnet (not verified: gpg unavailable) 
tlmgr.pl install: package already present: pgf `
` tlmgr search --file --global "/tikzlibrarytopaths.code.tex"`
` tlmgr search --file --global "/tikzlibraryshapes.code.tex"`
` tlmgr search --file --global "/tikzlibrarypositioning.code.tex"`
` tlmgr search --file --global "/tikzlibrarybackgrounds.code.tex"`

`! LaTeX Error: Environment TableNotes undefined. `

` Error: Failed to compile techreport.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See techreport.log for more info.
Execution halted`

**Comment by cgrandin** [comment]
Look in your .tex file that was created and make sure that `\usepackage{threeparttablex}` is in there. If it is, you may have to re-install tinytex. I have had to do this on occasion due to it not loading new packages properly.

**Comment by obradovichs** [comment]
@schansen @cgrandin 
We have applied all of these fixes and are still unable to knit these tables within csasdown (but they render properly in .rmd).

**Comment by seananderson** [comment]
With regards to the `tikz` messages, I commented those out in the style file earlier today so it shouldn't try to install all those now.

I just tried the following:

```
AStab <- readxl::read_xlsx("TableFootnoteTest.xlsx", sheet = 1)
AStab$References <- gsub("&", "and", AStab$References)

csasdown::csas_table(AStab,
  format = "latex",
  landscape = TRUE,
  caption = "Summary of methodological changes in the number of quadrats surveyed. Survey indicates whether  a    Northern Abalone Index Site Survey was conducted in a given year (Y) or not (N). Zeros identify the number of surveys in which no abalone were encountered in the first 8  quadrats.    Numbers listed under each regional heading indicate the targetted total number of quadrats to be surveyed when the first eight encountered no abalone (according to  the survey plan)."
) %>%
  kableExtra::footnote(alphabet = c("8 quadrats also identified in the data", "16 quadrats also identified in the data", "24 quadrats also identified in the data", "32 quadrats also identified in the data", "Quadrat counts in the data were all >= 32", "Survey plan consisted of priority levels assigned to sites (if no abalone were found in the first 8 quadrats, surveying was stopped in low priority sites but continued in high priority sites)"), threeparttable = TRUE)
```

I placed that after

```
# Introduction

A reference [@edwards2013].
```

in the template introduction and wrapped it in a chunk with `results='asis'` and it compiled for me after installing the appropriate package on-the-fly: `tlmgr search --file --global '/threeparttablex.sty'`

My `index.Rmd` file includes the following:

```
header-includes:
  - \usepackage{threeparttablex}
```

(although adding the caption package after is fine too if it's on the same line)

To be clear, here's a screenshot:

![image](https://user-images.githubusercontent.com/19349/61915736-b304bd00-aefa-11e9-8224-fa9db555c3f1.png)

![image](https://user-images.githubusercontent.com/19349/61915753-c57ef680-aefa-11e9-99a5-4501c29f7f42.png)

The output:
 
![image](https://user-images.githubusercontent.com/19349/61915791-e6474c00-aefa-11e9-8b76-992ddc2a9bad.png)

**Comment by obradovichs** [comment]
I can't seem to even get a simple table to knit when reading in from a csv with csasdown

{r slope, results='asis'}
```
slope <- read.csv("COV_site_level_slope.csv",stringsAsFactors = F)
csasdown::csas_table(slope,format="latex",escape=T,booktabs=T,caption="Test")
```

However, this one is working for us:
{r atab1, echo=FALSE, warning=FALSE, message=FALSE}
```
 csasdown::csas_table(GAM_table(gamNorth.all), format="latex", escape=TRUE, booktabs=TRUE, caption="Best-fitting generalized additive model") %>%
   kableExtra::kable_styling(font_size = 8)

```

**Comment by obradovichs** [comment]
It works! I had to remove some code in the index.Rmd that was creating the alphanumerics for each appendix (e.g. Table A1). Still don't know how to get that working. 

<- \newcommand{\beginsupplementa}{\setcounter{table}{0}  \renewcommand{\thetable}{A\arabic{table}} \setcounter{figure}{0} \renewcommand{\thefigure}{A\arabic{figure}}}>

I also had to add to the following or it gave me a title for the footnotes (i.e. "Note:")
`kableExtra::footnote(alphabet=c(" 51", " 2", " 46"," 39"),threeparttable = TRUE,general_title = "" )`
