### ISSUE TITLE
French YAML argument for Tech Report

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#63]
The French version of a Tech Report is not currently handled. When I uncomment to French: true in index.Rmd, I get the following error on knit:

```
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Scanner error: mapping values are not allowed in this context at line 23, column 11
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted
```
I guess that there is a bit of work to be done to bring the French Tech Report to life.

**Comment by cgrandin** [comment]
I started doing this but was pulled to other tasks. It's halfway-implemented

**Comment by seananderson** [comment]
Did this not happen here? 
https://github.com/pbs-assess/csasdown/commit/a4d74fca82eca9911d71f11d001e3dd5ed7e5990
https://github.com/pbs-assess/csasdown/commit/32333ed826d9c45f62e19d51b8f8b8b93f3203cb
https://github.com/pbs-assess/csasdown/commit/95eb5581524576fed5296e597397ddea3235f24d

**Comment by cgrandin** [comment]
Yes! What I had missed was setting up the landscape part in the french tech report style file.

**Comment by ricardd** [comment]
I just rebuilt the package and created a draft Technical Report, uncommented line 24 and I still get the same error as above:

```
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Scanner error: mapping values are not allowed in this context at line 23, column 11
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted
```

**Comment by seananderson** [comment]
Just fixed that. It was missing a colon after `csasdown::techreport_pdf`. https://github.com/pbs-assess/csasdown/commit/a7563417a83d1446f5cb0004aed4b57fe0172502
