### ISSUE TITLE
Nasty little bug - cannot use underscores in table chunk names

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/csasdowntex#66]
The following produces awfulness in the TeX file:
````
```{r bad_chunkname, results = "asis"}
    d <- data.frame(x = c(1,2,3,4),
                    y = c(5,6,7,8),
                    z = c(9,10,11,12))
    csasdown::csas_table(d,
                         format = "latex",
                         font_size = 8,
                         caption = "XX - This table is broken")
```
````
Whereas this is just fine:
````
```{r goodchunkname, results = "asis"}
    d <- data.frame(x = c(1,2,3,4),
                    y = c(5,6,7,8),
                    z = c(9,10,11,12))
    csasdown::csas_table(d,
                         format = "latex",
                         font_size = 8,
                         caption = "XX - This table is fine")
```
````
For now, just don't use underscores in table chunk names but we should probably fix this at some point.

**Comment by seananderson** [comment]
I browsed into `fix_envs` and it's coming in from knitr broken.

```
"\\textbackslash begin\\{longtable\\}\\{rrr\\} \\textbackslash caption\\{(\\#tab:bad\\_chunkname1)XX - This table is broken\\}\\textbackslash{} \\toprule x \\& y \\& z\\textbackslash{} \\midrule 2 \\& 5 \\& 9\\textbackslash{} 2 \\& 6 \\& 10\\textbackslash{} 3 \\& 7 \\& 11\\textbackslash{} 4 \\& 8 \\& 12\\textbackslash{} \\bottomrule \\textbackslash end\\{longtable\\}"
```

I tried swapping `csasdown::resdoc_pdf` for `bookdown::pdf_book` and got the same problem, so I think this is a bookdown issue.

Just did some searching, and this is intended behaviour of bookdown:
https://bookdown.org/yihui/rmarkdown/r-code.html (search for underscore)
https://bookdown.org/yihui/bookdown/figures.html (see the first (!) note)

**Comment by cgrandin** [comment]
I found the same thing. It would be so nice if they had an error message saying so. I spent a good amount of time trying to figure it out!
