### ISSUE TITLE
References not knitting in reference section

### ISSUE THREAD

**Issue by obradovichs** [pbs-assess/csasdowntex#67]
@cgrandin as we discussed re issues with preparation of our tech report for submission in mid-August prior to submission of a Res Doc in late August

References do not knit into the reference section, but instead seem to knit in the spaces throughout the end of the document. We created a patch for this, but does not render properly without this line in the reference section.

`<div id="refs"></div>`

**Comment by seananderson** [comment]
Does putting a `\clearpage` right before the `# REFERENCES` line fix things? I'm not sure what you mean by "knit in the spaces throughout the end of the document". You mean around figures that flow to the end?

The references should be appearing as the very last thing in the document.

**Comment by obradovichs** [comment]
I think the knit in the spaces around may have been remembered incorrectly. I believe they knit at the end of the document, but we would like to place the references section before the figures and tables sections as is common in tech reports. We created a bibliography.Rmd that is placed before these other sections in the bookdown.yml.

**Comment by seananderson** [comment]
`<div id="refs"></div>` is the only way to place the bibliography somewhere other than the end with R Markdown. This is a limitation of R Markdown. You're welcome to use that or just leave the references at the end. I'm sure that's fine too -- it is fine for research documents.

**Comment by obradovichs** [comment]
Thanks so much for all your help in understanding RMarkdown/csasdown!
