### ISSUE TITLE
Font/margins/lines in tech report

### ISSUE THREAD

**Issue by obradovichs** [pbs-assess/csasdowntex#68]
@cgrandin as we discussed re issues with preparation of our tech report for submission in mid-August prior to submission of a Res Doc in late August

csasdown appears to be using latex default settings and perhaps some settings for csasdown res docs/SRs (e.g. line at top and bottom of each page, table of contents, table of tables, etc.) in the tech report style file (i.e. tech-report.sty). Personally, I think the style of the TTT Workshop technical report would be an appropriate style.

#1 Lines - Matt Grinnell directed me to these lines in the .sty file and suggested updating pagestyle{fancy} to pagestyle{empty}, but every time we knit it gets overwritten because it is drawing from the csasdown repository (?)

`% Settings for the main document`
`\pagenumbering{arabic}  % Regular page numbers`
`\pagestyle{fancy}  % No page number on first page of main document, use 'empty'`
`\renewcommand*{\thefootnote}{\arabic{footnote}}  % Back to numeric footnotes`
`\setcounter{footnote}{0}  % And start at 1`

#2 Margins - Matt Grinnell directed us to line 159 where the 1 inch margins are currently commented out. We tried to change but everytime we knit it gets overwritten because it is drawing from the csasdown repository (?)
`%\usepackage[top=1in, bottom=1in, left=1in, right=1in]{geometry}`

#3 Font - we don't know how to change this.

#4 Table of contents, Table of Figures, Tables of Tables - we don't know how to change this, but adds a lot of pages

**Comment by seananderson** [comment]
All fixed here: https://github.com/pbs-assess/csasdown/commit/8527908a9e4dab73411eca3a91a96ec22354b709

I believe the default LaTeX font (Computer Modern) is fine, but I turned on Helvetica here to match the Res Docs.

If you want to play with these things in the future, you need to modify the files in the `inst` folder of the package and reinstall because the style files get copied over every time you compile.

**Comment by obradovichs** [comment]
Thank you! Maybe removing the Table of Tables and Table of Figures won't be a popular choice. I was very focused on one tech report and realize that many others do include them.
