### ISSUE TITLE
Format of references in tech-report.sty

### ISSUE THREAD

**Issue by obradovichs** [pbs-assess/csasdowntex#70]
Current tech-report.sty file produces:
![image](https://user-images.githubusercontent.com/45372441/62430222-768d4a00-b6ce-11e9-9cf9-1ff86b0772c1.png)

Would it be possible to switch to a style similar to the csas documents (or perhaps left justified?) with a empty row between references, as the default in the .sty file?

**Comment by obradovichs** [comment]
I changed two lines in the tech-report.sty file and made a pull request.

`\setlength\parindent{0pt}  % No indent paragraphs`
`\parskip 2ex  % Increase white space between paragraphs`

**Comment by cgrandin** [comment]
Note that this is a personal preference and someone else may come along later and want it the other way, and inadvertently change this back again.

**Comment by obradovichs** [comment]
@cgrandin @seananderson 
Ok. The Guide For the Production of Fisheries and Oceans Canada Reports (https://waves-vagues.dfo-mpo.gc.ca/Library/333125.pdf): says "References are formatted according to Instructions to Authors for the Canadian Journal of Fisheries and Aquatic Sciences, NRC Research Press at: http://www.nrcresearchpress.com/page/cjfas/authors#9d.", which says:

"The reference list must be double-spaced and placed at the end of the text. References must be listed in alphabetical order according to the name of the first author and not numbered."

Several tech reports I've seen have a space between references and have a hanging indent, similar to the CSAS Res Doc.

-----

Reference Order
Additionally, the Guide For the Production of Fisheries and Oceans Canada Reports requests the following order of references in the list:

"References are listed at the end of the report, in alphabetical order according to surname of the first author. References with the same first author are listed in thefollowing order: papers with one author only are listed first in chronological order; papers with dual authorship follow and are listed in alphabetical order by the last name of the second author; and papers with three or more authors appear after the dual–authored papers and are arranged chronologically."

The current csl file does not do this, instead ordering references with the same first author and 2 or more authors in alphabetical order. 

Is there a csl from the TTT workshop or has someone else already published a csasdown tech report and modified the csl file?

**Comment by seananderson** [comment]
Our .csl file is the CJFAS one with a couple modifications. It's the same one that's been used in the research documents and I think the TTT technical report. I wouldn't worry about those other specifics unless someone complains.
