### ISSUE TITLE
Centering landscape csas_table

### ISSUE THREAD

**Issue by obradovichs** [pbs-assess/csasdowntex#75]
Is there a way to center landscape tables on the page (between left and right edges)? Adjusting position appears to only center it relative to the top and bottom of the page.

**Comment by seananderson** [comment]
Does this work?
https://stackoverflow.com/a/44491267
or is that what you were already trying?

**Comment by obradovichs** [comment]
This is what I was trying and only centers the landscape table relative to the top/bottom of the page (in portrait).

**Comment by seananderson** [comment]
Not sure, we're definitely pushing the boundaries of R Markdown to LaTeX translation. [This answer](https://tex.stackexchange.com/questions/109920/centering-table-in-landscape-page/109922) suggests that using `[p]` or `\vspace*{\fill}` could work. It might be possible to use the `[p]` paragraph option for floating instead of ht etc. I'm not sure if the vspace approach could be translated via knitr.

Is there any possibility this is not that terrible looking and you could just live with it? ;)

**Comment by obradovichs** [comment]
Absolutely! But I have to at least try first and make sure it isn't just ignorance on my part. :)

**Comment by grinnellm** [comment]
Unfortunately this is now causing issues with the herring SR (see above reference). Did you find a work-around @obradovichs?

**Comment by obradovichs** [comment]
Unfortunately we did not find a simple solution before submitting for review and decided we could live with it in our Res Doc.

**Comment by grinnellm** [comment]
I'm not sure what to try next. Do you have any suggestions @seananderson?

**Comment by seananderson** [comment]
Not besides what I wrote on Aug 21 above referencing these answers https://tex.stackexchange.com/questions/109920/centering-table-in-landscape-page/109922

Can you get a minimal working example in csasdown that shows the centering problem?

One hacked solution would be for us to grep through the .tex and make it match one of the above solutions or maybe using xtable would give enough flexibility (but then not work for Word output, but maybe that's fine).

**Comment by cgrandin** [comment]
Actually this particular table is using the xtable package. So it seems to be an issue for either kable or xtable which means probably a root latex issue.

 I will take another look at this soon, I've just been busy with other issues

**Comment by seananderson** [comment]
I forget if we are using the lscape or landscape package, but with lscape, these should work:

```tex
\documentclass{article}
\usepackage{float,lscape}
\begin{document}
\begin{landscape}
    \topskip0pt
    \vspace*{\fill}
    \begin{table}[htb!]
        \centering
        \tiny
        \setlength{\tabcolsep}{2pt}
        \begin{tabular}{|ll|*4r|*4r|*4r|*4r|*4r|}
        % ...
        \end{tabular}
        \caption{A very wide table}
        \label{tab:wide_table}
    \end{table}
    \vspace*{\fill}
\end{landscape}
\end{document}
```

```tex
\documentclass{article}
\usepackage{float,lscape}
\begin{document}
\begin{landscape}
    \begin{table}[p]
        \centering
        \tiny
        \setlength{\tabcolsep}{2pt}
        \begin{tabular}{|ll|*4r|*4r|*4r|*4r|*4r|}
        % ...
        \end{tabular}
        \caption{A very wide table}
        \label{tab:wide_table}
    \end{table}
\end{landscape}
\end{document}
```

The issue is how to get an R function to create that output... and whether or not we use lscape.

**Comment by cgrandin** [comment]
Matt, can you confirm this makes a properly centered table using raw latex? This is direct raw output from the table code with a wrapper.. thx
GitHub doesn't support TEX files, so you should change the extension to "tex" or whatever. Or not.

[a.txt](https://github.com/pbs-assess/csasdown/files/3708708/a.txt)

**Comment by cgrandin** [comment]
Hmm. Seems to work fine when I put \begin{landscape} and \end{landscape} around the tables..

[sr.pdf](https://github.com/pbs-assess/csasdown/files/3708717/sr.pdf)

**Comment by grinnellm** [comment]
What happens if you increase the font?

**Comment by grinnellm** [comment]
I was using `landscapepage`s so that the header and footer lines, and page numbers appear on the correct side (at least as I understand it).

**Comment by cgrandin** [comment]
We totally gave up on having the footers and headers on the landscape sides because I spent something ridiculous like 3 days trying. I could take another look but can't really justify a whole bunch of time on it.

**Comment by grinnellm** [comment]
Ok, I'm fine either way:) I thought it was a CSAS requirement.

**Comment by cgrandin** [comment]
The centering issue is because of the tabularx environment. I'm working on it

**Comment by grinnellm** [comment]
Just talked with Ann (CSAS), and it's still required that header and footer lines including page numbers are on the top and bottom of the page on landscape pages. The way it currently is (headers and footers on the sides) will not pass inspection:/

**Comment by cgrandin** [comment]
I'll take another look at this.

**Comment by cgrandin** [comment]
After looking at it again, it just isn't feasible without learning KOMA-script and re-implementing the whole style file to use this language to replace the fancyheader package. That is out of the scope of what can be done given our current workload, so we will just submit documents as-is or make smaller tables which don't have to be landscape.

**Comment by grinnellm** [comment]
Thanks for taking another look at this Chris.

**Comment by grinnellm** [comment]
I think I got this working in the `sideways` branch -- I'll merge it soon if it passes Travis.
