### ISSUE TITLE
Quick fix for hanging paragraph indents for sections after the reference section

### ISSUE THREAD

**Issue by obradovichs** [pbs-assess/csasdowntex#76]
Wondering if anyone knows a quick fix for this? If not, will figure out after the document is submitted.

**Comment by seananderson** [comment]
Adding these after: https://github.com/pbs-assess/csasdown/blob/master/R/utils.R#L285
(one backslash)

But that should already be added after the references section automatically.

**Comment by obradovichs** [comment]
Thanks, Sean! Not sure why it wasn't automatically added this, but adding that one line to the first appendix fixed it.
