### ISSUE TITLE
Table of Contents in French Tech Report

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#80]
When I modified the Technical Report style file to use "TABLE DES MATIÈRES" for the Table of Contents on page iii, it had an unfortunate side effect that messed up the pagination:

![Capture](https://user-images.githubusercontent.com/1110182/64617908-a3abd700-d3b5-11e9-9237-6fd8d9958a49.PNG)

Could one of the LaTeX guru (@seananderson @cgrandin @andrew-edwards @grinnellm ) check how this could be fixed?

**Comment by cgrandin** [comment]
I also changed the size of the TOC title so that English and French ones are the same.
