### ISSUE TITLE
Science Response not knitting

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#81]
The draft SR does not knit on my machine.

The problem seems to be coming from \MakeAvailable 

```
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.147 \MakeAvailable
```

Is anyone else getting this error?

**Comment by ricardd** [comment]
I just updated the package, I still can't knit but the error is different:
```
Package hyperref Warning: Option `pdftex' has already been used,
(hyperref)                setting the option has no effect on input line 1369.

) (C:\Users\RicardD\AppData\Roaming\MiKTeX\2.9\tex/latex/textcase\textcase.sty)
) (sr.aux)
Runaway argument?
{\contentsline {se 
! File ended while scanning use of \@writefile.
<inserted text> 
                \par 
l.71 \begin{document}
                     
? 
```

**Comment by cgrandin** [comment]
@jaclyncleary has this problem, but she just commented out \MakeAvailable on her own csasdown repo because we had a due date and the rest of us could knit properly and make the document. It is also with the SR.
We didn't solve it.

 I would suggest re-installing tinytex from scratch.
Please let us know if you figure it out as she still needs to fix her system. Thanks

**Comment by ricardd** [comment]
@cgrandin I uninstalled and reinstalled tinytex but still get the same error.

```
! LaTeX Error: There's no line here to end.
```

**Comment by seananderson** [comment]
We're going to need more to figure it out.

If you run the following:
```r
testing_path <- paste0(tempdir(), "/testing_directory_sr")
dir.create(testing_path, showWarnings = FALSE)
setwd(testing_path)
rmarkdown::draft("index.Rmd",
  system.file("rmarkdown",
    "templates",
    "sr",
    package = "csasdown"
  ),
  create_dir = TRUE,
  edit = FALSE
)
setwd(file.path(testing_path, "index"))
bookdown::render_book("index.Rmd",
  csasdown::sr_pdf(),
  envir = globalenv()
)
```

presumably it returns that error for you? And presumably you can't compile `sr.tex` if you make sure it is in the `index` folder?

If so, can you send on a zip of the folder making sure to include the `.log` file?

Presumably the current resdoc template builds?

I wonder if it has to do with the textcase package, which isn't used in the Res Doc, but comes up in your error message above. Could try removing that functionality (if it's actually getting used) and commenting out that package. It shouldn't be absolutely necessary.

https://github.com/pbs-assess/csasdown/search?q=textcase&unscoped_q=textcase

**Comment by cgrandin** [comment]
I noticed your error has "MikTex" in it. Make sure that's uninstalled from your machine or it will use that instead of tinytex

**Comment by ricardd** [comment]
Sorry for the potential confusion with using MiKTeX, 

I tried to compile the sr.tex file using MiKTeX's TexWorks, which is where the error I pasted above comes from. 

However, I can confirm that TinyTeX is used when assembling the PDF from RStudio, and that it encounters the same error, log file below.

[sr.log](https://github.com/pbs-assess/csasdown/files/3702277/sr.log)

**Comment by seananderson** [comment]
The problem is somewhere in `\MakeAvailable` in the SR style file. Hard for me to troubleshoot without a computer that causes the error. Can you try commenting on various sections of the command in the style file to isolate what is causing the problem? Start by commenting out everything in that command or just commenting of the `\MakeAvailable` line in the tex file to confirm first. Maybe something about some character that's coming through as one of the parameters like `rdAddress`?

https://github.com/pbs-assess/csasdown/blob/aa2408a4847f1666c0f3395da8d175df08b5e359/inst/csas-style/sr.sty#L572-L608

**Comment by ricardd** [comment]
@seananderson thanks, that was my diagnostic too, I will attempt your proposed steps tomorrow.

**Comment by seananderson** [comment]
I feel like I fought with this issue before somewhere else and it came down to the `\emph{}` wrapping the parameter commands here: https://github.com/pbs-assess/csasdown/blob/aa2408a4847f1666c0f3395da8d175df08b5e359/inst/csas-style/sr.sty#L603-L605

**Comment by ricardd** [comment]
OK, I identified the phone number as the culprit.

For some reason the left and right brace around the area code creates the "There's no line here to end." error.

So in index.Rmd, changing from:
```
phone: (506) 851-6253
```
to:
```
phone: 506-851-6253
```

fixes the problem.

Now, how to add the braces to the output, and why does it cause the error?

**Comment by cgrandin** [comment]
That's weird. I'll ask @jaclyncleary to try the same on her machine and see if it was the same issue. I will bet it is. If so, can we just leave out the parens in the phone number ? I'm ok with that if CSAS is

**Comment by ricardd** [comment]
Did @jaclyncleary try my fix above?

**Comment by cgrandin** [comment]
Not yet, she is super busy with stakeholder meetings and travel etc. at the moment.
