### ISSUE TITLE
Science Response: no hanging indent in references

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#87]
In the Science Response, shouldn't the references that appear in "Sources of information" have a hanging indent? 

While the style file defines a hanging indent (https://github.com/pbs-assess/csasdown/blob/db542cefead9b75c84c97a79c32691b0050f6674/inst/csas-style/sr.sty#L405-L406), the rendered PDF doesn't have one:

![Capture](https://user-images.githubusercontent.com/1110182/66593310-1fdc3a80-eb6d-11e9-8794-f09b4563859f.PNG)

**Comment by seananderson** [comment]
That line doesn't do anything here. It only affects BibTeX bibliographies but this one is parsed by Pandoc into text. The hanging indent should be added here on the fly:
https://github.com/pbs-assess/csasdown/blob/db542cefead9b75c84c97a79c32691b0050f6674/R/utils.R#L307-L319

but it is grepped for here:
https://github.com/pbs-assess/csasdown/blob/db542cefead9b75c84c97a79c32691b0050f6674/R/utils.R#L295-L296

which obviously doesn't currently match "Sources of information".

**Comment by ricardd** [comment]
regular expression to the rescue @cgrandin ?

\\chapter{R[a-zA-ZÀ-Ö]F[a-zA-ZÀ-Ö]RENCES}|\\chapter{Sources [a-zA-Z]+ [a-zA-Z]+}

**Comment by seananderson** [comment]
Might be easiest to check 2 regular expressions and then use an or statement?

**Comment by ricardd** [comment]
3ac359e9c914d5fe0836921f330023201ff8bd7e

I think that fixes it.

**Comment by seananderson** [comment]
I swapped it for a more robust detection here https://github.com/pbs-assess/csasdown/commit/7cdc6ea1df80f5793823e882585a78752f686a9f
