### ISSUE TITLE
Science Response: alignment of short title in page header

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#88]
I am wondering why, when a short title must span more than one line, it is justified right in the page header in English:

![Capture](https://user-images.githubusercontent.com/1110182/66593570-a1cc6380-eb6d-11e9-8960-3e5956049c01.PNG)

but is centered in French:

![Capture2](https://user-images.githubusercontent.com/1110182/66593587-aabd3500-eb6d-11e9-9d2e-056f534c1fd0.PNG)

**Comment by seananderson** [comment]
No idea. Presumably something is different between the style files for how the header is defined?

**Comment by ricardd** [comment]
I looked at both style files, but they handle the header the same way.

https://github.com/pbs-assess/csasdown/blob/db542cefead9b75c84c97a79c32691b0050f6674/inst/csas-style/sr.sty#L336

https://github.com/pbs-assess/csasdown/blob/db542cefead9b75c84c97a79c32691b0050f6674/inst/csas-style/sr-french.sty#L336

**Comment by seananderson** [comment]
Except one has `\fancyhead[R]` and the other `\fancyhead[C]`!

**Comment by ricardd** [comment]
thanks @seananderson , good eye
