### ISSUE TITLE
Wrong indentation after 'Sources of information' section in SR

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#90]
Text in sections following 'Sources of information' is indented and sometimes hanging paragraphs.

**Comment by grinnellm** [comment]
See pbs-assess/herringsr#56 and https://github.com/pbs-assess/csasdown/commit/f7179bd4f24c521367dafd03e84789a59bbba712.

**Comment by cgrandin** [comment]
See issue #87

**Comment by grinnellm** [comment]
This doesn't seem to be fixed for me. I might be missing something?

**Comment by seananderson** [comment]
It had just been so long with accepted documents that I assumed it had been fixed.

Does this solution work? https://github.com/pbs-assess/csasdown/commit/f7179bd4f24c521367dafd03e84789a59bbba712#commitcomment-35612791

and the issue is just that it needs to be manually added?

**Comment by grinnellm** [comment]
Yes, that manual solution works -- I have it right in the [bibliography file](https://github.com/pbs-assess/herringsr/blob/master/english/09_bibliography.Rmd). Not sure if we want a cleaner fix? Is there a way to move those lines to either "sr.sty" or "sr.tex"? I think this is only an issue in SRs with Appendices etc after the References, which is maybe why it hasn't been an issue for others; not sure if that's common outside herring.

**Comment by grinnellm** [comment]
This seems to be fixed in the current herring SR -- the manual solution (above) is no longer required. 

For anyone who still has the manual solution: that solution is now causing the references themselves to be indented (see below). When I removed those 3 lines, the references look good and the sections following the references are good too.

![Untitled](https://user-images.githubusercontent.com/25674027/140186501-5f6075c0-0a7e-4b12-9e5f-e733cf9b6019.jpg)

**Comment by grinnellm** [comment]
Well, not fixed apparently. That manual fix is still required to get the proper margins in the Appendix, but something is causing the references to have an extra wide left margin like in the above picture. See "07_bibliography.Rmd" in the attached zip file.

[header.zip](https://github.com/pbs-assess/csasdown/files/7477161/header.zip)
