### ISSUE TITLE
Paragraphs often have an extra line with only one word

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#91]
I'm not sure if this is specific to SRs, but paragraphs often push the last word to a new line when the word would fit on the previous line. I'm sure I'm not explaining this clearly, so I attached a PDF that I created with the attached zipped file. There is plenty of space for the word "items)." to fit on the 4th line, but it gets moved to a new line.
[sr.pdf](https://github.com/pbs-assess/csasdown/files/3757558/sr.pdf)
[temp.zip](https://github.com/pbs-assess/csasdown/files/3757568/temp.zip)

**Comment by seananderson** [comment]
Can’t see the PDF right now, but there are some LeTeX parameters that affect the penalties for that kind of thing. One of them has to do with ‘orphans’. I can look them up later.

**Comment by grinnellm** [comment]
Sorry you can't see the PDF; here's an image from it that shows the issue:
![image](https://user-images.githubusercontent.com/25674027/67325998-d378ef00-f4ca-11e9-93ff-23d101ec839f.png)

**Comment by grinnellm** [comment]
Also, this is a small issue so I'm hesitant to even make it an "issue" :) But it does seem to be some sort of error so I decided to post it in case there's a solution. 
I did see the `\widowpenalty` options, but this seems to be a different issue?

**Comment by cgrandin** [comment]
Not a "perfect answer" but... https://tex.stackexchange.com/questions/204084/how-to-prevent-the-orphan-word-of-paragraphs

The second answer there is even more hack-ish but might work.

**Comment by seananderson** [comment]
I think we’re in raggedright land, which has known problems with this. Haven’t done the research to see if there’s a solution.

**Comment by grinnellm** [comment]
Thanks for the suggestions. I tried adding the following to the YAML but it didn't seem to affect the output:
`\usepackage{microtype}`
`\everypar{\looseness=-1}`

**Comment by seananderson** [comment]
See my changes here: https://github.com/pbs-assess/csasdown/commit/5fde12d47f31ab1abd404ca7b1c1e89ec17d3c7f

The important change is using `\RaggedRight` from ragged2e. Then you need to pick a hyphenation penalty if you want fewer hyphens. By default it hyphenates a lot of stuff. I dialled it back a bit.

I'm not sure what CSAS's policy is on hyphenation to improve wrapping... and maybe I don't want to know.
![image](https://user-images.githubusercontent.com/19349/67436905-6fc2f480-f5a4-11e9-94b4-9a336e88e1df.png)

**Comment by grinnellm** [comment]
Thanks for this Sean. I'll have to try tomorrow because I can't seem to load "ragged2e" right now.

**Comment by grinnellm** [comment]
That looks much nicer, even considering that it's ragged:) Thanks!
