### ISSUE TITLE
repeat column headings on long tables in landscape using csas_table

### ISSUE THREAD

**Issue by ErikaDAnderson** [pbs-assess/csasdowntex#92]
I made a repo with an example table in results section at  https://github.com/ErikaDAnderson/kableStylingExample

The long table has headings, above the column names, on a wide table that goes over multiple pages. I would like csas_table to repeat the headings on subsequent pages of the table, if possible. 
Thank you.

**Comment by seananderson** [comment]
Do you mean repeat the caption? For me it looks like the headings are repeating:

![image](https://user-images.githubusercontent.com/19349/67440517-5e7ee580-f5ae-11e9-9506-5d705d51e836.png)

Are you using the latest tinytex installation?

**Comment by ErikaDAnderson** [comment]
Table 2 is your example table that I never deleted. Have a look at Table 3. The letter column headers do not repeat on the second page.

I am running tinytex_0.16

**Comment by seananderson** [comment]
This is from a secondary row header added above the other header. Short and unsatisfying answer is probably to try not to do this. It looks like it's possible in raw .tex, but the `add_header_above()` contents aren't getting added to the header section only to the first header section. I have no idea if that's even possible with kableExtra. You could writing out all the tex code, which would be messy, or possibly use xtable. Best bet is probably to avoid using multiple headers that have to repeat on multiple pages. Using LaTeX/Pandoc is most efficient when you go with the flow wherever possible.

**Comment by ErikaDAnderson** [comment]
I appreciate the input. It is good to know that I am not missing anything obvious. 

We have non consecutive event numbers, and the primary author likes to add consecutive tow numbers above the event numbers. KableExtra::kable does repeat these headers with repeat_headers, but there are other issues.

**Comment by cgrandin** [comment]
I see the issue.

In your example repo, you need to look at the argument list for ```add_header_above()```. The align argument will help you I think:

```
csasdown::csas_table(
  widelong_df2,
  caption = "Example of long wide table with header above column names",
  format = "latex",
  escape = FALSE,
  landscape = TRUE,
  repeat_header = TRUE,
  font_size = 8) %>%
  add_header_above(c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N"),
    line_sep = 0,
    align = "r")
```

**Comment by cgrandin** [comment]
Oh, there's more to this, you don't just want to align the extra headers but add them to the continued pages along with the regular headers. I'll look into it.

**Comment by cgrandin** [comment]
Done here: 6ca654104db51670e7d29dc. I had to modify a non-exported function of kableExtra and created a new function for it called ```add_extra_header()```.

You can make the example table code work by calling this:
```
csasdown::csas_table(
  widelong_df2,
  caption = "Example of long wide table with header above column names",
  format = "latex",
  escape = FALSE,
  landscape = TRUE,
  repeat_header = TRUE,
  font_size = 8,
  extra_header = toupper(letters[1:ncol(widelong_df2)]),
  ex_line_sep = 0,
  ex_align = "r")

```
There are a bunch of ex_* arguments now to ```csas_table()```. I couldn't use ```...``` due to poor implementation of inner ```kable``` functions (they don't all pass ```...``` and subsequently fail).

Glad I did this, I have a much better knowledge now of how ```kable``` works internally.

**Comment by seananderson** [comment]
Yikes! Nice job.

**Comment by ErikaDAnderson** [comment]
Thank you - that helps and it was quick too!

**Comment by cgrandin** [comment]
@seananderson I had to turn off "warnings as errors" on Travis though as the ```:::``` scoping was throwing errors and this needs those internal functions to work. Hope that's ok
