### ISSUE TITLE
Multiple figure cross-references together

### ISSUE THREAD

**Issue by ErikaDAnderson** [pbs-assess/csasdowntex#97]
Not a csasdown issue, but you may have solved it. Your issue #40 about crossing referencing figures almost addressed it, and it is not covered in the FAQ https://github.com/pbs-assess/csasdown/wiki.  I am cross referencing figure captions in rmarkdown script. I would like to clean up a couple of the figure references; e.g., “Figure 4 to Figure 19” should be “Figures 4-19”. I did not use one figure with letters, since each plot is already two plots using cowplot.

The Rmarkdown is:

Length frequency plots for Pacific Salmon (Figure \@ref(fig:chinookLW), Figure \@ref(fig:chumLW), Figure \@ref(fig:cohoLW), Figure \@ref(fig:pinkLW), and Figure \@ref(fig:sockeyeLW)) illustrate that this survey encounters both juveniles (<300 mm) and adults, with a higher proportion of juvenile specimens.

And each figure captions is generated:

{r chumLW,   fig.cap="\\label{fig.path:chumLW}Chum salmon (\\textit{Oncorhynchus keta}) length frequency plots for specimens sampled during the  2019 Integrated Pelagic Ecosystem Survey aboard the M.V. Nordic Pearl, June 15-July 15, 2019 (A. top panel).  Double log-transformed length-weight regression with outliers removed, using a Bonferroni outlier test (B. bottom panel)."}

(Minor note is that we will use R variables in the figure captions next year. We discovered text cross referencing late in the process for fig captions).

The knitted version says:
Length frequency plots for Pacific Salmon
(Figure 7, Figure 5, Figure 6, Figure 9, and Figure 8) illustrate that this survey encounters
both juveniles (<300 mm) and adults, with a higher proportion of juvenile specimens.

I can modify it to say "Figure 5 to Figure 8", but cannot figure out to say "Figures 5-8". Suggestions would be appreciated, as google has not been as helpful as usual. Or even if "it is not worth the effort", would be good to know.
Thank you.

**Comment by cgrandin** [comment]
Can't you just do:

```
Figures \@ref(fig:chinookLW)-\@ref(fig:chumLW)
```

**Comment by seananderson** [comment]
Also, you shouldn't need `\label{fig.path:chumLW}`. It will get the label `fig:chumLW` by default. Unless you wanted to change it.

**Comment by ErikaDAnderson** [comment]
Yes 
` r Figures \@ref(fig:chinookLW)-\@ref(fig:chumLW) ` works. I was lost in the weeds before coffee.
Thank you.
