### ISSUE TITLE
Minor Formatting Changes- Hanging Indent References Tech Report

### ISSUE THREAD

**Issue by HilariDB** [pbs-assess/csasdowntex#98]
Hi,
I'm working on the same tech report as @ErikaDAnderson and we are having an issue getting our references into a hanging indent format. This is the format that we are hoping to use:
![image](https://user-images.githubusercontent.com/49734331/69456456-8e411a80-0d1f-11ea-83c1-67f5936c9b4d.png)

This is what the tech report currently produces:
![image](https://user-images.githubusercontent.com/49734331/69456518-ae70d980-0d1f-11ea-8ca9-49b66a23ad92.png)

Essentially we are looking to tab all subsequent lines after the first line. If you would like more information please let me know. 
Thanks

**Comment by seananderson** [comment]
Good point. Looks like we've done substitutions on the fly to adjust the indentation for the references for SRs and Res Docs but not Tech Reports.

As a quick fix I added the code into the template .Rmd files. Can you try adding this? https://github.com/pbs-assess/csasdown/commit/481d8e2c5fcbb139d1cfda1e06c5a04f58e33e68

**Comment by ErikaDAnderson** [comment]
Thanks for the quick fix! I added that code to our 05_bibliography.Rmd file and here is the results:
![image](https://user-images.githubusercontent.com/39602850/69459644-1971de80-0d27-11ea-8a47-3f07699a3887.png)

**Comment by HilariDB** [comment]
Great, thanks for the fix Sean!
